- src/views/ModelPlan/TaskList/index.test.tsx
- Updated `Status` test
1. Run `yarn test src/views/ModelPlan/TaskList/index.test.tsx`
2. Ensure no tests are failing
> [NOREF] Fix TaskList test

- pkg/storage/SQL/plan_collaborator_fetch_by_model_plan_id.sql
- Fixes use of parenthesis in a select statement.
> [NOREF] Fix SQL formatting and use of parenthesis

- .github/workflows/run_tests.yml
- scripts/testsuite
- Clone of https://github.com/CMSgov/easi-app/pull/1680, which removes python from our CI workflow.
- Make a copy of this branch.
- Modify the required code coverage to 100%
- Commit to that branch and ensure that this job fails.
> [NOREF] Remove python from CI

- .pre-commit-config.yaml
- Introduce `no-commit-to-branch` hook
This PR introduces a new pre-commit hook, [no-commit-to-branch](https://github.com/pre-commit/pre-commit-hooks#no-commit-to-branch). This is an official pre-commit hook which effectively fails a commit if it is on a branch that matches a name or pattern.
The regex used for this are, at time of writing:
```regex
^(?!((main|master)|(EASI-\d{0,5}|NOREF|dependabot|feat\/EASI-\d{0,5})\/[a-zA-Z0-9\-]+)$).*
```
There is a negative lookbehind (`?!`) because the hook is looking for branches which are not allowed to be committed to, but we want to specify ones we _are_ allowed to commit to, so we negate the regular expression. This means the following branch patterns are allowed:
- `main` & `master`
- These are set so when we run this in CI it doesn't break …
> [NOREF] Add pre-commit hook for enforcing branch naming patterns

- src/queries/UpdateModelPlan.ts
- src/queries/UpdateModelPlanAndBasics.ts
- src/queries/types/UpdateModelPlan.ts
- src/queries/types/UpdateModelPlanAndBasics.ts
- src/views/ModelPlan/TaskList/Basics/index.tsx
- Fixes Task List status failing to update
1. Before checking out branch, create and navigate to a model task list
2. Click `Update` next to Status 
3. See in a 422 console error 
4. Check out this branch, and redo the steps
5. Ensure no error and status tag gets updated. 
> [NOREF] fix update status

- .pre-commit-config.yaml
- cypress/support/graphql-test-utils.js
See `easi-app` PR here: https://github.com/CMSgov/easi-app/pull/1743
- Update regex to require `feature` instead of `feat`.
- Update regex to require feature branches look like `feature/EASI-2021`. Branches that merge into it will be ticket branches, like `EASI-2021/backend` or `EASI-2021/fix-type-error`
https://regex101.com/r/gl4XGb/2
Click "unit tests" on the left, and ensure it's set to "python" for the flavor.
> [NOREF] Fix pre-commit pattern for feature branches

- MINT.postman_collection.json
- pkg/graph/generated/generated.go
- pkg/graph/schema.graphql
- pkg/graph/schema.resolvers.go
- Introduce `query crTdl` which gets a single CR/TDL by ID
> [NOREF] Single query to get cr/tdl

- src/views/ModelPlan/TaskList/Basics/Milestones/index.tsx
- src/views/ModelPlan/TaskList/OpsEvalAndLearning/IDDOC/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/OpsEvalAndLearning/IDDOC/index.tsx
- src/views/ModelPlan/TaskList/Payment/Recover/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/Payment/Recover/index.tsx
There was an issue with date form components not loading data on hard browser refresh.  This PR addresses a previous workaround, and correctly loaded the date within the form.  
Date form components still need to wait for loading before render, which is different than other form components.  This seems to be a quirk of DatePicker.  May come back to address this in another ticket.
Navigate to OpsEval page 2, or last page of Payments, and ensure existing dates render on hard browser refresh
> [NOREF] - Fixed date not rendering on hard refresh

- src/utils/status.ts
- src/views/ModelPlan/TaskList/Basics/Milestones/index.tsx
- src/views/ModelPlan/TaskList/Beneficiaries/Frequency/index.tsx
- src/views/ModelPlan/TaskList/GeneralCharacteristics/Authority/index.tsx
- src/views/ModelPlan/TaskList/OpsEvalAndLearning/Learning/index.tsx
- src/views/ModelPlan/TaskList/ParticipantsAndProviders/ProviderOptions/index.tsx
- src/views/ModelPlan/TaskList/Payment/Recover/index.tsx
- Moved the `sanitizeStatus` util to the mutation, rather than sanitizing on the query data
- Create a model plan and got to IT tools page seven
- Click redirect on question 2
- Verify the mutation from autosave or manually is working
- Check no linting/ts errors with input types
> [NOREF] - Task status TS fix

- MINT.postman_collection.json
- Update the postman collection to create a model plan, and also store the ids from the response body as an environment variable.
- Update relevant existing queries to use these valuables where appropriate
- This will remove the need to copy and paste `UUID` from a response to another  query
1. Import the new postman collection.
2. Run the new query to set environment variables
3. Run another query that uses the new variable (eg getModelPlan)
> NOREF Create modelPlan and Store Relevant ID

- src/utils/modelPlan.ts
- src/views/App/index.tsx
- src/views/ModelPlan/ReadOnly/GeneralCharacteristics/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/GeneralCharacteristics/index.test.tsx
- src/views/ModelPlan/ReadOnly/GeneralCharacteristics/index.tsx
- src/views/ModelPlan/ReadOnly/ModelBasics/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/ModelBasics/index.tsx
- src/views/ModelPlan/ReadOnly/ParticipantsAndProviders/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/ParticipantsAndProviders/index.tsx
- src/views/ModelPlan/ReadOnly/Payments/index.tsx
- Added `translateBooleanOrNull` to better handle/translate boolean or null data values
- Added `translateNewModel` translation function
- Added Redirect `.../read-only` to `../read-only/model-basics`
- Added `dateOrNoAnswer` function to DRY up code in `src/views/ModelPlan/ReadOnly/ModelBasics/index.tsx`
1. Attempt to nagivate to `http://localhost:3005/models/---MODEL_ID----/read-only/`and check URL to see it actually goes to `.../read-only/model-basics`
2. Ensure there is no errors when going through each of the subpages
3. Any `No answer entered` should be grey and italicized  
- …
> [NOREF] New Translate Function And Read Only Redirect

- cypress/e2e/modelPlan.spec.js
- src/components/AskAQuestion/index.test.tsx
- src/i18n/en-US/draftModelPlan/basics.ts
- src/i18n/en-US/draftModelPlan/discussions.ts
- src/i18n/en-US/home.ts
- src/i18n/en-US/modelPlan.ts
- src/i18n/en-US/modelPlanTaskList.ts
- src/views/ModelPlan/ReadOnly/ModelBasics/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/StepsOverview/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/StepsOverview/index.tsx
- src/views/ModelPlan/TaskList/Basics/Milestones/index.tsx
- src/views/ModelPlan/TaskList/Basics/Overview/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/Basics/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/Basics/index.tsx
- src/views/ModelPlan/TaskList/index.tsx
- Content updates to task list for both user and assessment roles
- For regular user, only `Basics` and `General Characteristics` were updated
- Content updates to process list
- Updates to `Basics` CMMI Group visibility and info
- `Milestones` clearance info added
- `Discussions` info update
- Other minor text updates not noteworthy
[Figma](https://www.figma.com/file/M72DReE73SSXMN48WZfaKN/MINT---New-Model-Process-(Model-Intake)?node-id=3872%3A256455)
Log in as both a collaborator and assessment team member, and verify text changes reflect Figma
- Always make comments, even if it's …
> EASI 2295 - Content revisions for task list and process list

- src/views/ModelPlan/Discussions/index.tsx
NOREF
- Added the assessment icon when replying to a question
- answer a question in the discussion center as an assessment user and verify icon
> [NOREF] Added assessment icon in reply

- src/queries/ITSolutions/GetOperationalNeeds.ts
- src/queries/ITSolutions/types/GetOperationalNeeds.ts
- src/views/ModelPlan/TaskList/ITSolutions/Home/operationalNeedsTable.test.tsx
- src/views/ModelPlan/TaskList/ITSolutions/util.test.tsx
- src/views/ModelPlan/TaskList/ITSolutions/util.tsx
- Updated `getOperationalNeeds` query and types according to @patrickseguraoddball's [slack message](https://cmsgov.slack.com/archives/C01B9TEC65A/p1667575951219359?thread_ts=1667575800.972299&cid=C01B9TEC65A)
1. Navigate to the operational needs from task list
2. make sure nothing is failing
> [NOREF] Fixing the getOpertionalNeeds query and types

- pkg/local/authentication_middleware.go
- pkg/okta/authentication_middleware.go
- Normalize EUAs to always be uppercase in backend principal objects.
Identical change to EASi in https://github.com/CMSgov/easi-app/pull/1825
> [NOREF] Uppercase EUA when making principal object

- .github/workflows/deploy_pipeline.yml
- Enabled IMPL deploys in GitHub actions
- Added `impl` environment in GitHub and secrets (screenshot below as proof)
We could modify the code so that we fire off the impl deploy on this branch, but frankly, the code isn't likely to change specifically for this environment, so we could just merge this and let the `main` deploy trigger run through as a test.
Any preferences on testing in `main` vs here? 🤔 
> [EASI-2498] Enable IMPL deploys in GitHub actions

- src/i18n/en-US/home.ts
- src/views/ModelPlan/Table/index.tsx
NOREF
- Updated verbiage for mac warnings
[Figma](https://www.figma.com/file/6tkIhfNfcsKEAkqXo1qvXH/MINT---Read-Only-View?node-id=2148%3A113641&t=r5ZmnRgtABuXcOZ4-0)
- Log in a MAC and don't seed the db to show no models warning
> MAC experience updates

- .github/workflows/deploy_pipeline.yml
- Added test environment to GitHub deploy pipeline
- Currently will deploy after `dev`, before `impl`.
- Created `test` environment in GitHub.
- Currently has no required reviews for deploys
Should be nearly identical (practically) to https://github.com/CMSgov/mint-app/pull/342/ but this is for the test env instead of the impl env.
- Review with your 👀, approve with your ❤️ 
- Actually, though - there's not a _ton_ to test here, as the changes are part of the pipeline that's executed when we merge to `main`. The main things to validate are that the correct secrets exist, and the job is being called correctly (right order, right params/secrets, etc.)
- Check that all code is adequately covered …
> [EASI-2497] Add test env to GitHub actions deploy pipeline

- src/views/ModelPlan/ModelPlanOverview/index.test.tsx
- src/views/ModelPlan/ModelPlanOverview/index.tsx
- src/views/ModelPlan/ReadOnly/Table/index.tsx
- src/views/ModelPlan/Table/index.tsx
NOREF
- Hide favorites and table column for MAC user
- Added scroll into view functionality for /models 'Jump to all models'
- Adjusted loading states for table and favorites
> [NOREF] - MAC Experience Updates - more

- src/utils/modelPlan.test.tsx
- src/utils/modelPlan.ts
NOREF
User initials in icons were not displaying correctly with extra spaces and characters, ex: "John Doe (He/They)"
- Updated user initial icon to include first valid letter character of each word separated by a space character
- Unit tests
> [NOREF] - User initial updates

- src/views/ModelPlan/ReadOnly/index.tsx
NOREF
- Hid ability to favorite for MAC users on readonly
Log in as MAC user and verify you cannot favorite from readonly
> [NROEF] - Hide readonly favorite for mac users

- .github/workflows/deploy_pipeline.yml
- .github/workflows/manual_deploy.yml
- Add secrets to parent workflows
> NOREF - Add contribsys secrets to deploy pipelines

- src/i18n/en-US/draftModelPlan/operationsEvaulationAndLearning.ts
- src/views/ModelPlan/TaskList/OpsEvalAndLearning/Performance/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/OpsEvalAndLearning/Performance/index.tsx
- Added info warning for page 2 of OpsEvalAndLearning per Figma
- Updated snapshot
Verifiy warning appears on page 2
> [EASI-2520] - Ops Eval and Learning Info warning and text

- src/views/ModelPlan/TaskList/ITSolutions/_components/Subtasks/index.tsx
NOREF
-A linting error got through to the pipeline to do a prop destructuring issue.  This PR addresses and fixes the error
> [NOREF] - Fixed subtasks prop destructuring

- pkg/storage/audit_changeStore.go
- pkg/worker/analyzed_audit_job.go
- pkg/worker/analyzed_audit_job_test.go
- pkg/worker/digest_cron_job.go
- pkg/worker/digest_email_job.go
- Modified date used in Analyze/Email jobs to reference the previous day, as the CRON job will run at 7:00am each day.
- `scripts/dev up:backend`
- `scripts/dev test:go`
> [NOREF] Update date variable for analyze/digest jobs

- pkg/models/analyzed_audit.go
> NOREF - fix typo in digest email

- .github/workflows/deploy_to_environment.yml
- Following guides here: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsif
> [NOREF] Fix 'if' statement to contain entire expression in brackets

- src/i18n/en-US/home.ts
- Update copy for empty state
1. Log in with only `MINT_USER_NONPROD` job code 
2. Verify that you do not have any model plans and the copy has been updated
|||
|---|---|
|Before| ![SCR-20230201-ftl](https://user-images.githubusercontent.com/2349702/216102593-e94942d5-d3e9-474d-b07c-4181318b4544.png)|
|After|![image](https://user-images.githubusercontent.com/2349702/216102748-21004e6f-f03c-4005-a19b-f4115a3ffa58.png)|
> [EASI-2635] Update copy for empty state

- src/constants/jobCodes.ts
- src/utils/user.ts
- src/views/ModelAccessWrapper/index.tsx
> [NOREF] Adding MINT_ASSESSMENT to the job codes file

- .github/workflows/manual_deploy.yml
- Fix `input` on manual deploy job.
- Attempt to run the manual deploy job targeting this branch
- This was done [here](https://github.com/CMSgov/mint-app/actions/runs/4127818289). Check the logs to see if this deploy was a success!
> [NOREF] Fix input on manual deploy

- pkg/graph/model/subscribers/task_list_section_lock_changed_subscriber.go
- pkg/graph/resolvers/plan_task_list_section_locks.go
- pkg/shared/pubsub/mockpubsub/subscriber.go
- pkg/shared/pubsub/servicepubsub.go
- pkg/shared/pubsub/subscriber.go
- src/index.tsx
- src/utils/general.ts
- src/views/App/index.tsx
- src/views/RouterContext/index.tsx
- src/views/SubscriptionHandler/index.tsx
- src/views/SubscriptionWrapper/index.tsx
- Combination of changes from [this PR](https://github.com/CMSgov/mint-app/pull/450) and [this branch](https://github.com/CMSgov/mint-app/tree/NOREF/test-subscription-locking-2)
> [NOREF] Task list locking debug

- src/views/ModelPlan/CRTDL/AddCRTDL/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/CRTDL/AddCRTDL/index.tsx
- Convert CRTDL title input to be textarea with expanded max char limit
> Converted CRTDL input to textarea

- src/views/ModelPlan/ReadOnly/GeneralCharacteristics/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/GeneralCharacteristics/index.tsx
- src/views/ModelPlan/ReadOnly/ModelBasics/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/ModelBasics/index.tsx
- src/views/ModelPlan/ReadOnly/OpsEvalAndLearning/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/OpsEvalAndLearning/index.tsx
- src/views/ModelPlan/TaskList/GeneralCharacteristics/KeyCharacteristics/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/GeneralCharacteristics/KeyCharacteristics/index.tsx
[UX changes doc](https://docs.google.com/document/d/1_-E1KX19ogZYtOqP7SY8jmhEbOOYey9MMwSbHK7Q_pg/edit#)
- Basics, GenChar, and OEaL sections have been updated
- These are the first three bullet points in the doc, everything below was prior changes that have been completed
Verify changes as of Issues as of 2/16 are complete
> [NOREF] - UX changes part 4

- src/types/flags.ts
- src/utils/user.test.ts
- src/views/FlagsWrapper/index.tsx
- src/views/HelpAndKnowledge/home.tsx
- src/views/HelpAndKnowledge/index.tsx
- src/views/ModelPlan/TaskList/ITSolutions/LinkDocuments/index.test.tsx
-  Added flag `operationalSolutionHelp`for operational solution help
- Fixed merge lint error
> [NOREF] - Added flag for operational solution help

- package.json
- src/index.tsx
- src/views/App/index.tsx
- yarn.lock
- Added `react-ga4` for Google Analytics 4 tracking
- Added SPA route tracking in `App.js`
Verify page events show in realtime in GA
> [NOREF] - Added react-ga4 for Google Analytics tracking

- src/views/ModelPlan/ReadOnly/GeneralCharacteristics/index.tsx
- Added query for existing MINT models to map to UUID in readonly for `resemblesExistingModelWhich`
- Added mapping util to combine data-backfill and MINT models
Verify both data-backfilled models and MINT models render names correctly in readonly
> [NOREF] - Added existing MINT model mapping to resemblesWhich in readonly

- .github/workflows/deploy_to_environment.yml
- scripts/invalidate_cloudfront_cache.sh
- Created script to clear CloudFront cache
- Updated deploy_to_environment file
> Easi 2702/clear cloudfront cache

- scripts/invalidate_cloudfront_cache.sh
Clear CloudFront cache
Added script for fail on any error
> added line for fail on any error

- pkg/graph/generated/generated.go
- pkg/graph/schema.graphql
- src/views/UserInfoWrapper/index.tsx
- Don't query for NDA info if unauthenticated (you'll always get an error if you do!)
- Start the app locally
- Go to the home page (before logging in)
- Open the developer console
- Refresh the page
- Make sure there's no request to fetch NDA info
> [NOREF] Skip NDA query if not logged in

- cypress/e2e/itSolutions.js
> [NOREF] Cypress debug for flaky test

- Dockerfile
- cypress/e2e/itSolutions.js
- Copy directory instead of file for `/etc/ssl/certs`
> [NOREF] Add trailing slash to ensure directory is copied instead of a file

- .github/workflows/run_tests.yml
- Dockerfile
> [NOREF] Added tzdata to scratch image

- src/i18n/en-US/helpAndKnowledge/helpAndKnowledge.ts
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Modal/index.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/4Innovation/index.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/CMSQualtrics/index.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/CentralizedDataExchange/index.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/Generic/about.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/Generic/pointsOfContact.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/SalesforceApplicationReview/index.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/index.scss
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/_components/Contact/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/_components/Contact/index.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/_components/Header/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/_components/Header/index.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/_components/CategoryFooter/index.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/_components/SolutionCategories/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/SolutionsHelp/_components/SolutionCategories/index.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/_components/SolutionHelpCard/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/SolutionsHelp/_components/SolutionHelpCard/index.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/_components/SolutionHelpCardGroup/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/SolutionsHelp/_components/SolutionHelpCardGroup/index.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/_components/SolutionsHeader/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/SolutionsHelp/_components/SolutionsHeader/index.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/_components/SolutionsTag/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/SolutionsHelp/_components/SolutionsTag/index.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/index.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/solutionsMap.tsx
- src/views/HelpAndKnowledge/home.tsx
- src/views/ModelPlan/ReadOnly/_components/MobileNav/index.scss
- Address all the points listed in Natasha's review of the solution help center
Go through Help Center and Operational Solutions to check the points listed in Natasha's review is addressed.
> [EASI-2735] Help Center Operational Solution Review Updates

- docs/adr/0011-capturing-deleted-actor.md
- docs/adr/template.md
- src/hooks/useCacheQuery.ts
- Created an [ADR](https://github.com/CMSgov/mint-app/blob/EASI-2783/deleted_actor_adr/docs/adr/0011-capturing-deleted-actor.md) for how to capture the deleted actor.
- made a [POC test branch](https://github.com/CMSgov/mint-app/tree/EASI-2783/capturing_deleted_actors_spike)
- unit tests to verify the actor
1. Look at the ADR
2. Look at the changes in the POC branch
> ADR for capturing the deleted actor

- src/views/HelpAndKnowledge/SolutionsHelp/solutionsMap.tsx
- Updated solution help info per Figma
> [EASI-2796] Updated solution help info

- src/views/HelpAndKnowledge/SolutionsHelp/index.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/solutionsMap.tsx
- Fixed type and category search
> [NOREF] - Fixed type and category search

- src/types/flags.ts
- src/utils/user.test.ts
- src/views/FlagsWrapper/index.tsx
- src/views/HelpAndKnowledge/home.tsx
- src/views/HelpAndKnowledge/index.tsx
- Remove feature flag for Help Center Solutions now that flag is switched
> [EASI-2718] - Remove feature flag for Help Center Solutions

- src/views/ModelAccessWrapper/index.tsx
-  Added condition to skip collab access check if viewing sample help article
> [EASI-2798] - Added condition to skip collab access check if viewing sample help article

- cypress/e2e/login.spec.js
- src/i18n/en-US/general.ts
- src/i18n/en-US/home.ts
- Spell out Model Innovation Tool in MINT header (only)
> [EASI-2766] Spell out Model Innovation Tool in MINT header

- .github/workflows/build_application_images.yml
- .github/workflows/deploy_pipeline.yml
- .github/workflows/deploy_to_environment.yml
- .github/workflows/manual_deploy.yml
- .github/workflows/pr_checks.yml
- .github/workflows/run_tests.yml
- update the workflow files on this PR to simplify using secrets with reusable workflows
- doc: https://github.blog/changelog/2022-05-03-github-actions-simplify-using-secrets-with-reusable-workflows/
> Easi 2835/refactor gh secrets

- src/hooks/useModalSolutionState.ts
- src/queries/ITSolutions/GetOperationalNeeds.ts
- src/queries/ITSolutions/types/GetOperationalNeeds.ts
- src/views/App/index.tsx
- src/views/App/scrollConfig.ts
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Modal/index.test.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Modal/index.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/_components/Contact/index.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/index.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/solutionsMap.tsx
- src/views/ModelPlan/TaskList/ITSolutions/Home/operationalNeedsTable.test.tsx
- src/views/ModelPlan/TaskList/ITSolutions/Home/operationalNeedsTable.tsx
- src/views/ModelPlan/TaskList/ITSolutions/SelectSolutions/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/ITSolutions/SelectSolutions/index.test.tsx
- src/views/ModelPlan/TaskList/ITSolutions/SelectSolutions/index.tsx
- src/views/ModelPlan/TaskList/ITSolutions/SolutionImplementation/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/ITSolutions/SolutionImplementation/index.tsx
- src/views/ModelPlan/TaskList/ITSolutions/_components/CheckboxCard/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/ITSolutions/_components/CheckboxCard/index.tsx
- src/views/ModelPlan/TaskList/ITSolutions/_components/NeedQuestionAndAnswer/index.test.tsx
- src/views/ModelPlan/TaskList/ITSolutions/_components/SolutionCard/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/ITSolutions/_components/SolutionCard/index.test.tsx
- src/views/ModelPlan/TaskList/ITSolutions/_components/SolutionCard/index.tsx
- src/views/ModelPlan/TaskList/ITSolutions/_components/SolutionDetailCard/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/ITSolutions/_components/SolutionDetailCard/index.tsx
- src/views/ModelPlan/TaskList/ITSolutions/index.tsx
- src/views/ModelPlan/TaskList/ITSolutions/util.tsx
- Implemented solution detail modal for IT tracker
- Added description and PoC to solution cards
- Added subtask count to op needs table
> [EASI-2896] Map solution details/modal

- cypress/e2e/itSolutions.spec.js
- src/utils/globalFilterCellText.ts
- src/views/ModelPlan/TaskList/ITSolutions/AddCustomSolution/index.tsx
- src/views/ModelPlan/TaskList/ITSolutions/AddOrUpdateOperationalNeed/index.tsx
- src/views/ModelPlan/TaskList/ITSolutions/AddSolution/index.test.tsx
- src/views/ModelPlan/TaskList/ITSolutions/AddSolution/index.tsx
- src/views/ModelPlan/TaskList/ITSolutions/Home/operationalNeedsTable.tsx
- src/views/ModelPlan/TaskList/ITSolutions/SelectSolutions/index.test.tsx
- src/views/ModelPlan/TaskList/ITSolutions/SelectSolutions/index.tsx
- src/views/ModelPlan/TaskList/ITSolutions/SolutionImplementation/index.test.tsx
- src/views/ModelPlan/TaskList/ITSolutions/SolutionImplementation/index.tsx
- Added condition to only create a solution from a possible solution if `needed` = `true`
- Added loading state/render to solution selections
- Added conditional check for null on search query
- Replaced location state with query strings
- Tweaked cypress tests for consistency
Select solutions and verify only solutions that are needed or have already been created are updated by mutations
> [EASI-2601, EASI-2898] - Only create solution if needed, use query param instead of location state

- src/views/ModelPlan/TaskList/ITSolutions/AddCustomSolution/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/ITSolutions/AddCustomSolution/index.test.tsx
- src/views/ModelPlan/TaskList/ITSolutions/AddCustomSolution/index.tsx
- src/views/ModelPlan/TaskList/ITSolutions/AddSolution/index.tsx
- src/views/ModelPlan/TaskList/ITSolutions/LinkDocuments/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/ITSolutions/SelectSolutions/index.tsx
- src/views/ModelPlan/TaskList/ITSolutions/Subtasks/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/ITSolutions/_components/CheckboxCard/index.tsx
- src/views/ModelPlan/TaskList/ITSolutions/_components/SolutionCard/index.tsx
Data being passed from location state was already being fetched by apollo query, and was unnecessary.  This also aligns with the paradigm of moving away from passing state through router in favor of query params
- Removed location state in favor of query param
- Removed unneeded #remove-details - previously gutted feature
- Fixed incorrect breadcrumb
Verify updating custom solutions, renders the current solution details
> [NOREF] - Replaced location state with query param

- src/components/shared/OktaSignInWidget/index.tsx
- src/i18n/en-US/general.ts
- src/views/Login/index.tsx
- add error message to `general.ts` translation file
- Add alert in `login.tsx`
- pass `setError` down into oktawidget
1. Login with out the correct job codes
2. See error message show up
> [EASI-2628] Okta Error message for incorrect job code

- docs/temporal_tables.md
- [POC branch](https://github.com/CMSgov/mint-app/tree/EASI-2900/temporal_tables_poc).
- A write up of temporal table research [here](https://github.com/CMSgov/mint-app/blob/EASI-2900/temporal_tables_documentation/docs/temporal_tables.md)
> Easi 2900/temporal tables documentation

- cmd/dbseed/main.go
- pkg/authorization/require_principal_middleware.go
- pkg/authorization/require_principal_middleware_test.go
- pkg/graph/resolvers/resolver_test_utilities.go
- pkg/graph/schema.resolvers_test.go
- pkg/handlers/handler_base.go
- pkg/handlers/handlers_test.go
- pkg/integration/integration_test.go
- pkg/local/authentication_middleware.go
- pkg/okta/authentication_middleware_test.go
- pkg/server/logger.go
- pkg/server/logger_test.go
- pkg/server/routes.go
- pkg/server/server.go
- pkg/server/trace.go
- pkg/server/trace_test.go
- pkg/services/services_test.go
- pkg/storage/store.go
- pkg/storage/store_test.go
- pkg/worker/worker_test_utilities.go
See https://github.com/CMSgov/easi-app/pull/2030 for reference
- Added `app-env` and `app-name` log fields. These should be present on all logs!
- Start the server and ensure that logger fields are present
> [NOREF] Add splunk log fields and fix log references

- pkg/okta/authentication_middleware.go
> [NOREF] Adding debug logging for Okta websocket auth that fails occasionally

- pkg/okta/authentication_middleware.go
- pkg/server/logger.go
- Handle JWT creation errors more gracefully.
- Testing this locally is tough - best bet for testing locally is to force returning an error in this function and see if the UI breaks in any way that's unhandled!
> [NOREF] Handle JWT creation erorrs more gracefully in

- src/components/ITSolutionsWarning/__snapshots__/index.test.tsx.snap
- src/components/shared/Alert/__snapshots__/index.test.tsx.snap
- src/components/shared/Alert/index.tsx
- src/views/ModelPlan/Collaborators/AddCollaborator/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/Collaborators/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/Documents/AddDocument/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/NewPlan/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/Basics/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/GeneralCharacteristics/KeyCharacteristics/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/GeneralCharacteristics/TargetsAndOptions/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/OpsEvalAndLearning/CCWAndQuality/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/OpsEvalAndLearning/IDDOCTesting/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/OpsEvalAndLearning/Learning/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/OpsEvalAndLearning/Performance/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/ParticipantsAndProviders/Coordination/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/Payment/AnticipateDependencies/__snapshots__/index.test.tsx.snap
- src/views/NDA/__snapshots__/index.test.tsx.snap
- Changed nested `div` element in `Alert` component to `span`
- Updated lots of snaps
Warning were indicating this non standard practice of element nesting
> [NOREF] - Nested div in p element warning fix

- src/queries/GetAllModelData.ts
- src/queries/GetAllSingleModelPlan.ts
- src/queries/types/GetAllModelData.ts
- src/queries/types/GetAllSingleModelData.ts
- src/utils/export/CsvData.ts
- Reordered csv data to match task list
- Added previous name, abbreviation, amsModelD and demoCode
Download a csv and confirm order of task list sections and questions match task list
> [EASI-2679] - Reordered csv data to match task list

- src/views/HelpAndKnowledge/Articles/GetAccess/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/Articles/GetAccess/index.tsx
- src/views/Landing/index.scss
- src/views/Landing/index.tsx
- Fixed styling on landing
- Fixed get access text bullet
> [NOREF] - Fixed styling on landing and get access text

- src/i18n/en-US/helpAndKnowledge/helpAndKnowledge.ts
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/BCDA/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/BCDA/index.test.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/BCDA/index.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/_components/SolutionHelpCardGroup/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/SolutionsHelp/_components/SolutionsHeader/index.test.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/solutionsMap.tsx
- Added translation and mapping for a newBCDA component
- Left out the new category as that will be implemented as a part of [EASI-2987](https://jiraent.cms.gov/browse/EASI-2987)
Verify help component matches figma
> [EASI-2978] New solution - BCDA [FE]

- src/components/shared/Alert/index.scss
- src/components/shared/Alert/index.tsx
- src/i18n/en-US/helpAndKnowledge/helpAndKnowledge.ts
- src/stylesheets/custom.scss
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/About/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/About/index.test.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Modal/index.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/PointsOfContact/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/PointsOfContact/index.test.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/Generic/about.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Timeline/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Timeline/index.test.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/solutionsMap.tsx
- Added updates to solution details per Figma for CCW, ARS, CONNECT, POST, and RFA
- Added snapshots for all About, Timeline, and PointsOfContact. solution components
- Added IT lead info alert to all solution side panels
- Some solutions had external links to google drive that open in a new tab to display image
Verify all changes match Figma
> [EASI-3013] - Salesforce solution updates

- pkg/graph/generated/generated.go
- pkg/graph/schema.graphql
- pkg/storage/plan_discussionStore.go
- src/queries/Discussions/types/GetMostRecentRoleSelection.ts
- Silently handle the 'error' when no role selection exists and to return null for the selection in that case
> [NOREF] Wrap Role Selection Error

- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/About/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/PointsOfContact/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Timeline/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/OpsEvalAndLearning/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/OpsEvalAndLearning/index.tsx
- src/views/ModelPlan/ReadOnly/Payments/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/Payments/index.tsx
- Change the way the conditional is rendering to ensure it only shows when the questions are answered
1. Check read only Operations, evaluation, and learning section and ensure it is not showing any CCW questions 
2. Go to the Operations, evaluation, and learning questions and select yes
3. Go back to read only and check that the CCW questions are now showing up
4. Do the same with payment's claims based payment, non claim based payment, and beneficiary cost sharing
5. 
> [EASI-3084] Bug fixes for the conditional questions 

- src/views/HelpAndKnowledge/SolutionsHelp/_components/SolutionCategories/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/SolutionsHelp/_components/SolutionCategories/index.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/_components/SolutionsHeader/index.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/index.tsx
There was some unwanted scrolling behavior when changing help center pages.  Ideally the window would scroll to the top when a page changes.  This work addresses this functionality
- Now page scrolls to top when changing page
> [NOREF] - Adjust help center scrolling functionality

- migrations/V101__Add_foreign_keys_to_possible_need_solution_link.sql
- Created flyway migreation adding fk constraints to possible need solution link table
- Run `scripts/dev down && scripts/dev up:backend && scripts/dev db:seed`
- Verify that FK constraints have been added to the `possible_need_solution_link` table
> [EASI-3074] Add foreign key constraints to the need solution link table

- src/i18n/en-US/helpAndKnowledge/helpAndKnowledge.ts
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/About/__snapshots__/index.test.tsx.snap
- Updated help center link for second video sample on ISP solution
- Updated snap
Go to help center solution - ISP and click the last video link to verify it opens a video in CMS box
> [NOREF] - Updated help center link and snap

- src/views/ModelPlan/ReadOnly/Beneficiaries/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/Beneficiaries/index.tsx
- src/views/ModelPlan/ReadOnly/GeneralCharacteristics/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/GeneralCharacteristics/index.tsx
- src/views/ModelPlan/ReadOnly/ModelBasics/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/ModelBasics/index.tsx
- src/views/ModelPlan/ReadOnly/OpsEvalAndLearning/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/OpsEvalAndLearning/index.tsx
- src/views/ModelPlan/ReadOnly/ParticipantsAndProviders/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/ParticipantsAndProviders/index.tsx
- src/views/ModelPlan/ReadOnly/Payments/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/Payments/index.tsx
- src/views/ModelPlan/ReadOnly/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/_components/TitleAndStatus/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/_components/TitleAndStatus/index.test.tsx
- src/views/ModelPlan/ReadOnly/_components/TitleAndStatus/index.tsx
- src/views/ModelPlan/TaskList/_components/TaskListItem/index.tsx
|Before|After|
|-------|-----|
|![image](https://github.com/CMSgov/mint-app/assets/2349702/ebf984f1-8cd1-410b-a7e4-4a1051b9eeed)|![image](https://github.com/CMSgov/mint-app/assets/2349702/6b804f6b-af3c-4b38-9215-fdf85a4060e0)|
|![image](https://github.com/CMSgov/mint-app/assets/2349702/6be15c77-c9f5-41cb-94b8-977285f2d4ce)|![image](https://github.com/CMSgov/mint-app/assets/2349702/54c78a8f-92ea-42a1-9228-241fb4ce0179)|
1. Go to `Enhancing Oncology Model` model plan and set `Participants and Providers` and `Operations, evaluation, and learning` tasks to be `ready for clearance`
2. Go to Read only pages and verify the status tag is not weird
- Check that all code is adequately covered by tests - …
> [EASI-2894] fix text wrapping

- src/views/ModelPlan/TaskList/index.tsx
- Add a new function to pull the latest modified date for the IT Solutions
1. modify somethign in the IT Solutions task 
2. Ensure the latest modified date is showing on the task list
> [EASI-3071] add latest modified date to IT Solutions in Task List

- src/i18n/en-US/helpAndKnowledge/helpAndKnowledge.ts
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/About/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/PointsOfContact/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/SolutionsHelp/solutionsMap.tsx
[Figma](https://www.figma.com/file/dzzLdDf6UwkLA51BtoAt3T/MINT---Knowledge-Center?node-id=874%3A69947&mode=dev)
- Updated saleforceLOI help text
Verify with Figma
> [EASI-3116] - Updated saleforceLOI help text

- src/views/ModelPlan/ReadOnly/GeneralCharacteristics/index.tsx
- src/views/ModelPlan/ReadOnly/ModelBasics/index.tsx
- src/views/ModelPlan/ReadOnly/_components/FilterView/util.tsx
- [add new util function to check if filtered group has any questoisn](https://github.com/CMSgov/mint-app/commit/4581ccefab1875ca8538073f5d8882068a72b1f0)
- [move note out of the side by side section](https://github.com/CMSgov/mint-app/commit/c4f140185e9c6e1b43962ec072004c2c4b07785c)
1. Fill out a high level timeline note and ensure it is not showing up for `MDM` and `OACT` filtered views
2. Fill out geography note in general characteristics and ensure it is left aligned and stretches across the full span
- Always make comments, even if it's minor, or if you don't understand why …
> [NOREF] Fast follow for Group filter ux fixes

- src/components/ShareExport/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/ParticipantsAndProviders/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/Beneficiaries/Frequency/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/ParticipantsAndProviders/ProviderOptions/__snapshots__/index.test.tsx.snap
- Updated snapshots for the semiannually changes
Run `test:js`
> [NOREF] - Updated semiannually snapshots

- src/i18n/en-US/helpAndKnowledge/Articles/getAccess.ts
- src/views/HelpAndKnowledge/Articles/GetAccess/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/Articles/GetAccess/index.tsx
- Removed Summarybox and copy in it
- Add table and its copy
1. go to http://localhost:3005/how-to-get-access
2. ensure changes are there
> [EASI-3132] MINT Access Page: MAC Access Text Change

- src/i18n/en-US/helpAndKnowledge/Articles/getAccess.ts
- src/views/HelpAndKnowledge/Articles/GetAccess/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/Articles/GetAccess/index.tsx
https://oddball.slack.com/archives/C059QQA3HK5/p1692293277600869?thread_ts=1692279464.010489&cid=C059QQA3HK5
- Change 1
- Change 2
> [NOREF] Updating a couple more steps in the Get Access

- pkg/email/templates/model_plan_date_changed_body.html
- Email template link updated to readonly view rather than task list
- Change model plan date
- Check resulting email link
- Assert resulting email links to readonly view
> [NOREF] Fix model plan date change email to link to the readonly view

- src/i18n/en-US/helpAndKnowledge/helpAndKnowledge.ts
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/PointsOfContact/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/ChronicConditions/index.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Timeline/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/_components/Contact/index.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/_components/SolutionHelpCardGroup/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/SolutionsHelp/solutionsMap.tsx
- Text updates to CCW, GovDelivery, IPC, MDM, MIDS, and QV panels
1. Go to each panel and verify that it matches the figma
> [EASI-2834] Text updates to CCW, GovDelivery, IPC, MDM, MIDS, and QV panels

- src/components/ShareExport/__snapshots__/index.test.tsx.snap
- src/components/ShareExport/index.tsx
- src/views/ModelPlan/ReadOnly/__snapshots__/index.test.tsx.snap
- Fixed incorrect share email text
> [NOREF] - Fixed incorrect share email text

- pkg/email/templates/model_plan_share_body.html
- Moved link from below table into table
- Added info box with link to support article below table
- Modified table width style so they match and support text overflow in cells
> [NOREF] Updated share model plan email to make changes closer to spec

- .github/dependabot.yml
- Added `npm` to Dependabot config at the same interval/limit as the other ecosystems.
- https://github.com/CMSgov/easi-app/pull/2177
- There's nothing really to test here, other than that the dependabot config itself is valid, which is called out in the checks for this PR!
> [NOREF] Add npm to dependabot

- .github/workflows/manual_deploy.yml
- .github/workflows/run_tests.yml
- Introduce skip_tests option for manual deployment
> EASI-3236: skip_tests feature for manual deployment

- scripts/rds-snapshot-app-db.sh
- Delete manual RDS snapshots before making new ones to ensure we don't hit the 100 limit in each account.
> [NOREF] Delete RDS manual snapshots 

- cmd/test_email/main.go
- pkg/email/templates/report_a_problem_body.html
- pkg/email/templates/send_feedback_body.html
- pkg/graph/resolvers/send_feedback_email.go
- src/components/Footer/index.tsx
- src/stylesheets/custom.scss
- src/views/Feedback/ReportAProblem/__snapshots__/index.test.tsx.snap
- src/views/Feedback/ReportAProblem/index.tsx
- src/views/Feedback/SendFeedback/__snapshots__/index.test.tsx.snap
- src/views/Feedback/SendFeedback/index.tsx
[UX Findings](https://docs.google.com/document/d/15dc1Usl1EdvT2oAf8dlnpFYIF54aZNZILnjdiUV8dBg/edit)
- FE changes per UX findings 
- BE/Email changes per UX findings 
Verify all findings are addressed
> [NOREF]  - Feedback form UX findings

- .github/workflows/pr_label_checks.yml
> [NOREF] Check to see if blocked label is on PR

- .github/workflows/pr_label_checks.yml
- add 'opened' PR activity type for PR Label Checks workflow
> add 'opened' PR activity type

- src/i18n/en-US/helpAndKnowledge/Articles/utilizingSolutions.ts
- src/i18n/en-US/index.ts
- src/views/HelpAndKnowledge/Articles/AllArticles/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/Articles/UtilizingSolutions/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/Articles/UtilizingSolutions/index.test.tsx
- src/views/HelpAndKnowledge/Articles/UtilizingSolutions/index.tsx
- src/views/HelpAndKnowledge/Articles/_components/ArticlePageInfo/index.tsx
- src/views/HelpAndKnowledge/Articles/_components/RelatedArticles/index.tsx
- src/views/HelpAndKnowledge/Articles/index.ts
- src/views/HelpAndKnowledge/index.tsx
- Added content for Utilizing available operational solutions
- Updated props for `<RelatedArticles />` to show related tagged articles if more than one is present
- Added snapshot
- Verify article matches Figma
> [EASI-3329] - Utilizing available operational solutions article

- .github/workflows/pr_label_checks.yml
- Add on synchronize and ready_for_review
> Add on synchronize and ready_for_review

- src/i18n/en-US/draftModelPlan/discussions.ts
- src/views/ModelPlan/Discussions/QuestionAndReply.tsx
- src/views/ModelPlan/Discussions/index.test.tsx
A translation for discussion tagging made its way into the codebase (possibly from a Figma design that had discussion tagging included in the design)
- Removed unneeded translation and test
Verify help text for tagging is no longer present in the discussion center
> [NOREF] - Removed unneeded translation and test

- src/views/ModelPlan/ReadOnly/index.tsx
- Fixed the modal text for filtergroup not rendering
https://oddball.slack.com/archives/C059QQA3HK5/p1696881246408809
> [NOREF] - Updated filter view modal text

- src/views/ModelPlan/Discussions/index.tsx
- Fixed incorrect access on discussion center for basic users
Log in a basic user and navigate to readonly
Verify you can start a discussion/link is visible and active
> [EASI-3487] - Fixed edit access for discussions

- src/views/ModelPlan/ReadOnly/GeneralCharacteristics/index.tsx
- Fixed null render values for readonly
> [EASI-3509] - Fixed null render on readonly

- src/views/ModelPlan/Table/index.tsx
- Added demo code to home and models tables
> [EASI-3491] - Added demo code to home and models tables

- src/components/OktaUserSelect/multiSelect.tsx
- src/components/ShareExport/index.scss
- Added scroll to modal
- Fixed incorrect cms address
> [EASI-3538] - Added scroll to modal, fixed incorrect cms address

- src/views/ModelPlan/TaskList/GeneralCharacteristics/Authority/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/GeneralCharacteristics/Authority/index.tsx
- Fixed label rendering incorrectly
Verify matches Figma/addressed screenshot in ticket
> [EASI-3550] - Fixed label render

- src/components/ShareExport/__snapshots__/index.test.tsx.snap
- src/i18n/en-US/modelPlan/participantsAndProviders.ts
- src/views/ModelPlan/ReadOnly/ParticipantsAndProviders/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/ParticipantsAndProviders/Communication/__snapshots__/index.test.tsx.snap
- Addressing https://cmsgov.slack.com/archives/C04B10ZN6A2/p1699363456892159
- Updating copy in Participants and Providers page
|  |  |
|--|--|
|Before|<img width="451" alt="image" src="https://github.com/CMSgov/mint-app/assets/2349702/2ca701d4-8aca-4373-998a-67534a8906ab">|
|After|<img width="500" alt="image" src="https://github.com/CMSgov/mint-app/assets/2349702/9159aef4-d0a6-4082-9d5c-2ea208f7916e">|
1. to go a plan's `Participants and Providers` page
2. verfiy the change
> [NOREF] Capitation, not Capitalization

- src/components/shared/MentionTextArea/suggestion.ts
- Add config to allow spaces in mention config
Verify the suggestion popup remains after trigger (@) and adding a space between characters
> [NOREF] - Add config to allow spaces in mention config

- src/components/ShareExport/__snapshots__/index.test.tsx.snap
- src/i18n/en-US/modelPlan/generalCharacteristics.ts
- src/views/ModelPlan/ReadOnly/GeneralCharacteristics/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/GeneralCharacteristics/Authority/__snapshots__/index.test.tsx.snap
- Update "3021 (ACA)" to "3021 Affordable Care Act (ACA)"
1. Go to General Characteristics section and find the question `What authority allows CMMI to test the model?`
2. Find the updated copy
> [EASI-3570] Update "3021 (ACA)" to "3021 Affordable Care Act (ACA)"

- src/views/ModelPlan/TaskList/ParticipantsAndProviders/Communication/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/ParticipantsAndProviders/Communication/index.tsx
- Fixed incorrect page on Participants and Providers - Communication
- Fixed from page 4 to page 3
- Updated snapshot
- Navigate to page 3 (Communication) of Participants and Providers and verify it is set to page 3
> [EASI-3692] - Updated Participants and Providers - Communication page number

- src/components/ShareExport/__snapshots__/index.test.tsx.snap
- src/i18n/en-US/modelPlan/beneficiaries.ts
- src/views/ModelPlan/ReadOnly/Beneficiaries/__snapshots__/index.test.tsx.snap
- Updated text option
- Medicare Part D << rename to Prescription Drug (Medicare Part D)
- Fixed disease-specific sub-label
- Create a model plan
- Navigate to page one of beneficiaries in the task list
- Verify text and fix matches [Figma](https://www.figma.com/file/M72DReE73SSXMN48WZfaKN/MINT---New-Model-Process-(Model-Intake)?type=design&node-id=7055-37580&mode=design&t=qFBUXAtoZBY7f8uA-0)
> [EASI-3665] - Update who are the beneficiaries? options v2

- src/data/operationalNeedMap.ts
There were two incorrect translation mappings within the possible solutions table
-  Fixes incorre
- Navigate to the IT Track and verify that `Establish a benchmark with participants` and `Participant-to-participant collaboration` have correct mappings
> [NOREF] - Fixes incorrect translation mapping for possible needs table

- src/components/ShareExport/__snapshots__/index.test.tsx.snap
- src/i18n/en-US/modelPlan/beneficiaries.ts
- src/views/ModelPlan/ReadOnly/Beneficiaries/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/Beneficiaries/Frequency/__snapshots__/index.test.tsx.snap
- update chosen to added
- update snaps
1. Navigate to page 3 of Beneficiaries
2. See question has been updated from `How frequently are beneficiaries chosen?` to `How frequently are beneficiaries added?`
3. Check copy is changed in Read Only view too. 
> [EASI-3686] Update beneficiary question language

- src/components/shared/IconInitial/index.tsx
- src/hooks/useFetchCSVData.tsx
- src/i18n/en-US/modelPlan/collaborators.ts
- src/types/translation.ts
- src/utils/export/CsvData.ts
- src/views/ModelPlan/Collaborators/AddCollaborator/index.tsx
- src/views/ModelPlan/Collaborators/table.tsx
- src/views/ModelPlan/ReadOnly/Team/index.tsx
Collaborator roles were not rendering in CSV export.
RTE html tags were being rendered in CSV export.
- Added ability to correctly/dynamically render collaborator team role enums
- Added RTE html tag parser to remove tags from csv export
Verify discussion content renders without html tags
Verify collaborator roles are rendered and translated correctly in csv export
> [NOREF] - Fix CSV TeamRole translation and RTE parsing

- src/i18n/en-US/helpAndKnowledge/Articles/getAccess.ts
- src/views/HelpAndKnowledge/Articles/GetAccess/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/Articles/GetAccess/index.tsx
- Updated `How to get access to MINT` article text to support new job code
- Update snapshot
Verify the article (opened from the landing page) matches changes in [Figma](https://www.figma.com/file/aD3DZLft8HZXqJjWCIT3i2/MINT-Branding-%26-Marketing?node-id=1050%3A857&mode=dev)
> [EASI-3544] - Updated job code access help text

- migrations/V127__Update_Quality_Performance_Impacts_Payment.sql
- Reverted migration 127 to 4454a5a0f0957a0ddf10a284772c8bc38fd2034c
Use the diff tool of your choice to compare the contents of this file against the unmodified version
> [NOREF] Revert migration V127 whitespace changes

- migrations/V127__Update_Quality_Performance_Impacts_Payment.sql
- Reverted migration 127 to 4454a5a0f0957a0ddf10a284772c8bc38fd2034c
Use the diff tool of your choice to compare the contents of this file against the unmodified version
> [NOREF] Revert migration 127 to 4454a5a

- migrations/V138__IPC_Updates.sql
- Remove Sue Nonemaker and Phil Tennant from IPC POC
- Add Alistair Quatre and Brandon Cooper as SME to IPC POC
- Run migrations
- Check that the values in the database are appropriate for IPC possible solutions
> [EASI-3845] IPC Updates

- src/i18n/en-US/modelPlan/payments.ts
- src/views/ModelPlan/TaskList/Payment/ClaimsBasedPayment/__snapshots__/index.test.tsx.snap
- Updated label
1. Go to Payments in task list
2. Add a `Claims-Based Payments` to the last question in page 1
3. Select `Other` to the first question `Select which claims-based payments will you pay.`
4. Make sure the copy is matches ticket
|Before|After|
|---|---|
|![image](https://github.com/CMSgov/mint-app/assets/2349702/a0666d08-27d0-4e54-a489-6e93ac4b573a)|![image](https://github.com/CMSgov/mint-app/assets/2349702/0efce7b8-f10e-44ba-8e8a-33696617cf74)|
> [EASI-3916] Update Claims Based Payment text

- public/manifest.json
- I updated the manifest so it correctly reflects the applications name
1. Bring up the app.
2. Hover over the link to download the app as a PWA
3. Ensure the app now reflects the correct application name
> NOREF - Update Manifest

- .spelling
- docs/adr/0015-notification-archetecture.md
- ADR created for general approach
- POC Branch is created as a general proof of concept. Further refinement is needed, and will continue during implementation.
- [EASI-3294/notifications_poc](https://github.com/CMSgov/mint-app/tree/EASI-3294/notifications_poc)
> feat: notification archetecture ADR

- src/components/ShareExport/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/OpsEvalAndLearning/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/OpsEvalAndLearning/index.tsx
https://oddball.slack.com/archives/C059QQA3HK5/p1707232870029319
- Fixed dupe question
- Replaced with Note that was supposed to render there
- Updated snapshot
Verify that the issue noted in the slack thread is corrected
> [NOREF] Fixed dupe question in readonly

- .github/PULL_REQUEST_TEMPLATE.md
- .spelling
- CONTRIBUTING.md
- README.md
- Added docs on standards for contribution around naming PRs and branches
- Read, read with your special eyes!
> [NOREF] Add docs on branch and PR naming

- src/components/NDABanner/index.tsx
- src/components/ShareExport/__snapshots__/index.test.tsx.snap
- src/components/shared/CollapsableLink/index.tsx
- src/hooks/useFetchCSVData.test.tsx
- src/hooks/useFetchCSVData.tsx
- src/i18n/en-US/modelPlan/basics.ts
- src/i18n/en-US/modelPlan/beneficiaries.ts
- src/i18n/en-US/modelPlan/generalCharacteristics.ts
- src/i18n/en-US/modelPlan/modelPlan.ts
- src/i18n/en-US/modelPlan/opsEvalAndLearning.ts
- src/i18n/en-US/modelPlan/participantsAndProviders.ts
- src/i18n/en-US/modelPlan/payments.ts
- src/i18n/en-US/readOnly/generalReadOnly.ts
- src/types/translation.ts
- src/views/ModelPlan/ReadOnly/ParticipantsAndProviders/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/ParticipantsAndProviders/index.tsx
- src/views/ModelPlan/ReadOnly/_components/Body/index.tsx
- src/views/ModelPlan/ReadOnly/_components/FilterView/BodyContent/_filterGroupMapping.ts
- src/views/ModelPlan/ReadOnly/_components/ModelSummary/index.tsx
- src/views/ModelPlan/ReadOnly/_components/ReadOnlySection/index.tsx
- src/views/ModelPlan/ReadOnly/_components/ReadOnlySection/new.test.tsx
- src/views/ModelPlan/ReadOnly/_components/ReadOnlySection/new.tsx
- src/views/ModelPlan/ReadOnly/_components/SideBySideReadOnlySection/new.tsx
- src/views/ModelPlan/ReadOnly/index.scss
- src/views/ModelPlan/TaskList/ParticipantsAndProviders/ParticipantOptions/index.tsx
[Figma](https://www.figma.com/file/6tkIhfNfcsKEAkqXo1qvXH/MINT---Read-Only-View?type=design&mode=design&t=L5WS6W9bX4vaRidL-0)
- Created translation type for supporting parent <-> child relationships
- Extended translation type to support better dynamic rendering in readonly
- Implemented `participantsAndProviders` conditional mappings
- Added Alert toggle banner (per Figma) for showing not needed questions in readonly
- Created 3 new components to make readonly fully automated - `ReadOnlySectionNew`, `SideBySideReadOnlySectionNew`, and `ReadOnlyBody`
- `New` can be deprecated/cutover once all readonly sections are complete
- Added CSV support to conditionally render fields
- Adjusted `CollapseableLink` component to have better styling flexibility
- Added unit tests
- Verify new …
> [task: EASI-3923] Create base support for conditional relationships

- src/views/ModelPlan/Documents/AddDocument/documentUpload.tsx
- Added missing model name to document upload success
Verify document upload model name is rendered in success
> [NOREF] - Added model name to success message for document add

- src/types/flags.ts
- src/utils/user.test.ts
- src/views/FlagsWrapper/index.tsx
- Added `notificationsEnabled` LD flag in preparation for Notification Center work
Verify that the flag is set to true in dev within the client (defaults to false in dev if can't connect to LD)
Check the LD settings that IMPL and PROD have different defaults (defaults to false, but allows targeting)
> [NOREF] Added `notificationsEnabled` LD flag

- src/views/Feedback/ReportAProblem/index.test.tsx
- src/views/Feedback/SendFeedback/index.test.tsx
- src/views/ModelPlan/TaskList/ITSolutions/SolutionImplementation/index.test.tsx
- src/views/ModelPlan/TaskList/PrepareForClearance/Checklist/index.test.tsx
- src/views/ModelPlan/TaskList/PrepareForClearance/ClearanceReview/index.test.tsx
MINT has been seeing CI test failures related to the user-event package in the test suite.  Recently it was updated and there were a few test suites that had a different implementation.  This PR hopefully addresses the test inconsistency
- Updated the affected tests to use `setup` util, awaited event
Run tests successfuly
CI passes successfully
> [NOREF] Address CI test failures on userEvent implementation

- .golangci.yml
- .pre-commit-config.yaml
- Raise minimum confidence for `revive` linter to ignore issues that have _very_ low confidence
- Update linters to their most recent (minor) version
- Ensure `pre-commit run --all` works as expected locally, and in CI
> [NOREF] Raise minimum revive confidence, update linters

- src/components/Header/index.test.tsx
- src/components/NavigationBar/index.scss
- src/components/NavigationBar/index.test.tsx
- src/components/NavigationBar/index.tsx
- src/gql/apolloGQL/Notifications/GetPollNotifications.ts
- src/gql/gen/graphql.ts
- src/gql/gen/types/GetPollNotifications.ts
- src/i18n/en-US/header.ts
- Added poll query to fetch if user has notifications
-  Polling 5 second interval
- Added `NavigationBar` item for notification link and icon
- Added LD flag around changes
- Added/updated unit tests
- Trigger a notification for a user when tagged in a discussion
- Verify (within a span of 5 seconds) that the icon turns black and renders a red circle
- Use Postman to mark notification as read
- Verify that the icon returns to it's grey/outline state (within a span of 5 seconds)
- Verify mobile view matches figma
- Verify LD flag setting work - toggle in LD to test
- Always make …
> [EASI-3920] - Notification menu bar

- src/components/shared/Alert/index.scss
- src/components/shared/Alert/index.tsx
- src/i18n/en-US/draftModelPlan/itSolutions.ts
- src/views/ModelPlan/TaskList/ITSolutions/AddSolution/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/ITSolutions/AddSolution/index.tsx
- src/views/ModelPlan/TaskList/ITSolutions/SelectSolutions/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/ITSolutions/SelectSolutions/index.tsx
- Added alert on select solutions when a solution is selected that isn't of type other
- Added alert on add solution when a solution is added that isn't of type other
- Added additional prop on `Alert` component to better match figma
Verify matches [Figma](https://www.figma.com/file/BcI7pNwfkmwaDD2EGGTsYC/IT-Lead?type=design&node-id=2428-414&mode=design&t=bWCvdnszKdGA00IY-0)
Should only render if a non-other solution is selected
> [EASI-4051] Added alert on select solutions

- src/views/Notifications/Home/_components/IndividualNotification.tsx
- Changed where the user gets pushed to after clicking the view discussion link
- Change 2
1. Create a notification 
2. Click the view discussion
3. Verify that you are now in the read only discussion page
> [NOREF] change the link to send to read only discussion view

- migrations/V151__Update_Possible_Operational_Solution_Contacts.sql
- src/i18n/en-US/helpAndKnowledge/helpAndKnowledge.ts
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Timeline/__snapshots__/index.test.tsx.snap
- Remove two contacts as possible operational solution contacts
- Add new possible operational solution contacts
1. Open the application
2. Navigate to the solutions help page
3. Investigate the timeline and point of contact page for ISP, HDR, and CDX. Ensure that they match FIGMA.
[ISP Figma](https://www.figma.com/file/dzzLdDf6UwkLA51BtoAt3T/MINT---Knowledge-Center?type=design&node-id=2391%3A89475&mode=design&t=9iGU6vnArsYCQrDY-1)
[HDR Figma](https://www.figma.com/file/dzzLdDf6UwkLA51BtoAt3T/MINT---Knowledge-Center?type=design&node-id=2391%3A89457&mode=design&t=9iGU6vnArsYCQrDY-1)
[CDX Figma](https://www.figma.com/file/dzzLdDf6UwkLA51BtoAt3T/MINT---Knowledge-Center?type=design&node-id=2391%3A89446&mode=design&t=9iGU6vnArsYCQrDY-1)
4. To be thorough, select these solutions for an …
> [EASI-4054] Solution Contact Updats

- src/i18n/en-US/helpAndKnowledge/helpAndKnowledge.ts
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Timeline/__snapshots__/index.test.tsx.snap
- Change technical lead to product owner
1. Verify The header for HDR now says to reach out to Product Owner instead of Technical Lead
> [Easi-4054] Solution contact text change fix

- src/views/ModelPlan/TaskList/GeneralCharacteristics/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/GeneralCharacteristics/index.tsx
- Removed Other option for existingModel
[Slack](https://oddball.slack.com/archives/C059QQA3HK5/p1710516926381299)
> NOREF/ Removed Other option for existingModel

- migrations/V152__Update_Possible_Operational_Solution_Contacts.sql
- Created update migration
- Removed old POCs
- Added new POcs
- Bring up fresh backend containers
- Inspect the possible_operational_solution_contact table
- Assert that entries for `Felicia Addai` and `Miyani `Treva` are removed
- Assert that entries for `Sarah Okorafor` and `Luiz Lee` are added
> [EASI-4141] Update POCs for MDM

- .spelling
- docs/adr/0016-change-history-solutioning.md
- Create an ADR to capture decisions made about Change History.
No testing required, please review the new [ADR](https://github.com/CMSgov/mint-app/blob/EASI-4182/change_history_ADR/docs/adr/0016-change-history-solutioning.md) and see if it is as you expect!
> [EASI-4182] Change History Solutioning ADR

- src/i18n/en-US/modelPlan/participantsAndProviders.ts
- src/views/ModelPlan/TaskList/ParticipantsAndProviders/ParticipantOptions/__snapshots__/index.test.tsx.snap
https://oddball.slack.com/archives/C06RF2Q327R/p1712248820535789
- `appy` to `apply`
|Before|After|
|---|---|
|![image](https://github.com/CMSgov/mint-app/assets/2349702/799c3c0c-8bfb-4939-b3c4-eaa8fb256d14)|![image](https://github.com/CMSgov/mint-app/assets/2349702/6b9009e7-aff1-41eb-ac90-cf800e725bd0)|
1. Go through the Participants and Providers task list and verify typo has been fixed
> [NOREF] Fix typo in Participants and Providers

- src/hooks/useFetchCSVData.tsx
- Fixed data structure fed to `isHiddenByParentCondition` within the csv export
Verify questions that have the parent condition fulfilled are rendered in csv
Verify questions that do not have the parent condition fulfilled are not rendered in csv
> [NOREF] Fixed csv export for conditional questions

- mappings/export/exportTranslation.test.ts
- mappings/export/util.ts
- mappings/translation/plan_basics.json
- mappings/translation/plan_beneficiaries.json
- mappings/translation/plan_collaborators.json
- mappings/translation/plan_general_characteristics.json
- mappings/translation/plan_ops_eval_and_learning.json
- mappings/translation/plan_participants_and_providers.json
- mappings/translation/plan_payments.json
- Modified export to call closures for parent/child relation
- Updated unit test
Verify that the export evaluates the closures to represent the parent/child obj configs
> [NOREF] Add closure to translation export

- src/components/shared/CollapsableLink/index.tsx
- src/stylesheets/print.scss
- src/views/ModelPlan/ReadOnly/Team/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/Team/index.tsx
- src/views/ModelPlan/ReadOnly/_components/ReadOnlySection/index.tsx
[EASI-4227](https://jiraent.cms.gov/browse/EASI-4227)
[EASI-4228](https://jiraent.cms.gov/browse/EASI-4228)
[EASI-4230](https://jiraent.cms.gov/browse/EASI-4230)
- Addressed all findings per the above tickets
Verify findings are addressed per linked images/descriptions in tickets
> [EASI-4218] Readonly fixes- should haves

- src/gql/gen/graphql.ts
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/_components/Contact/index.stories.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/_components/Contact/index.test.tsx
- Add `isPrimary` to wherever there were an error 
1. Verify all tests and lint are not throwing any errors
> [NOREF] Fix isPrimary lint errors

- mappings/translation/plan_basics.json
- mappings/translation/plan_beneficiaries.json
- mappings/translation/plan_general_characteristics.json
- mappings/translation/plan_ops_eval_and_learning.json
- mappings/translation/plan_participants_and_providers.json
- mappings/translation/plan_payments.json
- migrations/V155__Translated_Audit.sql
- pkg/graph/resolvers/possible_operational_solution.resolvers.go
- pkg/graph/resolvers/translation.resolvers.go
- pkg/models/translation_field.go
- pkg/translatedaudit/conditional_questions.go
- Add Table reference to GO model
- Export the Translation JSON with Ready for Review By
- Update conditional check to look for pq.string array and not just []string
> ReadyForReviewExport, UUID data data, table reference

- src/components/ShareExport/__snapshots__/index.test.tsx.snap
- src/components/ShareExport/index.scss
- src/components/ShareExport/index.tsx
- Adjusted some class and styles for the tab in the share modal 
1. Go to any model plan
2. Click `Share or export this modal plan`
3. Ensure the tabs on the modal matches figma
|    |    |
|----|----|
|Before|![image](https://github.com/CMSgov/mint-app/assets/2349702/eaf21bfb-9c55-4189-8b4b-0fa0156d023b)|
|After|![image](https://github.com/CMSgov/mint-app/assets/2349702/c2d7fa04-f02e-4920-a346-d05317e634ef)|
> [NOREF] Share Modal Tab Style Fix

- cypress/e2e/collaborator.spec.js
- src/i18n/en-US/modelPlan/collaborators.ts
- Changed the translation file
|Before|After|
|-------|-------|
|![image](https://github.com/CMSgov/mint-app/assets/2349702/77b851c1-cdc6-4d22-9745-118d279b3ee5)|![image](https://github.com/CMSgov/mint-app/assets/2349702/39222674-c331-4178-a8cc-0921d38ecc93)|
> [EASI-4143] Update Text spacing issue on modal when removing team member

- src/i18n/en-US/modelPlan/opsEvalAndLearning.ts
- src/views/ModelPlan/TaskList/OpsEvalAndLearning/DataSharing/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/OpsEvalAndLearning/DataSharing/index.tsx
- Add new heading and adjust styling for existing label
1. Go to page 4 of Operations, evaluation, and learning questions
2. Verify the new header is there and style matches
> [EASI-4165] Add Missing heading and label styling for quality reporting questions

- src/i18n/en-US/modelPlan/opsEvalAndLearning.ts
Addressing issue brought up in the [mint-potluck channel](https://oddball.slack.com/archives/C06RF2Q327R/p1714577607929979)
- Changed text to match request
1. Go to the Operations, Evaluation, and Learning questions
2. Select `yes` to the question: `Are you planning to use IDDOC support?`
3. Go to Page 3 and check `Other` to the question `What types of files? Select all that apply.`
4. Verify that the text has changed
> [NOREF] Operations, Evaluation, and Learning text update

- graphql-schema-linter.config.js
- mappings/export/exportTranslation.ts
- mappings/export/util.ts
- mappings/translation/discussion_reply.json
- mappings/translation/operational_solution.json
- mappings/translation/operational_solution_subtask.json
- mappings/translation/plan_cr.json
- mappings/translation/plan_discussion.json
- mappings/translation/plan_document.json
- mappings/translation/plan_tdl.json
- mappings/translation/possible_operational_need.json
- pkg/graph/model/models_gen.go
- pkg/graph/schema/types/discussion_reply_translation.graphql
- pkg/graph/schema/types/discussion_translation.graphql
- pkg/graph/schema/types/operational_solution_subtask_translation.graphql
- pkg/graph/schema/types/plan_cr_translation.graphql
- pkg/graph/schema/types/plan_discussion_translation.graphql
- pkg/graph/schema/types/plan_document_translation.graphql
- pkg/graph/schema/types/plan_tdl_translation.graphql
- pkg/graph/schema/types/possible_operational_need_translation.graphql
- pkg/graph/schema/types/possible_operational_solution_translation.graphql
- src/gql/gen/graphql.ts
- src/i18n/en-US/index.ts
- src/i18n/en-US/modelPlan/replies.ts
- src/types/translation.ts
- src/views/ModelPlan/Discussions/QuestionAndReply.tsx
- Added remaining translations to schema (Docs, crs, tdls, needs, solutions, subtasks)
- Integrated generated types with FE types
- Updated export to include new translations
- Ran/generated export data
Verify exports are correct
> [EASI-4292] Add remaining schema translations and exports

- docs/faktory.md
- Added some additional documentation on how to deploy faktory jobs.
Read the documentation, and please feel free to suggest anything that should be added.
> [NOREF] Faktory documentation for deployed environments

- migrations/V157__Primary_POC_update_to_match_figma.sql
- pkg/graph/resolvers/possible_operational_solution_contact_test.go
- Update primary POCS to match [FIGMA](https://www.figma.com/design/dzzLdDf6UwkLA51BtoAt3T/MINT---Knowledge-Center?node-id=7690-22437&t=UZPEDnzDxnePNqbB-0)
1. Run the migration
2. Compare the primary POCS to FIGMA. Ensure they match
a. you can do this with the front end, or use this SQL query
```sql
SELECT name, POS.sol_key, POS.sol_name, POS.ID AS sol_id FROM possible_operational_solution_contact AS POC
JOIN  possible_operational_solution AS POS  ON POC.possible_operational_solution_id = POS.id
WHERE is_primary = true
ORDER BY sol_key
```
- Always make comments, even if it's minor, …
> [Easi 4382]/Primary poc update to match figma

- src/views/ModelPlan/TaskList/Basics/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/Basics/index.tsx
- src/views/ModelPlan/TaskList/Payment/FundingSource/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/Payment/FundingSource/index.tsx
- Changed `optionsLabel` to `tooltips` in basics and payments
Verify that model basics and payments page 1 have tooltips rending correctly
> [EASI-4277] Fixed tooltip keying on wrong translation key

- src/views/ModelPlan/TaskList/ITSolutions/LinkDocuments/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/ITSolutions/_components/SolutionCard/index.tsx
- Changed the way the params gets set and goes
- Removed `OTHER_NEW_PROCESS` as it is not used
1. Create two not listed solutions: OTHER and CONTRACTOR
2. After creating, try to update the solution details of each and ensure that name of solution persists
> [EASI-4378] Fix missing custom solution name

- migrations/V159__Update_Possible_Operational_Solution_Contacts.sql
- pkg/graph/resolvers/possible_operational_solution_contact_test.go
- src/i18n/en-US/helpAndKnowledge/helpAndKnowledge.ts
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/4Innovation/index.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Timeline/__snapshots__/index.test.tsx.snap
- Update references in frontend
- Flyway Migration
- Remove deprecated users
- Update user data
- Add new user
Bring up containers
Run js snapshot tests
Open 4i and ACO_OS
Assert features match [Figma spec](https://www.figma.com/design/dzzLdDf6UwkLA51BtoAt3T/MINT---Knowledge-Center?node-id=2391-89449&t=BYwzUyeT7lhuooJb-0)
> [EASI-4346] Update POCs on 4i and ACO_OS, Correct POC Email

- .golangci.yml
- .pre-commit-config.yaml
- Same change as https://github.com/CMSgov/easi-app/pull/2633
- Enable `stylecheck` linter, as some rules were phased out of `staticcheck` and put into `stylecheck`
- Fixed all findings
- Modified exclusion for package comments to use new `stylecheck ST1000` rule instead of `package-comments` (to maintain previous functionaltiy)
If using VSCode, you can edit your settings to enable `golangci-lint` as the linter of choice for go files -- this will enable findings to appear within the editor / problems view so you can address issues before having to run the lint script! This configuration will automatically use the `.golangci-lint` file in the root of the project!
Additionally -- you can just edit an exported function/var/type to not have a comment, run `scripts/dev lint`, and ensure that …
> [NOREF] Updating golangci config

- src/i18n/en-US/modelPlan/opsEvalAndLearning.ts
- Added `multiSelectLabel` config to `dataToSendParticicipants`
Verify the label is now rendered on the form
> [EASI-4436] Bug fix - multi-select label

- MINT.postman_collection.json
- pkg/graph/resolvers/translated_audit.go
- pkg/graph/resolvers/translated_audit.resolvers.go
- pkg/graph/schema/types/translated_audit.graphql
- pkg/sqlqueries/SQL/translated_audit/collection_get_by_model_plan_ids.sql
- pkg/storage/translated_auditStore.go
- src/gql/gen/graphql.ts
- Introduce optional `LIMIT`, and `OFFSET` params to the get translated audit collection query
- Add a utility query to the postman collection to get the id of the enhancing oncology seeded model, and set the ID, so you can query and set the postman variable
1. Query a collection of known audits
2. Use the postman collection to query the translated audit collection.
3. If desired, you can use the get Sample Model Plan query to set the model plan ID variable in the postman collection to the sample model, and query the changes on that model.
4. Assert that the new limit and offset parameters work as expected for the query.
a. Assert that it works as expected if the values are left out.
b. Assert that the combination of the values work as expected.
- It's best to pull the branch locally and …
> [Easi 4150] Recent audits query

- cypress/e2e/changeHistory.js
- src/components/NDABanner/index.test.tsx
- src/components/ShareExport/__snapshots__/index.test.tsx.snap
- src/components/shared/CollapsableLink/index.tsx
- src/i18n/en-US/changeHistory.ts
- src/views/ModelPlan/ChangeHistory/components/BatchRecord/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ChangeHistory/components/BatchRecord/index.test.tsx
- src/views/ModelPlan/ChangeHistory/components/BatchRecord/index.tsx
- src/views/ModelPlan/ChangeHistory/components/ChangeRecord/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ChangeHistory/components/ChangeRecord/index.test.tsx
- src/views/ModelPlan/ChangeHistory/components/ChangeRecord/index.tsx
- src/views/ModelPlan/ChangeHistory/components/RecentChanges/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ChangeHistory/components/RecentChanges/index.tsx
- src/views/ModelPlan/ChangeHistory/index.tsx
- src/views/ModelPlan/ChangeHistory/util.test.tsx
- src/views/ModelPlan/ChangeHistory/util.tsx
- src/views/ModelPlan/ReadOnly/GeneralCharacteristics/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/OpsEvalAndLearning/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/ParticipantsAndProviders/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/Payments/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/_components/TaskListStatus/index.tsx
- Updated Read-view link for non-assessment users (previously was only showing for assessment)
- Added cypress test
- Tested search, sort, and collapsible link
Verify cypress tests run successfully
Verify read view CH link appears for non assessment users
> [EASI-4441] Cypress change history

- .pre-commit-config.yaml
- MINT.postman_collection.json
- scripts/edit_postman_json.sh
- Added script and hook for updating postman collection JSON to remove fields that we don't really need, and often cause conflicts in PRs
- Import and re-export the postman collection, and run `scripts/dev lint` and ensure the file's properly edited!
> [NOREF] Add pre-commit hook for removing often-conflicting fields in postman

- pkg/server/logger.go
Same change as made in EASi, here https://github.com/CMSgov/easi-app/pull/2652
In support of diagnosing potential areas that we might want to address for performance (largely with regards to where we might want to introduce more dataloaders), this PR adds functionality that automatically logs the response time of each request in milliseconds, allowing us to aggregate and analyze that data in Splunk.
**OF NOTE:** This PR _does_ move the `logger.Info` call _after_ the next.ServeHTTP call. This is (probably) how it should be anyways, since we don't necessarily want to hold up making the HTTP response with a logger call (and now it's needed, since we need to make the HTTP response happen before we can truly log how long it took)
- Load the UI in your browser
- `docker …
> Add middleware functionality to log response times

- src/views/App/index.tsx
- Added redirect when task list nor read view present
Verify redirect occurs in the absence of task-list or read-view route
> [EASI-4416] Added redirect when task list nor read view present

- src/i18n/en-US/helpAndKnowledge/helpAndKnowledge.ts
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/About/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Modal/index.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/4Innovation/index.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/CMSBox/index.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/CMSQualtrics/index.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/CentralizedDataExchange/index.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/ChronicConditions/index.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/Generic/about.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/HIGLAS/index.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/OutlookMailbox/index.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/RMADA/index.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/SharedSystems/index.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Timeline/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/SolutionsHelp/index.tsx
- Fixed incorrect usage of `Trans` component in help center
- Fixed bugginess of modal when url is pasted in browser
- Default to query param `page=1` if no page param present
- Updated Shared Systems to match Figma
Verify changes match figma
Verify modal closes properly is url is pasted in browser
> [EASI-4380] Shared systems updates

- src/views/HelpAndKnowledge/Articles/HighLevelProjectPlan/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/Articles/HighLevelProjectPlan/index.tsx
- src/views/HelpAndKnowledge/Articles/ModelPlanOverview/index.tsx
- src/views/HelpAndKnowledge/Articles/ModelSolutionDesign/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/Articles/ModelSolutionDesign/index.tsx
- src/views/HelpAndKnowledge/Articles/ModelSolutionImplementation/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/Articles/ModelSolutionImplementation/index.tsx
- src/views/HelpAndKnowledge/Articles/PhasesInvolved/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/Articles/PhasesInvolved/index.tsx
- src/views/HelpAndKnowledge/Articles/SampleModelPlan/index.tsx
- src/views/HelpAndKnowledge/Articles/SixPagerMeeting/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/Articles/SixPagerMeeting/index.tsx
- src/views/HelpAndKnowledge/Articles/TwoPagerMeeting/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/Articles/TwoPagerMeeting/index.tsx
- src/views/HelpAndKnowledge/Articles/UtilizingSolutions/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/Articles/UtilizingSolutions/index.tsx
- src/views/HelpAndKnowledge/Articles/_components/RelatedArticles/index.tsx
- src/views/HelpAndKnowledge/Articles/index.tsx
- Addressing https://github.com/CMSgov/mint-app/pull/1183#issuecomment-2182876462
- Implemented `specificArticleNames` into `RelatedArticles` component
- Updated all help articles with the correct related article according to figma
1. Cross check all related articles are matching figma
> [NOREF] Update related articles in help articles

- src/i18n/en-US/modelPlan/participantsAndProviders.ts
- src/views/ModelPlan/TaskList/ParticipantsAndProviders/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/ParticipantsAndProviders/index.tsx
- Add sublabel copy to question
1. Navigate to the first page of the Participants and Providers section of the Model Plan task list
2. Add `Medicare providers/suppliers` as a participant
3. Verify that the following question has the following sublabel and has copy
> [EASI-4444] Update Help Text in Participants and providers section

- src/i18n/en-US/modelPlan/basics.ts
- src/i18n/en-US/modelPlan/beneficiaries.ts
- src/i18n/en-US/modelPlan/generalCharacteristics.ts
- src/i18n/en-US/modelPlan/participantsAndProviders.ts
- src/i18n/en-US/modelPlan/payments.ts
- src/views/ModelPlan/ReadOnly/_components/FilterView/BodyContent/_filterGroupMapping.ts
- Updated PBG Filter view to match figma 
1. Filter the read view of a model plan to PBG
2. Ensure questions shown match figma
> [EASI-4451] Update PBG Filter View

- .github/PULL_REQUEST_TEMPLATE.md
Updates PR template to have some more useful guidance and clarity on what's required & expected from PR authors and reviewers!
- Read, read with your special 👀!
> [NOREF] Updating PR template

- .github/workflows/run_tests.yml
- docker-compose.backend.yml
This PR migrates our PostgreSQL database from version 14.11 to 16.2. The migration includes various improvements, bug fixes, and new features to enhance performance, security, and functionality.
* **Support for pg_log_standby_snapshot**: Added.
* **AWS Lambda Call Performance**: Fixed multisecond latency issue.
* **Autovacuum**: Bug preventing termination fixed.
* **h3 Extension**: Bug preventing creation fixed.
* **rds.rds_superuser_reserved_connections**: Deprecated. Use `reserved_connections` instead.
* **TLS Configuration**: Allows setting TLS 1.3 as `ssl_min_protocol_version` and `ssl_max_protocol_version`.
* **Default Toast Compression**: Set to LZ4.
* **orafce**: Updated to 4.9.0.
* **pg_repack**: Updated to 1.5.0.
* **pgactive**: Updated to 2.1.2.
* **pgvector**: Updated to 0.6.0. …
> [EASI-4479] (Backend) Postgres Migration from 14.11 to 16.2

- pkg/storage/plan_documentStore.go
The document store method was calling Delete by ID twice, instead of deleting the document solution links first. I caught by some unit tests in the change history branch.
1. Make a document with document solution link
2. Ensure that you can delete the document
- Check that all …
> [NOREF] Plan Document Delete bug fix

- pkg/graph/resolvers/translated_audit.go
Translated audit was just checking if a user was a collaborator to check privelleged document access. In reality, it should use `HasPrivilegedDocumentAccessByModelPlanID`
1. Log in as Non_CMS user
2. Make a model plan, upload a restricted document
3.  Verify you can't see the document in the document list
4. Verify that you can't see the audits for the document in change history
If you like, you can also change your permissions and verify that you can see the document and the audits as well.
- 
- e.g. "Approving because the change is simple …
> [NOREF] Translated Audit Restricted Access Check

- src/i18n.ts
MINT was having instances where special HTML character were getting escaped by react-i18n library via interpolation values, as well as React (natively parsing all JSX values as plain text/not computed by the browser - we do NOT have `dangerouslysetinnerhtml` set in the application).  This was leading to special characters being escaped and also being rendered as plain text - ex: `Patrick&#39;s`
https://oddball.slack.com/archives/C059N01AYGM/p1719943391656779
- Verify user input characters are rendered as human readable throughout the app.  The are handled as plaint text natively by React
- e.g. "Approving because I tested it …
> [NOREF] Added escapeValue false for i18n

- src/i18n/en-US/home/customHome.ts
- src/views/Home/index.tsx
- src/views/HomeNew/__snapshots__/index.test.tsx.snap
- src/views/HomeNew/index.scss
- src/views/HomeNew/index.tsx
- src/views/ModelPlan/HomeTable/index.scss
- src/views/ModelPlan/HomeTable/index.tsx
- src/views/ModelPlan/Table/index.tsx
- Added support for rendering CRTDL table on homepage
- Duplicated and refactored the home table, as the original was moving to far away from the custom needs of the new home page
Cypress testing will be handled once all other tables are included
- Verify CRTDL table renders and orders correctly based on user settings
- Don't be afraid to leave comments or ask questions, especially if you don't understand why something was done! (This is often a great time to suggest …
> [EASI-4393] CR TDL homepage

- pkg/email/templates/daily_digest_body.html
- src/i18n/en-US/notifications.ts
- src/views/Notifications/Home/_components/DailyDigest.test.tsx
- src/views/Notifications/Home/_components/DailyDigest.tsx
- src/views/Notifications/Home/_components/__snapshots__/DailyDigest.test.tsx.snap
This simply updates the link to point to change history instead of the task list.
- Run the app
- Seed the database
- Look in mail catcher at the URL of the view this model plan link. Note that it points to the `change-history` route
- Note that the test should also match [figma](https://www.figma.com/design/5Ux715qVJHg38EbJKavMR4/MINT---Change-History?node-id=677-3531&t=vUhdV1p4shdg8pGx-0). …
> [EASI-4509] Daily digest Email links to Change History

- src/components/ITSolutionsWarning/__snapshots__/index.test.tsx.snap
- src/components/ShareExport/__snapshots__/index.test.tsx.snap
- src/components/shared/Alert/__snapshots__/index.test.tsx.snap
- src/components/shared/Alert/index.scss
- src/components/shared/Alert/index.tsx
- src/stylesheets/custom.scss
- src/views/HelpAndKnowledge/Articles/GetAccess/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Timeline/__snapshots__/index.test.tsx.snap
- src/views/HomeNew/Settings/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/CRTDL/CRTDLs/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/Collaborators/AddCollaborator/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/Documents/AddDocument/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/NewPlan/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/CRTDLs/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/Basics/Milestones/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/GeneralCharacteristics/KeyCharacteristics/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/GeneralCharacteristics/TargetsAndOptions/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/OpsEvalAndLearning/CCWAndQuality/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/OpsEvalAndLearning/IDDOCTesting/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/OpsEvalAndLearning/Learning/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/OpsEvalAndLearning/Performance/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/ParticipantsAndProviders/Coordination/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/Payment/AnticipateDependencies/__snapshots__/index.test.tsx.snap
- src/views/NDA/__snapshots__/index.test.tsx.snap
With the latest homepage PR there was a change to an alert css style that effected alerts without icons.  Before this there was an existing styling issue on mobile where the text was not padded properly.  This PR added the appropriate style only when an icon is present.
- Verify all alerts render correctly on all responsive size, both for alerts with icons and alerts without icons.  The padding between the icon and the text should remain stable
- Don't be afraid to …
> [NOREF] Added padding class to alert

- .github/workflows/build_application_images.yml
- .github/workflows/run_tests.yml
- Dockerfile.db_clean
- Dockerfile.db_migrations
This [Slack discussion](https://oddball.slack.com/archives/C06RF2Q327R/p1721242567709509) from @StevenWadeOddball brought up that our flyway version is a bit out of date, and that newer versions of Postgres aren't supported on our current version (and we just upgraded from v14 to v16 of postgres in https://github.com/CMSgov/mint-app/pull/1200)
This PR just accomplishes 2 things:
- Updates the few locations in the codebase where we define the version of Flyway to use
- Based on some warnings that were showing up locally post-upgrade and based on the [Flyway v9 to v10 migration guide](https://documentation.red-gate.com/flyway/flyway-blog/flyway-v10-upgrading-from-flyway-v9), I updated the `FLYWAY_LOCATIONS` env var to point to a non-default location. This doesn't really accomplish much …
> Update Flyway from v9 to v10

- src/i18n/en-US/helpAndKnowledge/Articles/highLevelProjectPlans.ts
- src/i18n/en-US/helpAndKnowledge/helpAndKnowledge.ts
- src/views/HelpAndKnowledge/Articles/AllArticles/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/Articles/HighLevelProjectPlan/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/Articles/SixPagerMeeting/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/Articles/TwoPagerMeeting/__snapshots__/index.test.tsx.snap
- Fixed plural on `High Level Project Plan` help articles
- Verify matches Figma
https://www.figma.com/design/dzzLdDf6UwkLA51BtoAt3T/MINT---Knowledge-Center?node-id=2545-7830&t=hJ5kJPQg9pLgnd1e-0
- Check that all code is adequately covered by tests - if it isn't feel free to …
> [NOREF] Fixed help article plural title

- src/views/HomeNew/__snapshots__/index.test.tsx.snap
- src/views/HomeNew/index.test.tsx
- src/views/HomeNew/index.tsx
- src/views/ModelPlan/HomeTable/index.tsx
I believe there was flakiness in unit test due to lots of different loading states.  This PR add specific testids to each loading component to be able to check individually when loading component unmount
- 
- Check that all code is adequately covered by tests - if it isn't feel …
> [NOREF] Fix flaky test 2

- src/i18n/en-US/home/customHome.ts
- src/views/HomeNew/index.tsx
Natasha and I identified a confusing alert text on the homepage for followed models if you aren't following any.  This PR adds a link to the models tab to be able to follow a model if you aren't following any
- Log in and select the setting to have the models you're following on you're homepage. 
- Make sure you aren't following any models
- Verify the link appears in the alert to take you to the /models tab
- Don't be afraid to leave comments or ask questions, …
> [NOREF] Added updated alert text for followed models

- pkg/graph/resolvers/analyzed_audit.go
- pkg/worker/aggregated_digest_email_job_test.go
- pkg/worker/analyzed_audit_job.go
- pkg/worker/analyzed_audit_job_test.go
- pkg/worker/digest_cron_job.go
- pkg/worker/digest_cron_job_test.go
- pkg/worker/digest_email_job.go
- pkg/worker/digest_email_job_test.go
- pkg/worker/job_utilities.go
- pkg/worker/translate_audit_cron_job.go
- pkg/worker/translate_audit_job.go
- pkg/worker/worker.go
There is an issue where daily digests are not getting sent in DEV. There is not enough logging on those jobs to determine what is going wrong.
This introduces a sugared logger where possible that includes parameters, JIDS (Faktory Job IDS), BIDS (Faktoy Batch IDS) and passes it to all functions instead of just the worker.logger.
It also wraps all analyzed audit and digest jobs in a panic protection function in case that was the issue.
- Verify all the changes visually.
- Verify Unit tests pass
- e.g. "Approving because the change is simple and …
> [EASI-4558]/daily digest logging improvements

- mappings/discussion_reply_translation_test.go
- mappings/existing_model_link_translation_test.go
- mappings/model_plan_translation_test.go
- mappings/operational_need_translation_test.go
- mappings/operational_solution_subtask_translation_test.go
- mappings/operational_solution_translation_test.go
- mappings/plan_basics_translation_test.go
- mappings/plan_beneficiaries_translation_test.go
- mappings/plan_collaborator_translation_test.go
- mappings/plan_cr_translation_test.go
- mappings/plan_discussion_translation_test.go
- mappings/plan_document_solution_link_translation_test.go
- mappings/plan_document_translation_test.go
- mappings/plan_general_characteristics_translation_test.go
- mappings/plan_ops_eval_and_learning_translation_test.go
- mappings/plan_participants_and_providers_translations_test.go
- mappings/plan_payments_translation_test.go
- mappings/plan_tdl_translation_test.go
- mappings/translation_test_utilities.go
- pkg/graph/resolvers/translated_audit_field_test.go
- pkg/worker/job_utilities_test.go
- pkg/worker/translate_audit_job_test.go
> [NOREF] Change History PR adjustments

- MINT.postman_collection.json
- pkg/graph/generated/generated.go
- pkg/graph/resolvers/calc_model_plan_anticipated_status.go
- pkg/graph/resolvers/model_plan.go
- pkg/graph/resolvers/model_plan.resolvers.go
- pkg/graph/resolvers/status_evaluation_strategies.go
- pkg/graph/resolvers/status_evaluation_strategies_test.go
- pkg/graph/schema/types/model_plan.graphql
- pkg/models/model_plan.go
- pkg/shared/utilitytime/checks.go
- src/gql/gen/graphql.ts
A functional resolver, AnticipatedStatuses, has been created on ModelPlan to determine anticipated statuses based on the following conditions.
- “Complete ICIP” date in anticipated timeline has passed but status is not "ICIP completed" or a future status
- “Clearance start date” date in anticipated timeline has passed but status is not any of the clearance statuses or a future status
- “Clearance end date” date in anticipated timeline has passed but status is not "Cleared" or a future status
- “Announce model” date in anticipated timeline has passed but status is not "Announced" or a future status
- “Performance start date” date in anticipated timeline has passed but status is not "Active" or a future status
- “Performance end date” date in anticipated timeline has passed but status is …
> [EASI-4536] (Backend) Model Plan Anticipated Statuses

- mappings/export/exportTranslation.test.ts
- mappings/translation/plan_basics.json
- mappings/translation/plan_general_characteristics.json
- src/i18n/en-US/modelPlan/basics.ts
- src/i18n/en-US/modelPlan/generalCharacteristics.ts
- General Characteristics status were capitalized differently, address this change and ran export
https://docs.google.com/document/d/17zoYGYf3nT6i_Cj6svLE_Qvv2GJLNnCbZRD5Vvt6B0I/edit#heading=h.kp20ddis6xor
- Verify status renders correctly according to doc
- Check that all code …
> [NOREF] Fix capitalization in General Characteristics

- src/views/Home/Table/index.tsx
Fix key char crtdl table render
- Render string in CRTDL table on home page
> [NOREF] Fix key char crtdl table render

- .github/PULL_REQUEST_TEMPLATE.md
I updated instances of ticket numbers referencing EASI --> MINT
I also defaulted testing steps to be numerical instead of a bullet point, to preserve ordering.
- Look at the updated template.
- Check that all code is adequately covered by tests - if it isn't feel free to suggest …
> [NOREF] PR template updates

- cypress/e2e/notification.spec.js
- src/i18n/en-US/modelPlanTaskList.ts
- src/views/ModelPlan/Status/index.test.tsx
- src/views/ModelPlan/Status/index.tsx
- src/views/ModelPlan/TaskList/index.tsx
- Added mutation handler to parse query param from url/email link and attempt to update status from task list
- Error states for mutation and if status is already set
- Success state
- Clears param after attempt
- Added default status on `<Status />` component tp take a default status for clearance status from email
- Added success message on next page/task list
- Added cypress test
- Navigate to task list of a model plan
- Added query param `?model-status=ACTIVE` or any `ModelStatus` enum value.  This is case sensitive.  I decided to leave it case sensitive to stay true to enum value
- Verify status gets updated and alert renders
- Add a random string, verify error
- Add the existing status, verify specific error
- It's best to pull the branch locally and test it, rather than just …
> [MINT-2998] Status route mutation handler

- MINT.postman_collection.json
- pkg/graph/generated/generated.go
- pkg/graph/model/models_gen.go
- pkg/graph/resolvers/model_plan.go
- pkg/graph/resolvers/model_plan.resolvers.go
- pkg/graph/resolvers/status_evaluation_strategies.go
- pkg/graph/resolvers/status_evaluation_strategies_test.go
- pkg/graph/schema/types/model_plan.graphql
- src/gql/gen/graphql.ts
In order to support frontend and email template needs we have anticipatedStatuses to include a phase enumeration value for easy state handling. Also, in order to more easily infer attribute intent we have updated the name from anticipatedStatuses to suggestedPhase. A null phase result indicates that there is no currently suggested phase.
1. Open Postman and run any of the endpoints to validate a phase and corresponding suggested statuses
2. Check unit tests
- Don't be …
> [MINT-3006] Refactor Backend to Support Model Plan Phases

- src/views/ModelPlan/Status/index.tsx
- src/views/ModelPlan/TaskList/index.tsx
Status  status mutation handler was no longer needed on task list to automatically change status from email links.  Status page should already be set to handle default status selections with the appropriate query parmater
- Removed status mutation handler from tasklist
1.  Verify no statuses get updated on task list with supplied query parameter
2. Verify and status set on the status form page via `?model-status={status}` query parameter, that that status is set as the default
- e.g. "Approving because the change is simple and matches the …
> [MINT-3025] Removed status mutation handler from tasklist

- .faktory/conf.d/cron.toml
- pkg/worker/model_status_update_batch_job.go
- pkg/worker/model_status_update_batch_job_test.go
- pkg/worker/model_status_update_cron_job.go
- pkg/worker/model_status_update_job.go
- pkg/worker/model_status_update_job_test.go
- pkg/worker/translate_audit_batch_job_test.go
- pkg/worker/worker.go
- pkg/worker/worker_test.go
The goal of this PR is to provide the boiilerplate code for a new cron and batch job in faktory. This will be run once a day to suggest if a model plan should have an email sent to suggest an email be sent. It is expected that this code will be updated as the business logic around suggestions evolves.
Current assumptions:
1. There will be query that returns model plans that should be checked if a status update check should be run.
2. The ModelStatusUpdateJob will be updated with the business logic to actually evaluate and notify users.
Unit tests in this package assert that the parameters are provided as anticipated, and that the job can complete without error. Other unit tests should be made in the package which defined business logic
> [!NOTE]
> The jobs.md file can be updated to show …
> [MINT-3007] notification to model leads faktory boilerplate

- src/components/CalendarDate/index.tsx
- src/stylesheets/custom.scss
- src/views/Home/components/ModelsApproachingClearance/index.tsx
Tweak style on `CalendarDate` component link to append to the end of the text than float to the right and center
Also added abbreviation/short name to model link
1.  Verify Figma
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition …
> [NOREF] Tweak style for CalendarDate

- pkg/shared/oddmail/go_simple_mail_service.go
> [!important]
> I think MINT-2637 calls out specifically handling the "Model Plan Created" notification being the source of this, but per my testing instructions, this could actually happen in a number of different cases, so I opted to handle (more generically) _any_ case where we attempt to send an email with no recipients.
- Updates go_simple_mail_service.go to un-export the `SendEmail` function (in favor of leaving `Send` exported instead, since that was the only one that was used outside the package anyways)
- Updates `sendEmail` to handle checking the length of the recipient list before sending.
- I opted for this approach since it felt a bit cleaner than checking the [returned error's](https://github.com/xhit/go-simple-mail/blob/3161d31a9a885a33b09566f408732f39624dc4ec/email.go#L785 …
> [MINT-2637] Handle sending email with no recipients

- src/components/CalendarDate/index.tsx
Tweak font size per UX doc
https://docs.google.com/document/d/1YkNVPdWzrEgVZTEO6YQIHo3XT6rB1ixOQxAihtuw29I/edit
1.  Verfiy via doc
> [NOREF] Font tweak CalendarDate Link

- .github/workflows/deploy_pipeline.yml
- Remove DEV from `main` deployment pipeline
1.  Github Actions CI/CD changes only - no testing required
> MINT-3066: remove dev from deploy pipeline

- src/views/UserInfoWrapper/index.tsx
Target the correct `idToken` parent object instead of `accessToken`
1.  
> [NOREF]  Fix incorrect OKTA email field

- package.json
- src/components/UpdateStatusModal/index.test.tsx
- src/utils/testing/MockedProvider.tsx
- yarn.lock
- Upgrades `@apollo/client` to the latest version
- Also replaces/removes references to `@apollo/react-testing` import in favor of `@apollo/client/testing`
- Just smoke test the application and make sure things work as expected. This doesn't really touch one specific area of the application, so keep in mind things like:
- Areas that we have custom cache policies
- Task List Locking
- Document Upload
- Don't be afraid to leave comments or ask questions, especially if …
> [NOREF] Upgrade @apollo/client to latest version

- migrations/V173__Update_CPI_Vetting_Operational_Solution.sql
- pkg/models/possible_operational_solution_contact.go
- pkg/sqlqueries/SQL/possible_operational_solution_contact/collection_get_by_possible_solution_id.sql
- pkg/sqlqueries/SQL/possible_operational_solution_contact/get_primary_contact_by_possible_solution_id.sql
- src/i18n/en-US/helpAndKnowledge/helpAndKnowledge.ts
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Timeline/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Timeline/index.test.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/_components/GatheringInfoAlert/index.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/solutionsMap.tsx
* Updated card timeline and point of contact for CPI Vetting possible operational solution
* Fixed is_team selection in query and model
1. Bring up the service containers
2. Navigate to the CPI Vetting card and validate that it matches the [Figma ](https://www.figma.com/design/dzzLdDf6UwkLA51BtoAt3T/MINT---Knowledge-Center?node-id=2391-89455&t=fKBJ4ICc5kC7cALD-0) spec …
> [MINT-3001] Possible operational solution POC Update - CPI Vetting

- pkg/graph/resolvers/model_plan_phase.go
- pkg/graph/resolvers/model_plan_phase_test.go
- pkg/worker/model_status_update_job.go
Addresses the following changes:
1.  
> [MINT-1905] [MINT-3068] Address backend findings with automatic status update email

- src/components/ShareExport/__snapshots__/index.test.tsx.snap
- src/components/ShareExport/index.test.tsx
- src/data/mock/readonly.ts
- src/i18n/en-US/modelPlan/generalCharacteristics.ts
- src/views/ModelPlan/ReadOnly/GeneralCharacteristics/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/OpsEvalAndLearning/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/Payments/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/_components/ReadOnlySection/index.tsx
- Fixed issue where nested lists were rendering a bit wonky.  Only occurred on one or two questions
Now renders as a single bullet beneath the parent question
- Fixed issue where values of select dropdowns were not being rendered
Only happens here:
1.   …
> [Mint-2994] Read view list empty state fix

- src/views/ModelPlan/CollaborationArea/Cards/ModelPlanCard/index.tsx
* Add some margin to the spinner so that it does not spill over
| Before       | After       |
| -------------- | -------------- |
| ![Screenshot 2024-08-23 at 1 56 10 PM](https://github.com/user-attachments/assets/9b5622fa-4ba3-4257-b3c3-a4e5e9f18e37)| ![image](https://github.com/user-attachments/assets/7478b6b5-1513-4f98-8dae-4e83bacf9687) |
1.  Verify that the spinner's spacing in not off the grid
2. 
- Don't be afraid to leave comments or ask questions, especially …
> [NOREF] Fix the loading spinner in Model Plan Card in Collaboration Area

- pkg/graph/resolvers/model_plan_phase.go
- pkg/graph/resolvers/model_plan_phase_test.go
* Identified an issue where our email template inputs were static and therefore providing incorrect behavior for the user
* Confirm that emails are suggesting the correct values
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition …
> [NOREF] Fix for Automatic Model Phase Suggestion Email

- src/views/HelpAndKnowledge/SolutionsHelp/_components/SolutionHelpCardGroup/index.tsx
- Fixed bug where there was sometimes an undefined solution within the solution category list with the category - `applications-and-participation-interaction-aco-and-kidney`
1. Verify that clicking on the category - `applications-and-participation-interaction-aco-and-kidney` works as expected …
> [NOREF] Filter on undefined help solution

- .faktory/conf.d/cron.toml
- pkg/email/templates/model_plan_suggested_phase_body.html
- Updates email styling to the "Suggested Status" emails to fix some spacing and text-size issues
- (Unrelated) Updates Faktory Cron TOML to run suggested status job every 1 minute instead of every 5 minutes for easier testing!
> [!tip]
> Ensure your `.envrc.local` has `export FAKTORY_PROCESS_JOBS=true` in it!
3. Create a model plan
4. Set the ICIP Completed date in Model Basics to a date in the past
5. Wait 1 minute
6. Ensure the email comes through on http://localhost:1085
- e.g. "Approving because the change is simple and matches the Figma …
> [NOREF] Fix styling on suggested status email

- cypress/e2e/modelPlan.spec.js
- src/components/FavoriteCard/__snapshots__/index.test.tsx.snap
- src/components/FavoriteCard/index.tsx
- src/components/ShareExport/__snapshots__/index.test.tsx.snap
- src/i18n/en-US/modelPlan/miscellaneous.ts
- src/i18n/en-US/modelPlan/modelPlan.ts
- src/i18n/en-US/readOnly/generalReadOnly.ts
- src/views/Home/components/ModelsBySolutions/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/CollaborationArea/Cards/ModelPlanCard/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/CollaborationArea/Cards/ModelPlanCard/index.tsx
- src/views/ModelPlan/Collaborators/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/Collaborators/index.tsx
- src/views/ModelPlan/Documents/AddDocument/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/Documents/AddDocument/index.tsx
- src/views/ModelPlan/ReadOnly/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/Status/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/ITSolutions/SolutionDetails/index.tsx
- src/views/ModelPlan/TaskList/_components/TaskListStatus/index.tsx
- src/views/ModelPlan/TaskList/index.tsx
QA fixes per [Doc](https://docs.google.com/document/d/1WcYwLtblwjXnnsBG3uE69v9eJ9PT147-GIimGONSq_8/edit?pli=1#heading=h.qwrm0ud0q9o)
1.  QA fixes addressed
> [NOREF] QA collaboration area fixes

- src/views/Notifications/Home/index.tsx
With the recent pagination conversion, notification page length was set to 3.  This should be 10
1.  Notifications are listed as 10 per page
> [NOREF] Change notification page length to 10

- src/views/ModelAccessWrapper/index.tsx
Fixed issue on readview where access control was firing.  Should only fire on collaboration routes now
1.  Verify access control as a basic user on read view documents, and task list
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the …
> [NOREF] Fixed user access for collaboration area and read view

- src/components/TableFilter/index.tsx
- src/views/Home/Table/index.tsx
* Referring to https://react-table-v7-docs.netlify.app/docs/faq#how-do-i-stop-my-table-state-from-automatically-resetting-when-my-data-changes
* Add `skipPageResetRef` to component
* default state is false
* set to true when user favorites/unfavorites a plan ==> table stays on page
* set to false when user searches for a plan ==> table resets back to page 1
1.  Create enough models so that `All Models` have at least two pages
2. Go to page 2 and favorite a plan
3. Verify that table does not reset to page 1
4. Search for any model plan, like `Plan` and verify that table resets to page 1
- e.g. "Approving because I tested it …
> [MINT-3037] Pagination Improvement

- pkg/server/routes.go
This PR aims to address an issue with our email client failing to execute a `STARTTLS` command before sending an email.
This change can't really be tested locally since we only use mailcatcher locally. I have validated this change by running a [manual deployment](https://github.com/CMSgov/mint-app/actions/runs/10683996461) to `dev` and trying the change there (and the fix works as expected) …
> [NOREF] Fix SMTP TLS config

- src/components/ShareExport/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/ModelBasics/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/ModelBasics/index.tsx
- src/views/ModelPlan/ReadOnly/__snapshots__/index.test.tsx.snap
When you navigate to Read View Model Basics view, the console will scream at you, saying that `<div>` cannot be a descendant of `<p>`. This PR addresses this cry of horror.
1.  Navigate to read view model basics and inspect the console.
2. Verify that there is no more error being logged.
- Don't be afraid to leave comments or ask questions, especially if you don't understand why something was done! (This is often a great time to suggest code comments or documentation …
> [NOREF] Addressing Console Warnings in Read View Model Basics

- src/views/ModelPlan/ReadOnly/_components/Sidenav/index.tsx
- src/views/ModelPlan/ReadOnly/index.tsx
When a user is viewing the read-view of a model plan and move from Model basics to General characteristic section the page jumps to the top and not maintaining the scroll position
The page wouldn't jump to the top when changing tabs. It should only scroll to the top of that particular section.
1. Login into MINT
2. Navigate to the read-view of a model plan
3. Click on Model basics then go to General characteristics --> this should produce the bug
1. Navigate to the read-view of a model plan
3. Click on Model basics then go to General characteristics
4. Click through all sections and verify that scrolling to the top of the Read Only body content if user is scrolled pass the filter bar
- When …
> [MINT-3078] Read View Scrolling Bug

- src/validations/documentUploadSchema.ts
When a user links an invalid link, validation error is not translated correctly.
1.  Navigate to linking a document
2. Copy and paste current URL
3. Verify that the validation error is translated, unlike the before screenshot
- Check that all code is adequately covered by tests - …
> [NOREF] fixing translation error

- src/views/Home/Table/index.tsx
Fixed the home and /models table that was a duplicate instance of an alert when no results found
1.  Verify any table that has search does not render a duplicate alert
> [MINT-3094] Fixed double table alert render

- cypress/e2e/discussions.spec.js
- pkg/email/templates/plan_discussion_created_body.html
- src/i18n/en-US/collaborationArea.ts
- src/views/ModelPlan/CollaborationArea/Cards/DiscussionsCard/index.tsx
- src/views/ModelPlan/CollaborationArea/index.tsx
- src/views/ModelPlan/TaskList/index.tsx
- Added new card for Discussions
- Updated cypress test
- Didnt need to remove from task list
- Updated email link
1.  Verify discussion work as expected
2. Verify email link takes you to collab area instead of task list
- Check that all code is adequately covered by tests - if …
> [MINT-3031] Discussions collab area

- src/i18n/en-US/helpAndKnowledge/helpAndKnowledge.ts
- src/views/HelpAndKnowledge/Articles/AllArticles/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/Articles/HighLevelProjectPlan/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/Articles/ModelSolutionDesign/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/Articles/ModelSolutionImplementation/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/Articles/PhasesInvolved/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/Articles/SixPagerMeeting/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/Articles/TwoPagerMeeting/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/Articles/UtilizingSolutions/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/Articles/_components/ArticleCard/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/Articles/_components/ArticleCard/index.tsx
- src/views/HelpAndKnowledge/Articles/_components/RelatedArticles/__snapshots__/index.test.tsx.snap
- src/views/HelpAndKnowledge/Articles/_components/RelatedArticles/index.tsx
- src/views/ModelPlan/CollaborationArea/index.tsx
- Added prop to `<RelatedArticles />` for implementation type - default to help center
- Added to collab area
- Updated snapshots
1.  Verfiy Figma
> [MINT-3032] Added additional resource component

- src/components/ShareExport/__snapshots__/index.test.tsx.snap
- src/features/Home/Table/index.scss
- src/features/Home/Table/index.tsx
- src/features/Home/__snapshots__/index.test.tsx.snap
- src/features/ModelPlan/CRTDL/CRTDLs/__snapshots__/index.test.tsx.snap
- src/features/ModelPlan/CRTDL/CRTDLs/__snapshots__/table.test.tsx.snap
- src/features/ModelPlan/Collaborators/__snapshots__/index.test.tsx.snap
- src/features/ModelPlan/Documents/__snapshots__/index.test.tsx.snap
- src/features/ModelPlan/ReadOnly/CRTDLs/__snapshots__/index.test.tsx.snap
- src/features/ModelPlan/ReadOnly/Documents/__snapshots__/index.test.tsx.snap
- src/features/ModelPlan/TaskList/ITSolutions/Home/__snapshots__/operationalNeedsTable.test.tsx.snap
- src/features/ModelPlan/TaskList/ITSolutions/LinkDocuments/__snapshots__/index.test.tsx.snap
- src/utils/tableSort.tsx
- One of the recent package upgrades had an unintended style effect on table headers.  This PR addresses that style issue
1.  Verify table header styles are correct
> [NOREF] Fixed table header style

- .vscode/settings.json
- apollo.config.js
- Adds properties to `.vscode/settings.json` to prompt us to use the "workspace" (i.e. `package.json`) version of Typescript instead of whatever version VSCode installs/manages
- Adds some settings to `apollo.config.js` to ensure it only parses files from `./src/gql/operations`. Previously, the apollo client was crashing because it was finding duplicate definitions in both `./src/gql/operations` and `./src/gql/generated`
1.  Ensure that when you launch VSCode you're prompted to set your Typescript version to the workspace version if it's not set already
2. Ensure that the Apollo VSCode extension doesn't crash
- e.g. "Approving …
> [NOREF] Fix Typescript and Apollo client configs

- src/contexts/ModelInfoContext/index.tsx
- src/hooks/useRouteTitle.ts
- Added `model_name` to ga4 `pageview` event
- Removed model info from `ModelInfoContext` when not viewing a model plan
1.  Verify that `model_name` shows up in the ga4 localhost data stream under `event_count` -> `page_view` -> `model_name`
- Check that all code is adequately …
> [NOREF] Added model name to ga and removed name from context

- src/features/ModelPlan/TaskList/Basics/Milestones/index.test.tsx
- src/features/ModelPlan/TaskList/Payment/BeneficiaryCostSharing/index.test.tsx
#NOREF
We were getting some recent flakiness.  This is a small explicit fix for the affected tests, but we have another ticket for a more comprehensive audit of unit tests.  I've ran this PR's checks in CI a few times, all passed
1.  CI tests pass …
> [NOREF] Address unit flaky test

- .pre-commit-config.yaml
- pkg/graph/resolvers/echimp.resolvers.go
- src/gql/generated/graphql.ts
- src/hooks/useOktaUserLookup.tsx
The recent plugin `typescript-react-apollo` seemed to generated some altered/supplemental types for operation base variables.  This resulted in a diff with the generated types, as well as one instance where we needed to be more explicit with a query option
1.  All tests pass
- …
> [NOREF] typescript-react-apollo TS fix

- .envrc
- .vscode/settings.json
- MINT.postman_collection.json
- cmd/dbseed/echimp.go
- cmd/dbseed/seeder.go
- docker-compose.backend.yml
- pkg/appconfig/config.go
- pkg/echimpcache/echimp_cache.go
- pkg/echimpcache/echimp_cache_test.go
- pkg/echimptestdata/echimp_test_data.go
- pkg/graph/resolvers/echimp.go
- pkg/graph/resolvers/echimp.resolvers.go
- pkg/graph/resolvers/echimp_test.go
- pkg/graph/resolvers/model_plan.resolvers.go
- pkg/graph/resolvers/resolver.go
- pkg/graph/resolvers/resolver_test.go
- pkg/graph/resolvers/resolver_test_utilities.go
- pkg/graph/schema/types/echimp.graphql
- pkg/models/echimp_cr.go
- pkg/models/echimp_tdl.go
- pkg/s3/download.go
- pkg/s3/upload.go
- pkg/server/routes.go
- pkg/testconfig/s3testconfigs/s3_test_configs.go
- pkg/testconfig/test_config_base.go
- src/gql/generated/graphql.ts
1. Configurable file path for CR and TDL
2. CR Summary is now Tagged Content ( it is not actually tagged, but we utilize this existing type for simplicity.) 
1.  Query CR and TDLs
2. Ensure CR Summary is returned as a Tagged Content String
- Check that all code is adequately …
> [NOREF]cr tdl config follow up

- MINT.postman_collection.json
- cmd/dbseed/main.go
- cmd/dbseed/resolver_wrappers.go
- pkg/echimpcache/echimp_cache.go
- pkg/echimpcache/echimp_cache_test.go
- pkg/graph/resolvers/echimp.go
- pkg/graph/resolvers/echimp.resolvers.go
- pkg/graph/resolvers/echimp_test.go
- pkg/graph/resolvers/model_plan.go
- pkg/graph/resolvers/model_plan.resolvers.go
- pkg/graph/resolvers/model_plan_test.go
- pkg/graph/resolvers/resolver_test.go
- pkg/s3/errors.go
- pkg/worker/worker_test.go
1. Introduce seed data with existing echimp model data
2. Update Postman collection
1.  Query  the seeded model plan, look at the related echimp CR or TDL
2. ( you can use the updated postman collection to do the query)
- Check that all code is adequately covered by tests - if it …
> [NOREF] Seed data for echimp

- pkg/server/config.go
- Removes required check for `AWSS3ECHIMPBucket` (`AWS_S3_ECHIMP_BUCKET`) since ECHIMP is not configured in our `dev` environment.
Ensure the application starts up / behaves without the `AWS_S3_ECHIMP_BUCKET` env var set locally. You can accomplish this by:
- editing your `.envrc.local` to have the line `unset AWS_S3_ECHIMP_BUCKET` at the bottom of the file
- running `direnv allow`
- running `scripts/dev up` and ensuring that the server starts as expected
> [!note]
> If the backend is configured as described above, Postman calls that attempt to fetch the ECHIMP CRs/TDLs will not work as expected unless the LD flag for `echimpEnabled` is also turned off.
- When approving a PR, provide a reason …
> [MINT-1732] Remove required clause for ECHIMP bucket name env var

- cmd/dbseed/resolver_wrappers.go
- cypress/e2e/collaborator.spec.js
- src/features/ModelPlan/TaskList/Basics/__snapshots__/index.test.tsx.snap
- src/features/ModelPlan/TaskList/Basics/index.test.tsx
- src/features/ModelPlan/TaskList/Basics/index.tsx
- src/features/ModelPlan/TaskList/Beneficiaries/Frequency/index.test.tsx
- Updates DB Seed logic to use proper local okta functions instead of local mocks
1.  
> [NOREF] Update db seed logic to use proper local mock FetchUserInfo function

- go.mod
- pkg/graph/resolvers/echimp_test.go
- pkg/graph/resolvers/model_plan.go
- pkg/graph/resolvers/model_plan.resolvers.go
- pkg/graph/resolvers/model_plan_test.go
- pkg/graph/resolvers/resolver_test.go
1. Replace the database query to get models with CR and TDLs by getting the keys from the cache instead
2. Model plans can be fetched with the updated data loader query to get model plans by IDS
3. The current query is retained until the post launch clean up work is done.
1.  Confirm unit tests pass
2. Use the existing postman collection after seeding data to confirm that 2 model plans are returned when you query model plans with CR and TDLS
- Don't be afraid to leave …
> [MINT-3131] models with echimp crs and tdls 

- src/stylesheets/custom.scss
Added margin in alert component is unintended change from upgrading USWDS package.  This style change reverts the new style
1.  Verify all alerts dont have the extra margin
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of …
> [NOREF] Fixed style on alert introduced from USWDS upgrade

- .pre-commit-config.yaml
- cmd/dbseed/translation.go
- docs/change_history.md
- mappings/export/util.ts
- mappings/translation/plan_general_characteristics.json
- mappings/translation/plan_participants_and_providers.json
- package.json
- scripts/translation_mappings.sh
- Replaces instances of `ts-node ./mappings/export/exportTranslation.ts` with a call to a new `yarn mappings:export` command
- Updates `pre-commit` script to have a reference to the aforementioned command.
> [!NOTE]
> Does the `yarn mappings:export` name for the new command in `package.json`, or should it be something else?
1.  Change a field in the `i18n` folder that maps to an exported translation
2. Run `scripts/dev lint`
3. Ensure that the final new lint step fails and modifies the right `.json` file.
- e.g. "Approving because the change …
> [NOREF] Add translation export to pre-commit

- .github/workflows/run_tests.yml
- Newer versions of the Ubuntu image don't seem to install Python, which is required for `pre-commit/action`. We were previously relying on the automatically installed version, but the docs for that action specify that this is how we _should_ be setting up python.
> [!NOTE]
> Want to see similar changes on EASi?
> https://github.com/CMS-Enterprise/easi-app/pull/2845
> https://github.com/CMS-Enterprise/easi-app/pull/2847
1.  Ensure CI/CD lint check passes!
- Don't be …
> [NOREF] Add python 3.9 setup when running pre-commit in CI

- .github/workflows/run_tests.yml
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/About/__snapshots__/index.test.tsx.snap
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Modal/index.scss
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Modal/index.tsx
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/Generic/about.tsx
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/_components/Contact/__snapshots__/index.test.tsx.snap
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/_components/Contact/index.scss
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/_components/Contact/index.tsx
- src/features/ModelPlan/ReadOnly/__snapshots__/index.test.tsx.snap
- src/features/ModelPlan/ReadOnly/_components/MobileNav/index.tsx
Addressing https://oddball.slack.com/archives/C06RF2Q327R/p1729000478195859
1.  Verify it matches https://www.figma.com/design/dzzLdDf6UwkLA51BtoAt3T/MINT---Knowledge-Center?node-id=1908-86549&node-type=frame&t=gxWh7UVp9AvZbweb-0
- Check that all code is adequately covered by …
> [NOREF] Addressing Operational Solution in Small Screens

- src/components/EChimpCards/__snapshots__/EChimpCard.test.tsx.snap
- src/components/EChimpCards/__snapshots__/EChimpCardsTable.test.tsx.snap
- src/components/ExternalLink/index.tsx
- src/features/HelpAndKnowledge/Articles/AllArticles/__snapshots__/index.test.tsx.snap
- src/features/HelpAndKnowledge/Articles/EvaluatingDataExchangeApproach/__snapshots__/index.test.tsx.snap
- src/features/HelpAndKnowledge/Articles/HighLevelProjectPlan/__snapshots__/index.test.tsx.snap
- src/features/HelpAndKnowledge/Articles/SixPagerMeeting/__snapshots__/index.test.tsx.snap
- src/features/HelpAndKnowledge/Articles/SixPagerMeeting/index.tsx
- src/features/HelpAndKnowledge/Articles/TwoPagerMeeting/__snapshots__/index.test.tsx.snap
- src/features/HelpAndKnowledge/Articles/TwoPagerMeeting/index.tsx
- src/features/HelpAndKnowledge/Articles/_components/ExternalResourceCard/__snapshots__/index.test.tsx.snap
- src/features/HelpAndKnowledge/Articles/_components/KeyResourcesCards/index.tsx
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/About/__snapshots__/index.test.tsx.snap
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Timeline/__snapshots__/index.test.tsx.snap
- src/features/ModelPlan/CRTDL/CRTDLs/__snapshots__/index.test.tsx.snap
- src/features/ModelPlan/CRTDL/CRTDLs/index.tsx
- src/features/ModelPlan/CollaborationArea/Cards/cards.scss
- src/features/ModelPlan/ReadOnly/CRTDLs/__snapshots__/index.test.tsx.snap
- src/features/ModelPlan/TaskList/Basics/Milestones/__snapshots__/index.test.tsx.snap
There were some weirdness introduced to the External Link component from a recent merge conflict. This PR is to address said weirdness. Additionally, some code refactor in the `KeyResource` component in the 2 and 6 pager help article
1.  Checkout branch and look through app to ensure things match figma
2. Check the key resource component matches figma in the 2 and 6 pager help article …
> [NOREF] Addressing some weird styles introduced in recent merge conflict

- src/features/HelpAndKnowledge/Articles/AllArticles/__snapshots__/index.test.tsx.snap
- src/features/HelpAndKnowledge/Articles/_components/ArticleCard/index.scss
- src/features/HelpAndKnowledge/Articles/_components/ArticleCard/index.tsx
- src/features/HelpAndKnowledge/Articles/_components/ExternalResourceCard/__snapshots__/index.test.tsx.snap
- src/features/HelpAndKnowledge/Articles/_components/ExternalResourceCard/index.tsx
- src/features/ModelPlan/TaskList/Beneficiaries/BeneficiaryIdentification/index.test.tsx
When clicking `Read more` on the truncated text, not all the text was being shown do to an class on the card body.  Removed this class on the external link cards to allow the full text to be shown.
1.  Verify the full text is shown on external link card in help center when `Read more` is clicked …
> [NOREF] Extend help truncated text

- pkg/graph/resolvers/model_plan_phase_test.go
- Updates tests to use absolute dates (`time.Now().Add(...)` instead of `time.Date(...)`)
1.  Ensure CI/CD tests pass - shouldn't require any other tests!
> [NOREF] Fix strategy evalutaion / phase tests to use relative dates

- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Timeline/__snapshots__/index.test.tsx.snap
- src/features/HelpAndKnowledge/SolutionsHelp/solutionsMap.tsx
- src/i18n/en-US/helpAndKnowledge/helpAndKnowledge.ts
1.  Verify the changes match the expected [state](https://docs.google.com/document/d/1AGXEbYxgiW8v-KwzLJ3Iz-NgGfwIrXKyfxiXZxG9yaw/edit) from [figma](https://www.figma.com/design/dzzLdDf6UwkLA51BtoAt3T/MINT---Knowledge-Center?node-id=8354-31446&node-type=frame&t=ruDK8hQonLt9DMzb-0).
- Don't be afraid to leave comments or ask questions, especially if you don't understand why something was done! (This is often a great time to suggest code comments or documentation …
> [MINT-3054] Model Space solution bug fix

- .envrc
- .vscode/settings.json
- docker-compose.backend.yml
- pkg/appconfig/config.go
- pkg/echimpcache/echimp_cache.go
1. Make echimp cache time be an env var
2. make it configurable to a minute. 
3. If time is less than or = to 0, the cache is disabled.
1.  bring up the app.
2. Seed the data
3. Ensure that you can fetch echimp data
4. If desired, change the cache time and validate again
- Check …
> [MINT-3185] Configurable Echimp Cache time

- cypress/e2e/modelPlan.spec.js
- cypress/e2e/notification.spec.js
- cypress/e2e/webSocket.spec.js
- cypress/plugins/index.js
Addressing https://github.com/CMS-Enterprise/mint-app/pull/1453#issuecomment-2447838216
* Removed "only" in one of the tests in the `notification.spec.js` file
* Refactored the model status test and moved it to `modelpan.spec.js` 
1.  run cypress and ensure tests pass
- Check …
> [NOREF] Addressing e2e test failures that were hidden with "only" 

- .github/workflows/check_migrations.yml
- Updates `.github/workflows/check_migrations.yml` to only run when a PR targets main
This helps cut down on the number of failing jobs that we see when operating in feature branches (which often update/edit migrations _before_ they hit `main`)
> [!NOTE]
> Here's the [GitHub actions documentation](https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#running-your-pull_request-workflow-based-on-the-head-or-base-branch-of-a-pull-request) for this modification!
1.  Ensure that the modification matches the documentation -- otherwise, we just have to wait for this to hit `main` before we can really test it practically!
- When approving a …
> [NOREF] Only run 'Check Migrations' job when PR targets main

- src/components/CRAndTDLSidePanel/index.tsx
- src/components/EChimpCards/EChimpCard.test.tsx
- src/components/EChimpCards/EChimpCard.tsx
- src/components/EChimpCards/EChimpCardsTable.tsx
https://cmsgov.slack.com/archives/C06J1SCLFT3/p1730832467275259
1.  Update the ID for a TDL in React Developer Tools
2. Verify that the URL for this TDL card remains to say `...sysSelect=TDL...`
- Check that all code is adequately covered by tests - if it isn't feel free to …
> [NOREF] Updating TDL Echimp URL

- .github/workflows/mto_dev_deploy.yml
- Create deploy pipeline for MTO branch to DEV
1.  push to `feature/MINT-3175_mto`
2. branch will automatically deploy to dev
> MINT-3202: Create deploy pipeline for MTO branch to DEV

- MINT.postman_collection.json
- cmd/dbseed/mto.go
- migrations/V182__Add_MTO_Common_Milestone.sql
- pkg/graph/resolvers/mto_milestone.go
- pkg/graph/resolvers/mto_milestone.resolvers.go
- pkg/graph/schema/types/mto_milestone.graphql
- pkg/storage/mto_milestone.go
- src/gql/generated/graphql.ts
- Removes the existing `createMTOMilestone` mutation in favor of 2 mutations based on _how_ the Milestone is being added (Custom, or from the Common Milestone Library)
> [!NOTE]
> This PR introduces a few `TODO` comments, most of which relate to the fact that we need to confirm & build out functionality to automatically create MTO Categories when adding from the Common Milestone Library
- Use the updated postman collection on a model plan - `createMTOMilestoneCustom` and `createMTOMilestoneCommon` are now part of the collection! (Functionally, they were both there before, but now they use the new mutations
- e.g. "Approving …
> [NOREF] Split create milestone mutation

- src/features/ModelPlan/DataExchangeApproach/CollectingAndSendingData/index.tsx
- Added optionsLabel/sublabel to DEA 2nd page multiselect
1.  Navigate to page 2 of DEA and ensure it matches [Figma](https://www.figma.com/design/qXhO12xSSkDF4LaToGKJoV/MINT-Blue-Sky-Ideas?node-id=3027-28714&node-type=instance&t=gfRFO0ffWjhmiA4e-0) …
> [MINT-3193] Added sublabel to multiselect for DEA

- pkg/graph/resolvers/mto_milestone.go
- pkg/sqlqueries/SQL/mto/category/create_allow_conflicts.sql
- pkg/sqlqueries/mto_category.go
- pkg/storage/mto_category.go
- Automatically creates categories and subcategories as-needed when adding Milestones from the Common Milestone library (via the `createMTOMilestoneCommon` mutation)
1.  `scripts/dev up:backend`
2. Create a Model Plan
3. Using Postman, create a MTO Milestone from the Common Milestone Library
4. Using Postico or Postman, query the MTO Category table to ensure that the proper category and subcategory were created.
Additionally, feel free to test out the `insert / return on conflict` logic by:
1. Deleting the Milestone and re-adding it
a. ensuring that the same Categories remain in the DB and are linked to the milestone
2. Deleting the subcategory _and_ the milestone and re-adding it
b. ensuring the milestone will get created and linked to the new subcategory (and the existing parent …
> [MINT-3219] Create categories automatically

- .envrc
- CONTRIBUTING.md
I noticed the contributing markdown was still referencing EASI. I updated the references to use MINT instead. I didn't change any content except for the prefix
Read the markdown and look for any places where EASI still exists.
- Check that all code is adequately covered by tests …
> [NOREF] replace references to EASI prefix for branch name to MINT

- .pre-commit-config.yaml
- Dockerfile
- go.mod
- pkg/accesscontrol/access_control.go
- pkg/graph/resolvers/apply_changes.go
- pkg/models/analyzed_audit.go
- tools.go
> [!IMPORTANT]
> You'll want to make sure you've installed go v1.23.4 locally before testing these changes!
1.  Ensure the app builds properly with `scripts/dev up`
2. Ensure linting works with `pre-commit run --all-files` (shouldn't result in any changes locally)
- Check that …
> [NOREF] Upgrade go from 1.22.3 to 1.23.4

- migrations/V181__Add_MTO_Category.sql
Migrations were failiing in the deploy pipeline. Likely because a collation isn't dropped with DB clean. To address this, we just add a DROP if exists method in the migration. 
Future enhancements might look at dropping collations as part of DB clean, but this is the simplest solution for now
1.  Verify tests pass. The true test is if the deploy pipeline functions as expected. …
> [Noref] collation migration fix

- src/features/ModelPlan/ModelToOperations/Home/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/ActionsTable/index.test.tsx
- src/features/ModelPlan/ModelToOperations/_components/ActionsTable/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/AddCustomCategoryForm/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/AddCustomMilestoneForm/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/AddCustomSolutionForm/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/EditCategoryTitleForm/index.tsx
* Refetch was being called on modal closure, causing unnecessary refreshes to the matrix
* Moved to when the create/rename mutations are successfully called
1.  Navigate to MTO Matrix
2. Repeated open and close the edit category title
3. ensure no matrix flicker
4. actually rename the title and see matrix reload
- Don't be afraid to leave comments or ask questions, especially if you don't understand why something was done! (This is often a great time to suggest code …
> [NOREF] Move Refetch to the create/rename mutation, not closing modal

- pkg/email/templates/model_plan_suggested_phase_body.html
#NOREF
https://cmsgov.slack.com/archives/C04B10ZN6A2/p1735647002985219
- Fixed link where suggested status in emails was not targeting the parent collaboration area route
1.  Trigger email to suggest status update and verify link works as expected …
> [NOREF] Fixed status link for emails

- src/contexts/MTOModalContext/index.tsx
- src/features/ModelPlan/ModelToOperations/Home/index.tsx
- src/features/ModelPlan/ModelToOperations/MilestoneLibrary/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/ActionsMenu/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/ActionsTable/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/AddCustomCategoryForm/__snapshots__/index.test.tsx.snap
- src/features/ModelPlan/ModelToOperations/_components/AddCustomCategoryForm/index.test.tsx
- src/features/ModelPlan/ModelToOperations/_components/AddCustomCategoryForm/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/AddCustomMilestoneForm/index.test.tsx
- src/features/ModelPlan/ModelToOperations/_components/AddCustomMilestoneForm/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/AddCustomSolutionForm/index.test.tsx
- src/features/ModelPlan/ModelToOperations/_components/AddCustomSolutionForm/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/AddTemplateModal/__snapshots__/index.test.tsx.snap
- src/features/ModelPlan/ModelToOperations/_components/AddTemplateModal/index.test.tsx
- src/features/ModelPlan/ModelToOperations/_components/AddTemplateModal/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/EditCategoryTitleForm/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/EditMilestoneForm/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/FormModal/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/MilestoneCard/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/MilestonePanel/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/MoveSubCategoryForm/__snapshots__/index.test.tsx.snap
- src/features/ModelPlan/ModelToOperations/_components/MoveSubCategoryForm/index.test.tsx
- src/features/ModelPlan/ModelToOperations/_components/MoveSubCategoryForm/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/OptionPanel/__snapshots__/index.test.tsx.snap
- src/features/ModelPlan/ModelToOperations/_components/OptionPanel/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/RemoveCategoryForm/index.test.tsx
- src/features/ModelPlan/ModelToOperations/_components/RemoveCategoryForm/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/Table/index.tsx
- src/hooks/useFormatMTOCategories.ts
- src/i18n/en-US/modelPlan/modelToOperations.ts
This brach has https://github.com/CMS-Enterprise/mint-app/pull/1583 pulled into it, in order to unblock.  Can deisregard the changes related to this pr until it gets merged
- Added component to render confirmation modal when adding a template
- Hooked up custom milestone and solution forms on empty states
- Refactored the `MTOModal`
- Hoisted the rendered component to be used outside the scope of the `ActionTable`
- Unit tests
1.  Matches Figma
2. Code refactor looks good an makes sense - can pair on changes
- e.g. "Approving because the …
> [MINT-3243] Empty states and modal refactor

- src/features/Home/components/ModelsBySolutions/__snapshots__/index.test.tsx.snap
- src/features/Home/components/ModelsBySolutions/banner.tsx
Fixed misaligned margin on the button group on the home page
Updated snap
https://oddball.slack.com/archives/C06RF2Q327R/p1736278427387229
1.  Button group text is aligned with numbers
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the …
> [NOREF] Fixed misaligned margin on home page

- src/features/ModelPlan/ModelToOperations/_components/EditCategoryTitleForm/index.tsx
Fixed issue where updating a category name from the matrix was allowing an empty string as a valid UUID
1.  Verify can update both a category and subcategory from MTO matrix
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the addition of …
> [NOREF] Fix category title update

- src/components/Sidepanel/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/AddTemplateModal/__snapshots__/index.test.tsx.snap
- src/features/ModelPlan/ModelToOperations/_components/SelectSolutionForm/__snapshots__/index.test.tsx.snap
- src/features/ModelPlan/ModelToOperations/_components/SelectSolutionForm/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/SolutionCard/index.tsx
- src/i18n/en-US/modelPlan/modelToOperations.ts
- Fixed help center modal disabling scroll once closed
- Fixed discrepancy on MTO template count
- Fixed select solution modal count text when 0
1.  Verify help center side panel behaves as expected in both help center and MTO, scrolling works when closed
2. Button text on select solutions is correct …
> [NOREF] Fix modal scroll bug

- MINT.postman_collection.json
- pkg/graph/resolvers/mto_solution.go
- pkg/graph/resolvers/mto_solution.resolvers.go
- pkg/graph/resolvers/mto_solution_test.go
- pkg/graph/schema/types/mto_solution.graphql
- pkg/sqlqueries/SQL/mto/solution/delete.sql
- pkg/sqlqueries/mto_solution.go
- pkg/storage/loaders/mto_milestone.go
- pkg/storage/mto_solution.go
- pkg/translatedaudit/translate_foreign_key.go
- pkg/translatedaudit/translated_audit_meta_data.go
- pkg/translatedaudit/translated_audit_meta_data_test.go
- pkg/translatedaudit/translated_audit_suite_test.go
- pkg/translatedaudit/translated_audit_suite_utils_test.go
- src/gql/generated/graphql.ts
1. Meta Data for MTO Solution and Milestone
a. uses generic to return names
2.  Meta Data updates for MTO Category
a. allow data to be nullable as it can be deleted between fetching and we need to account for it
3. Add ability to delete a solution
1.  Ensure unit tests pass
2. Ensure meta data looks as expected (make some audits for solution and milestone)
3. If desired, delete a solution …
> [NOREF] Meta data for mto solution and mto milestone

- pkg/models/mto_category.go
- pkg/translatedaudit/translate_foreign_key.go
- pkg/translatedaudit/translate_foreign_key_test.go
- pkg/translatedaudit/translated_audit_meta_data.go
- pkg/translatedaudit/translated_audit_meta_data_test.go
- pkg/translatedaudit/translated_audit_suite_utils_test.go
- pkg/translatedaudit/translated_audit_utils.go
1. This updated foreign key translations to show data not available if data is deleted before being translated. It will still fail if there is an unexpected error (so it can be retried)
2. Updates to category foreign key rendering to always show Uncategorized as well if it is a primary category.
1.  Make some Milestones, solutions and Categories and links
2. Delete them before translating.
3. Translate the data
4. Ensure that the translations still come through for deleted data
Verify that the new unit tests make sense
- e.g. "Approving …
> [NOREF] Support deletable foreign key translations for Change History

- migrations/V189__Add_MTO_Category_Reorder_Trigger.sql
#NOREF
1. With auditing enabled, you were not able to delete records that weren't already modified.
2. To correct this, the reorder trigger had to look for the deleted by user set in a session variable in app code.
1.  Use the standard template to make categories
2. Delete an unmodified category
3. Ensure you are allowed to delete it
- Don't be afraid to leave comments or ask questions, especially if you don't understand why something was done! (This is often a great …
> [NOREF]category reorder update for delete

- pkg/translatedaudit/translate_foreign_key.go
- pkg/translatedaudit/translate_foreign_key_test.go
- src/features/ModelPlan/ChangeHistory/components/BatchRecord/index.tsx
A Nil category means it is uncategorized, this updates Change history to match
1.  Make a milestone that is categorized.
2. Delete the parent category, make sure the new category shows `Uncategorized (Uncategorized)`
3.  Change to a new category, make sure that the data shows a previous translation of `Uncategorized (Uncategorized)` (not this currently doesn't show up in the front end, it might require a code change to show nil translated valued for category)
- Don't …
> [NOREF] Nil category to Uncategorized translaltion

- src/features/ModelPlan/ChangeHistory/index.tsx
- src/features/ModelPlan/ModelToOperations/MilestoneLibrary/index.tsx
- src/features/ModelPlan/ModelToOperations/SolutionLibrary/_components/AddToExistingMilestoneForm/__snapshots__/index.test.tsx.snap
- src/features/ModelPlan/ModelToOperations/SolutionLibrary/_components/AddToExistingMilestoneForm/index.test.tsx
- src/features/ModelPlan/ModelToOperations/SolutionLibrary/_components/AddToExistingMilestoneForm/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/MatrixTable/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/MilestoneCard/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/MilestonePanel/index.tsx
- src/gql/generated/graphql.ts
- src/gql/operations/ModelToOperations/GetMTOAllMilestones.ts
- src/tests/mock/mto.ts
Quickly addressed the UX findings per post meeting sync with Zoe
- Fixed the double modal render when adding solutions to a milestone from the side panel of the milestone library
- Fixed adding existing milestones to a solution from the solution library
- Fixed incorrect modal opening from the milestone library when selecting to add a custom milestone from the info alert
- Added category and subcategory to search results from milestone library
- Added a top border to matrix rows
- Fixed CH icon color on back link
1.  Verify UX changes a re accurately fixed
- e.g. "Approving because I tested it locally and all functionality works …
> [NOREF] Address UX findings

- pkg/graph/resolvers/mto.go
1. This [PR](https://github.com/CMS-Enterprise/mint-app/pull/1653/files?diff=split&w=0#diff-a6eff7337528d456f5afb577b939095791cdd28c2c81e9c5e7870e8ceebdbd0a) made MTO status calculations dependant on change history, which can result into up to 1 minute delay
2. This PR reintroduces the MTOLastUpdated, but also adds on reference to the mto solution
3. The recent edit field still relies on change history to provide more detailed information
1.  Seed the DB
2. Go to an empty model
3. Ensure the MTO status is Ready to Start
4. Add a Solution
5. Ensure status is now in progress
6. Mark Ready for Review
7. Status should be ready for review
- When approving a PR, provide a reason _why_ you're …
> [MINT-3333] MTO status not dependant on change history.

- pkg/email/templates/model_plan_share_subject.html
- pkg/models/model_plan.go
It was noted that there were a few changes that needed to be made to the email template to update terminology for sharing a model plan.
1.  Share a model plan, verify the email matches [figma](https://www.figma.com/design/BcI7pNwfkmwaDD2EGGTsYC/IT-Lead?node-id=6878-110353&t=TZLJZIFGYVtiSnsN-0) …
> [NOREF] Share Model Plan email fixes

- src/features/HelpAndKnowledge/Articles/CreatingMTOMatrix/__snapshots__/index.test.tsx.snap
- src/features/HelpAndKnowledge/Articles/CreatingMTOMatrix/index.test.tsx
- src/features/HelpAndKnowledge/Articles/CreatingMTOMatrix/index.tsx
- src/features/HelpAndKnowledge/index.tsx
- src/i18n/en-US/helpAndKnowledge/Articles/creatingMtoMatrix.ts
- Added copy and render components for `Creating your Model-to-operations matrix (MTO) in MINT`
- Added unit test
Note: the MTO tutorial links at the bottom are ordered alphabetically due to the listed array, except for Starting MTO. Checking with UX to see if this is okay as it doesnt quite match Figma
1.  Verify matches https://www.figma.com/design/dzzLdDf6UwkLA51BtoAt3T/MINT---Knowledge-Center?node-id=8909-16630&t=d59tc23d3qThX0Gl-0
- Don't be afraid to leave …
> [MINT-3342] Create MTO help article

- src/features/ModelPlan/ModelToOperations/_components/SuggestedMilestoneToggle/index.tsx
Noticed that answers that trigger a sigguested milestone that were multiselect we always rendering as `No answer`
- Fixes bug so all multiselect answers are shown
1.  Navigate to page 3 of `Operations, evaluation, and learning` and select multiple answers
2. Answer helpdesk question on page 1 of `Operations, evaluation, and learning`
Verify both type render correctly as the suggested cards in MTO
- Don't be afraid to leave comments or ask questions, especially if you …
> [NOREF] Fix suggested answer mto

- src/features/ModelPlan/ModelToOperations/SolutionLibrary/_components/AddToExistingMilestoneForm/__snapshots__/index.test.tsx.snap
- src/features/ModelPlan/ModelToOperations/SolutionLibrary/_components/AddToExistingMilestoneForm/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/AddCommonMilestoneForm/__snapshots__/index.test.tsx.snap
- src/features/ModelPlan/ModelToOperations/_components/AddCommonMilestoneForm/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/SelectSolutionForm/__snapshots__/index.test.tsx.snap
- src/features/ModelPlan/ModelToOperations/_components/SelectSolutionForm/index.tsx
- src/i18n/en-US/modelPlan/modelToOperations.ts
- Add bold labels for selected milestone and selected solution in relevant modals for better user clarity 
- Update i18n strings with selectedMilestone and selectedSolution keys to support translation 
- Enhance form UIs (AddToExistingMilestoneForm, AddCommonMilestoneForm, SelectSolutionForm) to include the selected entity above the modal description 
- Improve snapshot tests to reflect the new labeled content in the DOM structure
1. Seed and go to the MTO Matrix and click to add solution and verify that the "Selected milestone" matches
2. Nav to common milestone library, click to add, and verify that the "Selected milestone" matches
3. Nav to common solutions libary, click to add, and verify that the "Selected solution" matches 
- It's best to pull the branch locally and test it, rather …
> [MINT-3360] Adding Milestone/Solution label to modals

- cypress/e2e/mto.spec.js
- src/components/Sidepanel/__snapshots__/index.test.tsx.snap
- src/components/Sidepanel/index.tsx
- src/contexts/EditMTOMilestoneContext/index.tsx
- src/contexts/EditMTOSolutionContext/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/EditMilestoneForm/__snapshots__/index.test.tsx.snap
- src/features/ModelPlan/ModelToOperations/_components/EditMilestoneForm/index.test.tsx
- src/features/ModelPlan/ModelToOperations/_components/EditMilestoneForm/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/EditSolutionForm/__snapshots__/index.test.tsx.snap
- src/features/ModelPlan/ModelToOperations/_components/EditSolutionForm/index.test.tsx
- src/features/ModelPlan/ModelToOperations/_components/EditSolutionForm/index.tsx
- src/features/ModelPlan/ModelToOperations/index.scss
- src/stylesheets/custom.scss
Was a bit of a headache to implement in its current structure, but managed to achieve the desired UX outcome for sticky header and footer for these panels.  
1.  Sticky header and footer for both solution and milestone edit panels
Leaving out readview panels at least for now
- …
> [MINT-3361] Sticky header footer panels

- src/app/Routes/index.tsx
- src/contexts/EditMTOMilestoneContext/index.tsx
- src/features/ModelPlan/CollaborationArea/Cards/MTOCard/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/ActionsTable/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/AddCustomMilestoneForm/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/AddCustomSolutionForm/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/LinkMilestoneForm/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/LinkSolutionForm/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/SelectSolutionForm/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/SuggestedMilestoneBanner/index.tsx
- src/hooks/useScrollTop.ts
- src/utils/scrollConfig.ts
- Refactored scroll functionality to it's own hook
- Added ability to manually scroll by passing state to location
This work added a no scroll functionality across all of MTO, due to most routes utilizing query parameters.  For the few instances where we want to force scroll to the top, I've passed state to the location.
1.  Verify pages scroll and dont scroll where they need to in MTO …
> [NOREF] Scroll refactor MTO - QA

- src/components/ExternalDocumentLink/index.tsx
https://oddball.slack.com/archives/C059QQA3HK5/p1747067664290199
- Fixed issue where `<ExternalLink />` was embedded within `<ExternalDocumentLink />`, causing a double modal render
1.  Follow instructions in slack to try to replicate and validate issue is resolved
- Check that …
> [NOREF] Fixed external link modal

- pkg/translatedaudit/translated_audit_meta_data.go
The code failed when auditing change history records for milestones and solutions that were deleted. This was because it was looking for fields specific to a custom entry, not ones sourced from the common librarys.
1.  Make and delete a milestone and solution from the common library.
2. Make sure that they have entries listed when you delete the records.
- Don't be afraid to leave comments or ask questions, especially if you don't understand why something was done! …
> [NOREF] mto change history fix

- src/features/ModelPlan/ModelToOperations/_components/AddTemplateModal/__snapshots__/index.test.tsx.snap
- src/features/ModelPlan/ModelToOperations/_components/AddTemplateModal/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/MatrixTable/index.tsx
- Fixed model height on Add Template modal
- Alphabetized milestones within the matrix
- Updated snap
1.  Verify Add template modal height allows for all content to be displayed
2. Verify any milestone within the matrix is correctly alphebetized …
> [NOREF] - Sort milestones, fix template modal height

- mappings/translation/mto_solution.json
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/BCDA/index.tsx
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/Generic/about.tsx
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Timeline/__snapshots__/index.test.tsx.snap
- src/features/ModelPlan/ModelToOperations/SolutionLibrary/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/EditSolutionForm/__snapshots__/index.test.tsx.snap
- src/features/ModelPlan/ReadOnly/MTOSolutions/SolutionPanel/__snapshots__/index.test.tsx.snap
- src/i18n/en-US/helpAndKnowledge/helpAndKnowledge.ts
- src/i18n/en-US/modelPlan/mtoSolution.tsx
- Fixed # 5, 8 - Help solution links, risk indicator capitalization
1.  Verify fixes address QA
> [NOREF] Additional must have fixes # 5, 8

- pkg/email/templates/mto_solution_selected_body.html
Updated empty state to be italicized, and increased email spacing
Testable with postman
1.  Make a model plan
2. Make a common solution
Look at the resulting email and verify it is updated correctly.
- Check that all code is adequately covered by tests - if it isn't feel free to …
> [NOREF] QA Fix 97 for solution selected emails

- mappings/translation/mto_solution.json
- src/features/HelpAndKnowledge/Articles/CreatingMTOMatrix/__snapshots__/index.test.tsx.snap
- src/features/HelpAndKnowledge/Articles/CreatingMTOMatrix/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/LinkMilestoneForm/__snapshots__/index.test.tsx.snap
- src/features/ModelPlan/ModelToOperations/_components/LinkMilestoneForm/index.test.tsx
- src/features/ModelPlan/ModelToOperations/_components/LinkMilestoneForm/index.tsx
- src/i18n/en-US/modelPlan/changeHistory.ts
- src/i18n/en-US/modelPlan/modelToOperations.ts
- src/i18n/en-US/modelPlan/mtoSolution.tsx
QA fixes # 76 and 78. 
FIx help article content
1.  Verify fixes address issues in QA doc
> [NOREF] - QA fixes # 76 and 78

- src/components/ShareExport/index.tsx
- src/hooks/useFetchCSVData.tsx
- Added filename to csv and pdf export
- Single model plan -> `MINT-My_Model_Plan-OACT.csv`
- Format - `MINT` - `model plan name` - `section`
- All model plans
Note we arent translating the sections, need to check if that's okay or if enum/abbreviations are fine
1.  Download a model plan with both csv and pdf and verify correct name
- Don't be afraid to leave comments or ask questions, especially if you don't understand why something was done! (This is often a great …
> [NOREF] Add filename to csv and pdf export

- cypress/e2e/notification.spec.js
- src/features/Notifications/Home/_components/IndividualNotification.tsx
- src/i18n/en-US/notifications.ts
- Added the user's name to the date notification component in the notification center
1. Navigation to the notifcation center settings
2. Select to opt in for notifications when dates change and save
3. Add a date to the model plan
- Collab area -> Task list -> Model Basics -> Page 3
4.  Wait for notification to appear
5. Verify user name rendered in component
- Don't be afraid to leave comments or ask questions, especially if you don't understand why something was …
> [MINT-3268] Added user name to notification

- cypress/e2e/modelPlan.spec.js
- cypress/fixtures/flagdata.json
- pkg/flags/client.go
- pkg/graph/resolvers/model_plan.go
- pkg/graph/resolvers/model_plan.resolvers.go
- pkg/graph/resolvers/model_plan_test.go
- pkg/server/config.go
- src/app/Routes/index.tsx
- src/components/CRAndTDLSidePanel/__snapshots__/index.test.tsx.snap
- src/components/CRAndTDLSidePanel/index.test.tsx
- src/components/CRAndTDLSidePanel/index.tsx
- src/components/EChimpCards/EChimpCard.tsx
- src/components/EChimpCards/__snapshots__/EChimpCard.test.tsx.snap
- src/components/EChimpCards/__snapshots__/EChimpCardsTable.test.tsx.snap
- src/components/NavigationBar/index.test.tsx
- src/components/NavigationBar/index.tsx
- src/features/ModelPlan/CRTDL/CRTDLs/__snapshots__/index.test.tsx.snap
- src/features/ModelPlan/CRTDL/CRTDLs/index.tsx
- src/features/ModelPlan/ReadOnly/CRTDLs/__snapshots__/index.test.tsx.snap
- src/features/ModelPlan/ReadOnly/CRTDLs/index.tsx
- src/features/ModelPlan/TaskList/_components/TaskListSideNav/__snapshots__/index.test.tsx.snap
- src/features/ModelPlan/TaskList/_components/TaskListSideNav/index.tsx
- src/types/flags.ts
- src/utils/tests/user.test.ts
- src/wrappers/FlagsWrapper/index.tsx
- Removed unused/legacy flags that were causing issues with cypress
- Removed echimp BE LD config
- Updated cypress dates
There were dates set in the `modelPlan` cypress test that were in the past.  This cause a status update modal to trigger and hide necessary components to test the suite.  This pushed those dates very far into the future.
1.  Verify cypress tests now pass …
> [NOREF] Fixed cypress past dates/status trigger, removed unused flags

- src/features/ModelPlan/ReadOnly/_components/StatusBanner/index.tsx
- src/i18n/en-US/modelPlan/changeHistory.ts
…and update display string]
When clicking on a model’s “View change history” link in the read view, the go back button incorrectly says “Back to the model collaboration area”. That link is fine for when navigating to change history from the collab area as a model team member, but I don’t think we want it saying that for our read-only users as they won’t know what the collab area is.
As read only user, I should see 'Back to model information' (previously as 'Back to the Read view") when viewing change history.
After fix:
https://github.com/user-attachments/assets/258cd76e-ccc5-42e1-9bc4-2eff8690112b
1.  login as a read only user
2. nav to change history
3. verify back button should display 'Back to model information' 
- It's best to pull the branch locally and test it, rather than just …
> [MINT-3388 ]Fix go back from change history display incorrect wording

- src/i18n/en-US/helpAndKnowledge/Articles/addCustomMilestone.ts
- src/i18n/en-US/helpAndKnowledge/Articles/addCustomSolution.ts
- src/i18n/en-US/helpAndKnowledge/Articles/sharingExportingMto.ts
- src/i18n/en-US/helpAndKnowledge/Articles/startingMto.ts
- src/i18n/en-US/helpAndKnowledge/Articles/usingSolutionLibrary.ts
Few help articles are missing bread crumbs translation. Fixed in this pr.
Articles include: 
- How to add a custom milestone
- How to add a custom solution
- Sharing and exporting your MTO
- Starting an MTO for a new model
- Using the solution library
1.  verify above mentioned articles(or all tutorials) now have breadcrumbs when rendering.
- Don't be afraid to leave comments or ask questions, especially if you don't understand why something was done! (This is often a …
> [NOREF] Add missing help articles breadcrumbs

- mappings/translation/mto_milestone.json
- migrations/V208__Add_Shell_Solutions.sql
- pkg/graph/schema/types/mto_common_solution.graphql
- pkg/models/mto_common_solution.go
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/About/__snapshots__/index.test.tsx.snap
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/PointsOfContact/__snapshots__/index.test.tsx.snap
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/Generic/about.tsx
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Timeline/__snapshots__/index.test.tsx.snap
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/_components/GatheringInfoAlert/index.tsx
- src/features/HelpAndKnowledge/SolutionsHelp/_components/CategoryFooter/__snapshots__/index.test.tsx.snap
- src/features/HelpAndKnowledge/SolutionsHelp/_components/SolutionCategories/__snapshots__/index.test.tsx.snap
- src/features/HelpAndKnowledge/SolutionsHelp/_components/SolutionHelpCard/__snapshots__/index.test.tsx.snap
- src/features/HelpAndKnowledge/SolutionsHelp/_components/SolutionHelpCard/index.tsx
- src/features/HelpAndKnowledge/SolutionsHelp/_components/SolutionHelpCardGroup/__snapshots__/index.test.tsx.snap
- src/features/HelpAndKnowledge/SolutionsHelp/_components/SolutionHelpCardGroup/index.test.tsx
- src/features/HelpAndKnowledge/SolutionsHelp/_components/SolutionHelpCardGroup/index.tsx
- src/features/HelpAndKnowledge/SolutionsHelp/_components/SolutionsHeader/__snapshots__/index.test.tsx.snap
- src/features/HelpAndKnowledge/SolutionsHelp/_components/SolutionsHeader/index.test.tsx
- src/features/HelpAndKnowledge/SolutionsHelp/solutionsMap.tsx
- src/gql/generated/graphql.ts
- src/i18n/en-US/helpAndKnowledge/helpAndKnowledge.ts
- src/i18n/en-US/modelPlan/mtoMilestone.tsx
- src/types/operationalSolutionCategories.ts
This feature covers both [MINT-3397](https://jiraent.cms.gov/browse/MINT-3397) and [MINT-3396](https://jiraent.cms.gov/browse/MINT-3396)
- Added migration for new solutions and new category
- Updated gql schema for enum changes
- Exported translation
- Added translations and config mapping for all solutions
- Added translation config `gatheringInfo` property to dynamically render alert
- Updated unit test
1.  Log into MINT and navigate to the help and knowledge center
2. For each solution [here in the figma](https://www.figma.com/design/dzzLdDf6UwkLA51BtoAt3T/MINT---Knowledge-Center?node-id=9273-11579&t=8nYZUo9MNYMeFWl7-0) verify the correct text, and render. 
3. Some solutions have both an alert and some content
4. PoC's should all be the same - MINT mailbox
5. At the category footer, …
> [Feature/MINT-3376] Shell solutions

- pkg/server/config.go
- pkg/server/routes.go
https://cmsgov.slack.com/archives/C038CMDFEBC/p1727793179911629?thread_ts=1727785544.091139&cid=C038CMDFEBC
MINT was getting slack alerts. every 15 min due to echimp config not existing for our dev env.  This PR removes the check for a dev echimp config.
Echimp data in dev will fail to fetch.  This will be addressed in a subsequent ticket - https://jiraent.cms.gov/browse/MINT-3414?atlLinkOrigin=c2xhY2staW50ZWdyYXRpb258aXNzdWU%3D
Can possible remove the dev `isLocal` check, not sure if that is really affecting anything any longer
1.  Verify tests pass
2. Log in a verify echimp data is present
3. Can log into the manually deployed instance in MINT dev and verify app runs but no echimp data fetch …
> [NOREF] Disable echimp bucket config for dev env

- .pre-commit-config.yaml
- pkg/graph/resolvers/mto_common_solution_contact.go
- pkg/sqlqueries/SQL/mto/common_solution_contact/unset_primary_key.sql
- pkg/storage/mto_common_solution_contact.go
noref
This PR enables setting isPrimary when creating a mailbox or user contact. All create operations are now wrapped in transactions to ensure only one primary contact exists per solution at any time. Additionally changed go-lint to point to local installation. 
1.  run create query for mailbox and for user account and set isPrimary to true
2. verify it is primary in database and that only 1 isPrimary exist per key 
- Don't be afraid to leave comments or ask …
> NOREF: createContact now can be a primary contact 

- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/About/__snapshots__/index.test.tsx.snap
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/Generic/about.tsx
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Timeline/__snapshots__/index.test.tsx.snap
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/_components/Header/__snapshots__/index.test.tsx.snap
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/_components/Header/index.tsx
…header text
https://oddball.slack.com/archives/C059QQA3HK5/p1751909787097199
Zoe noticed a few small UI tweaks to address in help and knowledge center
- Added `inlineText` prop to the external links in help center modal
- Fixed ghost space in category text of header
- Updated unit tests
1.  Verify the changes accurately address the findings in the linked slack thread above …
> [NOREF] Help Center - CDAC UI Tweaks

- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/PointsOfContact/__snapshots__/index.test.tsx.snap
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/Generic/PointsOfContact/__snapshots__/index.test.tsx.snap
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/Generic/PointsOfContact/index.tsx
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/Generic/_components/OwnerCard/__snapshots__/index.test.tsx.snap
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/Generic/_components/OwnerCard/index.test.tsx
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/Generic/_components/OwnerCard/index.tsx
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/Generic/_components/Owners/__snapshots__/index.test.tsx.snap
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/Generic/_components/Owners/index.test.tsx
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/Generic/_components/Owners/index.tsx
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/_components/GatheringInfoAlert/index.tsx
- src/features/HelpAndKnowledge/SolutionsHelp/solutionsMap.tsx
- src/i18n/en-US/helpAndKnowledge/helpAndKnowledge.ts
1. Update system owner/business owner section ui to match[ figma](https://www.figma.com/design/dzzLdDf6UwkLA51BtoAt3T/MINT---Knowledge-Center?node-id=8854-94504&t=l4hKurqI0Yn8RRmP-0)
2. Add test and snapshots
3. Edit and add models are not included in this pr
1.  verify the ui matches figma design …
> [Mint-3387] System owner contact card

- query_examples/MINT/Models to Operations Matrix/Common Solutions/ContactInfo/CreatebyMailbox MTO ContactInfo.bru
- query_examples/MINT/Models to Operations Matrix/Common Solutions/ContactInfo/CreatebyUser MTO ContactInfo.bru
- query_examples/MINT/Models to Operations Matrix/Common Solutions/ContactInfo/Delete MTO ContactInfo.bru
- query_examples/MINT/Models to Operations Matrix/Common Solutions/ContactInfo/Get MTO ContactInfo.bru
- query_examples/MINT/Models to Operations Matrix/Common Solutions/ContactInfo/Update MTO ContactInfo.bru
- query_examples/MINT/Models to Operations Matrix/Common Solutions/Contractor/CreateMTO Contractor.bru
- query_examples/MINT/Models to Operations Matrix/Common Solutions/Contractor/DeleteMTO Contractor.bru
- query_examples/MINT/Models to Operations Matrix/Common Solutions/Contractor/GetMTO Contractor.bru
- query_examples/MINT/Models to Operations Matrix/Common Solutions/Contractor/UpdateMTO Contractor.bru
…ther using variables
Updated the Bruno calls to include consistent variable styles and added support for chaining requests together using variables. 
1.  run the bruno calls for poc in query_examples/MINT/Models to Operations Matrix/Common Solutions/ContactInfo
2. run the bruno calls for contrcator in query_examples/MINT/Models to Operations Matrix/Common Solutions/Contractor …
> [NOREF] Bruno Enhancement for editable POC calls 

- cypress/downloads/MINT-Plan_with_Basics-TIMELINE.csv
- cypress/e2e/export.spec.js
Needed to update the plan used for export spec, since Timeline was introduced
- export spec now uses `Plan with Basics`
- Added test for `Model timeline` export section
1.  Cypress test passes
- Check that all code is adequately covered by tests - if it isn't feel free to suggest …
> [NOREF] Cypress export spec updates

- cmd/test_email/main.go
- cmd/test_email/mto_common_solution_contact_emails.go
- go.mod
- pkg/email/email_helper_methods.go
- pkg/email/mto_common_solution_system_owner_added.go
- pkg/email/mto_common_solution_system_owner_edited.go
- pkg/email/mto_common_solution_system_owner_removed.go
- pkg/email/template_service_impl.go
- pkg/email/templates/mto_common_solution_contractor_removed_subject.html
- pkg/email/templates/mto_common_solution_system_owner_added_body.html
- pkg/email/templates/mto_common_solution_system_owner_added_subject.html
- pkg/email/templates/mto_common_solution_system_owner_edited_body.html
- pkg/email/templates/mto_common_solution_system_owner_edited_subject.html
- pkg/email/templates/mto_common_solution_system_owner_removed_body.html
- pkg/email/templates/mto_common_solution_system_owner_removed_subject.html
- pkg/graph/resolvers/mto_common_solution_contractor.go
- pkg/graph/resolvers/mto_common_solution_system_owner.go
- pkg/graph/resolvers/mto_common_solution_system_owner_test.go
This PR adds email notifications for the "Add," "Edit," and "Remove" actions for system owners, ensuring that appropriate emails are sent during these operations. It also includes updates to the test suite to validate the email templates for each action.
1.  run ./scripts/dev email to create all the test emails and then verify structure of the emails in the mail catcher (http://0.0.0.0:1085/)
2. then run the create, update, and delete endpoints in the bruno and then check in mail catcher 
- e.g. "Approving because the change is simple and …
> [MINT-3432] added email functionality for system owner feature

- mappings/translation/mto_common_solution_contractor.json
- migrations/V210__MTO_Common_Solution_Contractor.sql
- pkg/graph/model/models_gen.go
- pkg/graph/schema/types/mto_common_solution_contractor_translation.graphql
- pkg/models/mto_common_solution_contractor.go
- pkg/sqlqueries/SQL/mto/common_solution_contractor/create.sql
- pkg/sqlqueries/SQL/mto/common_solution_contractor/delete.sql
- pkg/sqlqueries/SQL/mto/common_solution_contractor/get_by_common_solution_key.sql
- pkg/sqlqueries/SQL/mto/common_solution_contractor/get_by_id.sql
- pkg/sqlqueries/SQL/mto/common_solution_contractor/get_by_ids.sql
- pkg/sqlqueries/SQL/mto/common_solution_contractor/update.sql
- src/i18n/en-US/modelPlan/mtoCommonSolutionContractor.ts
> [NOREF] changed db name for contract title

- migrations/V210__Update_Common_Milestone_Solutions_MDM_POR_To_AMS.sql
https://cmsgov.slack.com/archives/C01B9TEC65A/p1753129846923269
For two of the milestones, we need to swap some common solutions
- Milestone: Manage and check provider overlaps
- Currently has MDM-POR as a common solution. We should remove that as a common solution and add AMS instead.
- Milestone: Manage and check beneficiary overlaps
- Currently has MDM-POR as a common solution. We should remove that as a common solution and add AMS instead.
No data should need to be migrated, just the suggested common solutions
1.  Navigate to miletstone library in MTO
2. Verify the common milestones are now AMS for both common milestones listed above
- When approving a PR, provide a reason _why_ you're …
> [MINT-3440] Replaced common solutions on common milestones

- .github/COPILOT_INSTRUCTIONS.md
- .github/COPILOT_REVIEW.md
- .pre-commit-config.yaml
- Added to markdown files to Github copilot
- `.spelling` was catching some obviously correct spellings, and even adding to the ignore list were still triggering.  The package is quite old (should look at a a replacement).  The only solution was to add the entire file in the ignore list in the precommit
COPILOT_REVIEW.md - Comprehensive codebase analysis document that:
- Documents your application's architecture, tech stack, and patterns
- Outlines established coding standards and conventions
- Serves as a reference for understanding the codebase structure
- Acts as onboarding documentation for new developers
COPILOT_INSTRUCTIONS.md - GitHub Copilot PR review configuration that:
- Provides specific instructions for automated PR reviews
- Defines what issues to flag (critical, major, …
> [NOREF] Github Copilot review instructions

- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/PointsOfContact/__snapshots__/index.test.tsx.snap
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/Generic/About/__snapshots__/index.test.tsx.snap
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/Generic/PointsOfContact/__snapshots__/index.test.tsx.snap
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/Generic/Timeline/__snapshots__/index.test.tsx.snap
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/Generic/_components/MailboxesAndTeamMembers/__snapshots__/index.test.tsx.snap
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/Generic/_components/MailboxesAndTeamMembers/index.tsx
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/Generic/_components/TeamMailboxForm/index.tsx
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/Generic/_components/TeamMemberForm/index.tsx
ref doc https://docs.google.com/document/d/1h68K8YmLiju9d2CUtgqZhhujOo9OjFlzTHd6NQnoMck/edit?tab=t.0#heading=h.cjvqou3lrx2k
1. Designating a POC as the Primary should shows “Does not receive notifications”. (Must fix-2)
2. Small screen stacking/spacing of headings and “+ Add” links are too tight (Should fix -2)
1.  create and/or update a contact poc as primary contact, poc card should show 'receive emails notification'
2. Verify “+ Add” section of contact poc is no longer tight when stacking on smaller screen
- e.g. "Approving because the …
> [NOREF] Fix primary not receive email

- mappings/translation/mto_common_solution_contractor.json
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/Generic/_components/ContractorForm/__snapshots__/index.test.tsx.snap
- src/i18n/en-US/modelPlan/mtoCommonSolutionContractor.ts
ref doc https://docs.google.com/document/d/1h68K8YmLiju9d2CUtgqZhhujOo9OjFlzTHd6NQnoMck/edit?tab=t.0#heading=h.yj341gx96x4f
Field name capitalization should match figma (Could fix-1)
1.  verify contractor modal field name matching figma
https://www.figma.com/design/dzzLdDf6UwkLA51BtoAt3T/MINT---Knowledge-Center?node-id=8854-94396&p=f&t=ZotN5gr74iSe9CNA-0
- Don't be afraid to leave comments or ask questions, especially if you don't understand why something was done! …
> [NOREF] Fix field name capitalization

- src/components/Modal/index.tsx
https://cmsgov.slack.com/archives/C01B9TEC65A/p1753884004462949
Zoe noticed an issue where the multiselect box wasnt scrollable.  
- Added overflow class to be visible instead of hidden for modal body content
1.  Navigate to MTO
2. Open any/all of the modals and verify the combobox and modal can be scrolled to the bottom
- Don't be afraid to leave comments or ask questions, especially if you don't understand why something was done! (This is often a great time to …
> [NOREF] Fix MTO modal scroll

- pkg/email/templates/added_as_collaborator_body.html
- pkg/email/templates/aggregated_daily_digest_body.html
- pkg/email/templates/daily_digest_body.html
- pkg/email/templates/data_exchange_approach_marked_complete_body.html
- pkg/email/templates/discussion_reply_created_originator_body.html
- pkg/email/templates/model_plan_created_body.html
- pkg/email/templates/model_plan_date_changed_body.html
- pkg/email/templates/model_plan_share_body.html
- pkg/email/templates/model_plan_suggested_phase_body.html
- pkg/email/templates/mto_solution_selected_body.html
- pkg/email/templates/plan_discussion_created_body.html
- pkg/email/templates/plan_discussion_tagged_solution_body.html
- pkg/email/templates/plan_discussion_tagged_user_body.html
- pkg/email/templates/report_a_problem_body.html
- pkg/email/templates/send_feedback_body.html
Link in email is not directing user accordingly, and that is because `clientAddress` is not being passed in correctly.
1.  
> [NOREF] Fix not linking correct client address issue

- pkg/email/report_a_problem.go
- pkg/email/send_feedback.go
- pkg/graph/resolvers/report_a_problem.go
- pkg/graph/resolvers/send_feedback_email.go
Recent header changes introduced a requirement for the client address field in “Send Feedback” and “Report a Problem” emails. These templates previously did not need the field, causing runtime issues.
This PR updates the email body structs to include the client address parameter and ensures it is properly passed through in code. This resolves the bug and restores expected behavior for affected emails.
1.  test email command ./scripts/dev email
- Don't be afraid to …
> added client address to send feedback and report a problem emails

- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/ChronicConditions/index.tsx
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/Generic/About/index.tsx
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/Generic/Timeline/__snapshots__/index.test.tsx.snap
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/HIGLAS/index.tsx
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Solutions/SharedSystems/index.tsx
- src/features/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Timeline/__snapshots__/index.test.tsx.snap
- src/features/HelpAndKnowledge/SolutionsHelp/solutionsMap.tsx
- src/i18n/en-US/helpAndKnowledge/helpAndKnowledge.ts
- Added prop on `LinksType` within HKC component to easily link to PoC page of solution detail
- Updated all solutions according to [Figma](https://www.figma.com/design/dzzLdDf6UwkLA51BtoAt3T/MINT---Knowledge-Center?node-id=9271-13642&t=NyxQKA0v4szsFDbz-0)
- Updated unit tests
1.  Navigate to HKC and verify all sensitive/PII contact info is updated according to Figma
- Don't be afraid to leave comments or ask questions, especially if you don't understand why something …
> [MINT-3442] Genericize operational solutions PoC

- src/features/HelpAndKnowledge/Articles/EvaluatingDataExchangeApproach/__snapshots__/index.test.tsx.snap
- src/i18n/en-US/helpAndKnowledge/Articles/evaluatingDataExchangeApproach.ts
https://cmsgov.slack.com/archives/C01B9TEC65A/p1756471563228899
- Fixed missing download link text for HKC
- Updated snap
1.  Navigate to `Evaluate your data exchange approach` and verify download link text is run through translation
- Check that all code is adequately covered by …
> [NOREF] Fixed hkc download link text

- src/features/Analytics/__snapshots__/index.test.tsx.snap
- src/features/Analytics/index.test.tsx
- src/features/Analytics/index.tsx
- src/features/Analytics/util.ts
`ChangesBySection` and `ChangesByOtherData` charts were not aggregating the sections and showing a cummulative total.  This PR adds util to massage the data for clear results
1.  Navigate to the /analytics route of seeded data and verify that that chart is intuitive to the data structure
- Don't be afraid to leave comments or ask questions, especially if you don't understand why something was done! (This is often a great time to suggest code comments or documentation …
> [NOREF] Analytics aggregate util for chart data

- src/features/ModelPlan/CollaborationArea/index.tsx
We recently noticed an edge case where it's possible to have a suggested phase/modal trigger, and the session variable would be stored for that model plan to persist that the user has already view this suggestion.  However if a new/different suggestion was triggered, the modal would not render, as it was not checking for a different suggested phase.  This PR now stores the value of the suggested phase and renders the modal if it is a new phase or if there is no session variable stored
1.  Create a new model plan (seeded data wont work)
2. Add a clearance date in the past
3. Go back to collab area
4. Suggested phase modal appears, close it
5. Navigate away and return.  Verify it does not reappear
6. Go back to timline and add the performance end date to also be in the past. 
7. Go back to …
> [MINT-3487] Updated session variable for suggested phase

- migrations/V222__Add_MTO_Template_Audit.sql
- migrations/V223__Add_MTO_Template_tables.sql
This adds the migrations for mto template changes based on this lucidchart https://lucid.app/lucidchart/04b274b3-dbf3-430a-b70d-6ac3cbf07c0d/edit?beaconFlowId=0E4691DB4DC41DCE&invitationId=inv_d47f9f03-36c9-4bfc-ab8d-adc930f39bce&page=0_0# 
1.  run app
2. open postico or db viewer of choice and compare structure and DDL to lucidchart 
- Don't be afraid to leave comments or ask questions, especially if you don't understand why something was done! (This is often a great …
> MINT-3473: added migrations for mto template tables

- pkg/email/templates/model_plan_suggested_phase_body.html
> NOREF fix incorrect email template

- src/features/HelpAndKnowledge/SolutionsHelp/index.tsx
- Added reset to page 1 when query changes
1. Go to HKC
2. Search for "grant". Notice it finds "GrantSolutions".
3. Clear search.
4. Any page besides page 1
5. Search for "grant". Verify it appears and page reset
- Check that all code is adequately covered by tests - if it isn't …
> [MINT-3447] Reset HKC page to 1 on query change

- src/features/ModelPlan/ModelToOperations/_components/EditMilestoneForm/__snapshots__/index.test.tsx.snap
- src/features/ModelPlan/ModelToOperations/_components/EditMilestoneForm/index.tsx
#NOREF
Unsaved changes were being triggered how the date picker was formatting the date and the data returned from the BE
- Add suppress milliseconds to edit milestone - needby
1.  Added a date to milestone needby
2. Save
3. Reopen milestone
4. Verify no unsaved changes
- Check …
> [NOREF] Add suppress milliseconds to edit milestone - needby

- src/features/ModelPlan/ModelToOperations/_components/EditMilestoneForm/index.tsx
- src/i18n/en-US/modelPlan/modelToOperations.ts
Users can manually enter non-conforming dates in the "Need by" field but the system doesn't throw an error and appears to save when it actually doesn’t. This pr add field validation for needby to prevent user from adding invalid date.
1.  Edit the details for a milestone that has no "Need by" date
2. Enter "1/5/26" or some other non-conforming date format
3. Save changes
4. Verify field validation appear, and should not allow user to save. 
- Don't be afraid to leave …
> [MINT-3531] Add validation for needby field in edit milestone 

- src/components/TableFilter/index.tsx
- src/features/HelpAndKnowledge/SolutionsHelp/index.tsx
There was an issue with pagination not working as intended when an active query was present
- Fixed useEffect hook that had an unnecessary page reset on query change
1.  Navigate to HPK solutions
2. Add a single letter to query search
3. Navigate to another page
4. Verify pagination works
5. Verify opening a solution works
- Don't be afraid to leave comments or ask questions, especially if you don't understand why something was done! (This is often a great time to …
> [NOREF] Fixed pagination/query param - solution help center

- migrations/V229__Custom_Milestone_Description.sql
Database action was failing in pipeline to do the constraint on setting `modified_by` and `modified_dts`
- Updated migration to populate required fields
1.  Migrations passes and fields are set in database
- Check that all code is adequately covered by tests - if it isn't feel …
> [NOREF] Fix migration modified_by and modified_dts
