CMS-Enterprise/mint-app

- pkg/graph/schema.resolvers.go
- CMSCenters resolver to return CMS centers instead of CMMI groups
- Was set incorrectly
Create and Update a model plan
>  update CMSCenters resolver to return CMS centers instead of CMMI groups

- .pre-commit-config.yaml
I'm sure you've all seen it, but sometimes the [go-fmt-import](https://github.com/CMSgov/mint-app/blob/d389bbbbaad710cbfd4e2f7b79c209beb5e6c933/.pre-commit-config.yaml#L28-L31) statement would complain that the "file was not 'goimport'ed with -local". This should fix that by introducing the `-local` flag to the linting step that was complaining about it. Not really sure why this wasn't there before! (Perhaps some folks editors did this automatically?)
1. Open a .go file that imports packages from `mint-app` and other sources (like `/pkg/server/config.go`)
2. Edit the file to put some `mint-app` imports between others, like so
```go
import (
"fmt"
"github.com/cmsgov/mint-app/pkg/appconfig"
"github.com/cmsgov/mint-app/pkg/appses"
"github.com/cmsgov/mint-app/pkg/email" …
```
> [NOREF] Added args and exclude statement to go-fmt-import

- cypress/integration/modelPlan.spec.js
- scripts/dev
- src/queries/GetModelPlanQuery.ts
- src/queries/UpdateModelPlan.ts
- src/queries/types/GetModelPlan.ts
- src/queries/types/UpdateModelPlan.ts
- src/views/Home/index.tsx
- src/views/ModelPlan/TaskList/_components/TaskListSideNav/index.test.tsx
- src/views/ModelPlan/TaskList/_components/TaskListSideNav/index.tsx
- src/views/ModelPlan/TaskList/index.test.tsx
- src/views/ModelPlan/TaskList/index.tsx
- Added ability to archive a model plan
- Added cypress test for archiving model plan
- Refactored some unit tests
Passing in queried model plan as prop from task list instead of just the modelId from the url param.  The additional fields of the model are needed for archiving.
Seed database using MINT (if testing cypress test)
Select/create a model plan and navigate to the task list and select `Remove your Model Plan`, then confirm
Should redirect to home page with model plan archived and no longer returned from query
- Always make comments, even if it's minor, or if you don't …
> Easi 1998/archive model plan

- pkg/graph/generated/generated.go
- pkg/graph/model/models_gen.go
- pkg/graph/resolvers/model_plan.go
- pkg/graph/resolvers/plan_collaborator.go
- pkg/graph/schema.graphql
- pkg/graph/schema.resolvers.go
- pkg/graph/schema.resolvers_helpers.go
- pkg/storage/plan_collaboratorStore.go
- scripts/dev
- src/queries/CreateModelPlanCollaborator.ts
- src/queries/DeleteModelPlanCollaborator.ts
- src/queries/UpdateModelPlanCollaborator.ts
- src/queries/types/CreateModelPlanCollaborator.ts
- src/queries/types/DeleteModelPlanCollaborator.ts
- src/queries/types/UpdateModelPlanCollaborator.ts
- src/types/graphql-global-types.ts
- src/views/ModelPlan/Collaborators/AddCollaborator/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/Collaborators/AddCollaborator/index.tsx
- src/views/ModelPlan/Collaborators/index.tsx
- Simplifications to create, update, and delete plan collaborator mutations.
```gql
mutation createModelPlan {
createModelPlan(modelName: "My Custom Model") {
id
}
}
```
```gql
mutation createPlanCollab {
createPlanCollaborator(input: {
modelPlanID: "<ID>"
euaUserID: "BC0V"
fullName: "Clay Boy"
teamRole: EVALUATION
}) {
id
}
}
```
```gql
mutation updateCollab {
updatePlanCollaborator(id: "<ID>", newRole: MODEL_LEAD) {
id
modifiedDts
}
}
```
```gql
mutation deleteCollab {
deletePlanCollaborator(id: "<ID>") {
id
}
}
```
- Always make comments, even if it's minor, or if you don't …
> [EASI-2023] Plan collaborator simplifications

- pkg/graph/resolvers/plan_basics_test.go
- pkg/graph/resolvers/plan_collaborator_test.go
- pkg/graph/resolvers/plan_discussion_test.go
- pkg/graph/resolvers/plan_milestones_test.go
- pkg/graph/resolvers/resolver_test.go
- Added Plan Collaborator tests
- Basic CRUD operations, as well as expecting an error when updating/deleting the last model lead on a plan
- Updated `EqualValues` asserts to be `expected, actual` instead of `actual, expected` in some instances. This doesn't affect the tests as is, but if something breaks one of these tests, the error messages would be a bit confusing.
```bash
scripts/dev up:backend
scripts/dev test:go
```
> [NOREF] Improved backend tests

- pkg/graph/resolvers/plan_collaborator_test.go
- pkg/storage/genericmodel/errorhandling.go
- pkg/storage/model_planStore.go
- pkg/storage/plan_basicsStore.go
- pkg/storage/plan_collaboratorStore.go
- pkg/storage/plan_discussionStore.go
- pkg/storage/plan_documentStore.go
- pkg/storage/plan_general_characteristicsStore.go
- pkg/storage/plan_milestonesStore.go
- Removed unneeded error type checking when using SQLX's `Select` (which doesn't actually return an error when no results are found)
- Removed checking of `sql.ErrNoRows` when using SQLX's `Get` (so that we now get an error when querying a single entity and don't find it)
- We should still take some time to figure out how we want to do contextually appropriate error logging, if that's a route we want to take (over just forwarding the errors up the call stack)
1. `scripts/dev up:backend`
2. Try and get an entity by ID that doesn't exist:
```gql
query getModelPlan {
modelPlan(id: "eeeeeeee-d693-4daf-87ef-02c97701fc46") {
id
basics {
id
}
}
}
```
3. Expect an error …
> [EASI-2051] SQL error handling

- pkg/graph/generated/generated.go
- pkg/graph/schema.graphql
- pkg/graph/schema.resolvers.go
- pkg/models/model_helpers.go
This change implements common functionality for casting a PQ string array to a specific enum type. At present, you still have to implement the resolver for each pq.StringArray, but it reduces the lines of code considerably. 
Note, credit goes to @DylanSpOddball for implementation of ConvertEnums  helper function. Thanks Dylan!
I also corrected a type in the updatePlanBeneficiaries mutation. No functional change made there.
`scripts/dev up:backend:debug && scripts/dev db:seed`
Run this GQL script that should include most / all of the properties that are an array of enums
```gql
query ModelPlan{
modelPlan(id:"6e224030-09d5-46f7-ad04-4bb851b36eab"){
id
modelName
modelCategory
cmsCenters
cmmiGroups
generalCharacteristics {
resemblesExistingModelWhich
alternativePaymentModelTypes …
```
> implement common function for deserializing pq.string arrays in resolver

- src/views/ModelPlan/TaskList/Basics/Milestones/index.tsx
This bug occurred because of an extra set of {}. One set of {} denotes that the text in between them is javascript, so if you put in another set of brackets in between that, it denotes an object literal. React rendered the model name incorrectly because of this. This syntax now passes the string directly 
Thanks @patrickseguraoddball for discovering this!
`scripts/dev up && scripts/dev db:seed`
1. Navigate to http://localhost:3005/models/6e224030-09d5-46f7-ad04-4bb851b36eab/task-list/basics/milestones
2. Confirm that the subtitle renders the model name correctly
- Always make …
> Update milestones subheader to render modelName correctly

- pkg/graph/generated/generated.go
- pkg/graph/schema.graphql
- pkg/storage/SQL/plan_payments_create.sql
- Fixes to make the enum arrays nullable per FE request
```
mutation createModelPlan ($modelName: String!) {
createModelPlan (modelName: $modelName) {
id
modelName
modelCategory
cmsCenters
cmsOther
cmmiGroups
archived
createdBy
createdDts
modifiedBy
modifiedDts
basics {
id
modelPlanID
modelType
problem
goal
testInterventions
note
createdBy
createdDts
modifiedBy
modifiedDts
status
}
milestones {
id
modelPlanID
completeICIP
clearanceStarts
clearanceEnds
announced
applicationsStart
applicationsEnd
performancePeriodStarts
performancePeriodEnds
wrapUpEnds
highLevelNote
phasedIn
phasedInNote
createdBy
createdDts
modifiedBy
modifiedDts
status
}
generalCharacteristics {
id
modelPlanID
isNewModel
existingModel
resemblesExistingModel
resemblesExistingModelWhich
resemblesExistingModelHow …
```
> fix: nullable enum arrays and other minor issues

- .github/CODEOWNERS
- Introduces GitHub CODEOWNERS that use newly created teams for mint frontend and mint backend specifically.
The goal of this was to make it so that the right people are being tagged for reviews by default, rather than randomly assigning from the entire team.
You can technically test this change by making a PR that targets this branch as the base and seeing if the right people are requested (or you can just trust that GitHub says it's valid and go with it)
> [NOREF] Introduce GitHub teams for specific files

- src/i18n/en-US/modelPlanTaskList.ts
- src/queries/GetModelPlan.ts
- src/queries/types/GetModelPlan.ts
- src/utils/date.ts
- src/views/ModelPlan/TaskList/index.test.tsx
- src/views/ModelPlan/TaskList/index.tsx
- Added `Last Updated` to task list sections
- modifiedDts field should be rendered mm/dd/yyyy for all statuses that are not `READY`
- `Basics` is the only outlier as it has 3 different statuses and 3 different modifiedDts
- Reworked how task list renders statuses to better accommodate displaying relevant task list info
- Some seeded data won't accurately display the realistic nature of last modified dates, as there are status if `IN_PROGRESS` with no modifiedDts, which would never occur
- There are some fields in the forms that won't trigger `IN_PROGRESS` status change, which is dependent on the `Last Modified` rendering.  *may need to consult with BE if we want to change or audit this*
- Create a model plan and fill out fields
- Navigate back to task list and see status and `Last …
> Easi 2134/task list last updated

- src/components/AddNote/index.test.tsx
- src/components/AddNote/index.tsx
- src/views/ModelPlan/Collaborators/AddCollaborator/index.tsx
- src/views/ModelPlan/TaskList/Basics/Milestones/index.tsx
- src/views/ModelPlan/TaskList/Basics/Overview/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/Basics/Overview/index.tsx
- src/views/ModelPlan/TaskList/ParticipantsAndProviders/Coordination/index.tsx
[EASI-2069](https://jiraent.cms.gov/browse/EASI-2069)
- Updated the <AddNote /> component to auto expand if value exists
- Added unit test
Small side fixes
- Fixed a typo on `coordinateWorkNote`
- Added index to collaborator combobox to allow for accessible navigation
[Slack thread about this](https://oddball.slack.com/archives/C030RBZMTRA/p1653597229971309)
- Utilized a Formik hook to fetch field value from name
- This allowed there to be no changes in implementation, only directly in existing component definition
- Create a model plan or use a seeded plan
- Note field with no text should be collapsed on page load - `Add an additional note`
- Note field with text should automatically expand on load with `Add an additional note` hidden
- Deleting a note should leave the text area expanded …
> Easi 2069/note field updates

- go.mod
- pkg/authorization/require_principal_middleware.go
- pkg/local/authentication_middleware.go
- pkg/server/routes.go
- pkg/services/auth.go
- Support for authentication in websocket payload
> Easi 2175/backend websocket changes

- src/views/ModelPlan/Discussions/index.tsx
- Updated the conditional on discussions refetch after the creation of a new discussion
The fixed conditional addresses a race condition between two refetches (now only one should fire)
Create some discussions and replies.  Ensure the discussions and replies are rendered in the correct category
> [NOREF] - Fixed discussion rerender/refetch

- src/utils/status.ts
- src/views/ModelPlan/TaskList/Basics/Milestones/index.tsx
- src/views/ModelPlan/TaskList/Beneficiaries/Frequency/index.tsx
- src/views/ModelPlan/TaskList/GeneralCharacteristics/Authority/index.tsx
- src/views/ModelPlan/TaskList/OpsEvalAndLearning/Learning/index.tsx
- src/views/ModelPlan/TaskList/ParticipantsAndProviders/ProviderOptions/index.tsx
- src/views/ModelPlan/TaskList/Payment/Recover/index.tsx
- Ensured that the final pages of task list sections were not autosaving with `READY` status
There was a case where a user would land on the final page of a task list section without ever visiting the previous pages via IT Tools redirect.  The section would then have a status of ready, and attempting to send mutation with that status.  This PR addresses final pages of section to ensure that the status converts to IN_PROGRESS if status is READY.
- Enter an empty plan and navigate to IT Tools, page seven, question two
- Redirect to the corresponding question and wait for the autosave (or save quickly).  
- Verify no gql errors with mutation
- Check that all code is adequately covered by tests - …
> [NOREF] - Fixed issue where READY status was in final page mutation

- src/views/SubscriptionHandler/index.tsx
NOREF
- Modified conditional for checking if section should be locked
Previously, the locking mutation was checking for a valid task-list section.  This conflicted with identical route names for read-only routes.  Added a conditional to ensure the route lives under 'task-list' and not 'read-only'
-  Navigate to a read-only route
-  Within postman or another browser tab, navigate to the same model's task list
- Ensure the read-only route has not locked the task list
> [NOREF] Modified conditional to locks section

- pkg/graph/generated/generated.go
- pkg/graph/resolvers/model_plan.go
- pkg/graph/resolvers/model_plan_test.go
- pkg/graph/schema.graphql
- pkg/graph/schema.resolvers.go
- pkg/storage/SQL/model_plan_collection_by_collaborator.sql
- pkg/storage/model_planStore.go
- src/queries/GetModelPlans.ts
- src/queries/ReadOnly/GetAllModelPlans.ts
- src/queries/ReadOnly/types/GetAllModelPlans.ts
- Introduces a `Boolean!` parameter to `modelPlanCollection()` GQL query that allows for querying all model plans (or just "my" model plans)
- Modifications to existing queries in the frontend to use this new parameter.
- `scripts/dev db:seed`
- Sign in as `BTAL`
- Navigate to the home page, you should only see one model plans.
- Navigate to the "all models" page, you should see 4 model plans.
> [NOREF] Query All models or just "My" models

- cypress/e2e/modelPlan.spec.js
- src/views/ModelPlan/ReadOnly/Table/index.tsx
- Added data-cy to `<svg>` for favorite element to aid cypress tests
- Modified `modelPlan.spec.js` to reference `data-cy` for checking if a table element is favorited or not
1. `scripts/dev up`
2. Run the Cypress tests
- If you want to run the whole test suite, simply run `yarn cypress run`
- If you want to run only the test that changed, open [modelPlan.spec.js](./cypress/e2e/modelPlan.spec.js) and tag the `favorites and unfavorites a model plan` test with `it.only`, then run `yarn cypress run --spec cypress/e2e/modelPlan.spec.js` to run only the Model Plan test spec
- Always make …
> [NOREF] Fixed failing Cypress test for Favoriting a Model Plan

- src/components/shared/DatePicker/index.tsx
- src/utils/date.ts
- src/validations/planBasics.ts
- src/views/ModelPlan/TaskList/Basics/Milestones/index.scss
- src/views/ModelPlan/TaskList/Basics/Milestones/index.tsx
- src/views/ModelPlan/TaskList/OpsEvalAndLearning/IDDOC/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/OpsEvalAndLearning/IDDOC/index.tsx
- src/views/ModelPlan/TaskList/Payment/Recover/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/Payment/Recover/index.tsx
- Added date warnings for dates in the past
- Ensured dates render on hard refresh
- Updated previous date implementations to not need state and useeffect
This is a small tech debt ticket to add `<DatePickerWarning />` and alerts for date entered in the past.  This is an existing component that needed to be added to Milestones.
- Navigate to Milestones on Model Basics
- Enter a date in the past and click outside the input (blur)
- Verify a alert icon and banner appear notifying a past date was entered
- Save the form and do a hard refresh to ensure the dates render on refresh
- Always …
> [EASI-2189] - Add date warning milestones

- MINT.postman_collection.json
- pkg/graph/generated/generated.go
- pkg/graph/schema.graphql
- src/queries/GetAllModelData.ts
- src/queries/GetModelPlans.ts
- src/queries/types/GetAllModelData.ts
- src/queries/types/GetModelPlans.ts
- src/utils/export/CsvExportLink.tsx
- src/views/Home/index.tsx
- src/views/ModelPlan/Table/index.tsx
- Remove `includeAll` default (previously `False`) from the `modelPlanCollection` query
- Update all GQL queries (postman, `src/*`) to pass the parameter if they weren't already.
- **Note**: For some reason, exported "examples" from the postman collection were not retained when importing/exporting the collection. Feel free to try this yourself by checking out the collection from `main`, importing it, and then immediately exporting it with no changes. For now, I think we should just not have examples in the collection to avoid this.
This change was made because the query that was used to download model plans as CSV was supposed to be downloading ALL model plans, but was instead only downloading the current user's model plans. Additionally, this feature was only intended to show up for …
> [NOREF] Remove default for 'includeAll' parameter in 'modelPlanCollection'

- cypress/e2e/modelPlan.spec.js
- src/components/Modal/index.scss
- src/i18n/en-US/draftModelPlan/newModel.ts
- src/queries/Collaborators/GetModelCollaborators.ts
- src/queries/Collaborators/types/GetModelCollaborators.ts
- src/views/App/index.tsx
- src/views/Home/index.tsx
- src/views/ModelPlan/Collaborators/AddCollaborator/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/Collaborators/AddCollaborator/index.test.tsx
- src/views/ModelPlan/Collaborators/AddCollaborator/index.tsx
- src/views/ModelPlan/Collaborators/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/Collaborators/index.test.tsx
- src/views/ModelPlan/Collaborators/index.tsx
- src/views/ModelPlan/Collaborators/table.tsx
- src/views/ModelPlan/Documents/table.tsx
- src/views/ModelPlan/NewPlan/index.tsx
- src/views/ModelPlan/ReadOnly/Team/index.test.tsx
- src/views/ModelPlan/TaskList/_components/TaskListSideNav/index.test.tsx
- yarn.lock
- Warning modal when adding yourself as a collaborator
- Message on home screen once user booted from model plan
- Rework collaborator route structure from `/new-plan` to `/collaborators`
- Cypress testing
During working on this ticket I realized our routing for collaborators needed to be reworked, and it was relevant to this ticket.  I decided to include it in here.
Previously all collaborator components were rendering. under `/new-plan` routing, which also affected the access control wrapper.  The change in here is to standardize collaborators route to adhere to conventions throughout the rest of the application
- Log in with only `MINT_USER` role
- Create a model plan
- Add another user with role of model lead
- Remove yourself
- Confirm you are sent to home with Success message …
> Easi 2114/warning remove self as collaborator

- .sqlfluff
- pkg/graph/generated/generated.go
- pkg/graph/model/models_gen.go
- pkg/graph/resolvers/prepare_for_clearance.go
- pkg/graph/resolvers/prepare_for_clearance_test.go
- pkg/graph/schema.graphql
- pkg/graph/schema.resolvers.go
- pkg/models/prepare_for_clearance.go
- pkg/storage/SQL/prepare_for_clearance_get_by_model_plan_id.sql
- pkg/storage/prepare_for_clearance.go
- Introduce new types and resolvers to GraphQL
- Added `type PrepareForClearance` to the schema. This represents information helpful for rendering the "Prepare for Clearance" task list section.
- This type has resolvers that dynamically calculate the status of the prepare for clearance section by querying multiple different data sources: The "Clearance Start Date" of the Plan Basics section, as well as the whether or not (and the last time) that each section (minus IT Tools) was marked "Ready for Clearance"
- The logic for this happens in 2 places: [This helper function](https://github.com/CMSgov/mint-app/blob/f54678e5ff26bdf178581450c212a232fb2a160a/pkg/graph/resolvers/prepare_for_clearance.go#L33-L58) in the resolvers, and the [SQL that selects the …
> [NOREF] Prepare for clearance statuses + GQL

- pkg/email/templates/added_as_collaborator_body.template
- The link was only active on the word "unfollow" rather than FIGMA spec of "unfollow it"
- The words "unfollow it" were incorrectly under a color style span
Add a collaborator to a model plan and check the corresponding email in MailCatcher (http://localhost:1085/)
> Collaborator Added Email Fix: fixed style and word linking on "unfollow it"

- pkg/server/routes.go
- DefaultSender now set to no-reply@mint.cms.gov
Add a collaborator to a model plan and observe the FROM field in the corresponding email on MailCatcher is set to no-reply@mint.cms.gov
> Email FROM field now properly set

- docker-compose.yml
- migrations/V1__Add_CRUD_Role_And_IAM_App_User.sql
- pkg/server/config.go
- pkg/storage/iam_db.go
- pkg/storage/store.go
- Introduces logic to authenticate the backend to the DB with IAM (Using `rdsutils` to build a token)
- Changes local execution of the app to use `postgres` instead of `app_user`
- Modifies initial migration to create an IAM user for RDS instead of a traditional app user.
This change is similar (almost identical) to the changes made in the following PRs in the EASi repository:
- https://github.com/CMSgov/easi-app/pull/1677
- https://github.com/CMSgov/easi-app/pull/1694
Ensure the app runs locally as expected!
- Play around in the frontend (create some stuff, modify some stuff!)
- `scripts/dev test:go`
- Check that all code is adequately covered by tests - if it isn't feel …
> [NOREF] Introduce RDS IAM authentication logic

- src/components/shared/OktaSignInWidget/index.tsx
- src/i18n/en-US/general.ts
- Updated Okta widget sign in text
- Navigate to login screen and verify widget text reads - 'Sign in with your EUA or IDM credentials.'
> [EASI-2237] - Updated Okta widget sign in text

- pkg/okta/authentication_middleware.go
- pkg/okta/authentication_middleware_test.go
- Update the field name that holds the groups in the JWT from Okta
Access token example
```json
"accessToken": {
"accessToken": "nixed for 'security'",
"claims": {
"ver": 1,
"jti": "AT.IJOYrBia76YLdXA_3VzDgIyZwhNYzK9QmvbgQxuz0kQ",
"iss": "https://test.idp.idm.cms.gov/oauth2/ausd980kt2CBBzStG297",
"aud": "mint",
"iat": 1668112241,
"exp": 1668114041,
"cid": "0oad9awvebnsMwWNa297",
"uid": "00uaog8skmOPJ7D2m297",
"scp": [
"profile",
"email",
"openid"
],
"auth_time": 1668112232,
"sub": "BC0V",
"mint-groups": [
"MINT_ASSESSMENT_NONPROD",
"MINT_USER_NONPROD"
]
},
"expiresAt": 1668114041,
"tokenType": "Bearer",
"scopes": [
"profile",
"email",
"openid"
],
"authorizeUrl": "https://test.idp.idm.cms.gov/oauth2/ausd980kt2CBBzStG297/v1/authorize",
"userinfoUrl": …
```
> [NOREF] Modify the key that the groups are stored in in the JWT from Okta

- pkg/okta/authentication_middleware.go
- pkg/okta/authentication_middleware_test.go
- pkg/server/routes.go
- Introduces functionality to allow Okta users to authenticate WebSocket connections
- Log in with Okta authentication on two browsers (same account)
- Create a model plan
- Test out task list locking between the two browsers.
> [EASI-2207] Introduce WebSocket authentication for Okta.

- src/index.tsx
- Calculate the `ws://` address based on the `process.env.REACT_APP_GRAPHQL_ADDRESS` variable, rather than hard-coding `localhost`
- Log in on two different browser instances (local dev or Okta)
- Create a model plan that both logged in accounts are collaborators on
- Browse the task list and ensure task list locking works as expected.
> [EASI-2207] Add code to dynamically get ws:// protocol address

- src/index.tsx
- Use `wss://` protocol when the API address is using `https://`
- Same as #311 
> [EASI-2207] Use WSS when connecting over HTTPs

- src/i18n/en-US/draftModelPlan/itSolutions.ts
- src/i18n/en-US/readOnly/modelSummary.ts
- src/queries/ITSolutions/GetOperationalNeeds.ts
- src/queries/ITSolutions/types/GetOperationalNeeds.ts
- src/views/ModelPlan/ReadOnly/OperationalNeeds/index.tsx
- src/views/ModelPlan/ReadOnly/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/_components/Sidenav/index.tsx
- src/views/ModelPlan/ReadOnly/index.tsx
- src/views/ModelPlan/TaskList/ITSolutions/Home/__snapshots__/operationalNeedsTable.test.tsx.snap
- src/views/ModelPlan/TaskList/ITSolutions/Home/operationalNeedsTable.test.tsx
- src/views/ModelPlan/TaskList/ITSolutions/Home/operationalNeedsTable.tsx
- src/views/ModelPlan/TaskList/ITSolutions/util.tsx
- Add `modifiedDts` to `GetOperationalNeeds` query and types, so that `getITSolutionsStatus` works in OperationalNeeds Read Only component
- Add `ReadOnlyOperationalNeeds` component to ReadOnly subcomponent object
- add a few more conditionals to render a full width subcomponent section for `it-tools`
- add a `readOnly` parameter to `returnActionsLinks` in `operationalNeedsTable` file
1. Seed data
2. Navigate to Read Only
3. Navigate to IT tools
4. Ensure Operational Needs table is displaying
5. Editor Access and Collaborator should see the "Actions" column. Otherwise, "Actions" column is hidden.
- Check that all code is adequately covered by tests - if it isn't feel free to suggest the …
> [EASI-2213] Model Plan Read Only: Operational Needs

- src/views/ModelAccessWrapper/index.tsx
NOREF
- Added a skip conditional to gql query for collaborators on routes that do need access control
- Changed the route definitions for access control from `!read-only` to `editable`
The access control wrapper was making unnecessary calls to BE for collaborator info on routes that had no need for access control
The access control routes are more clearly defined by the presence of the task list/collaborators rather than the absence of read only.  The task list/collaborators are the only editable sections in MINT
- Attempt to access any route under `/task-list` or `/collaborators` if not a model team or assessment member
- Verify user is taken to read-only view …
> [NOREF] - Access control update

- src/views/ModelPlan/ReadOnly/Table/index.tsx
NOREF
- Connected CRTDL data on the table on /models
When adding CRTDL dev work, data flow was not connected to the previously stubbed data on the table on /models.  This was previously added on the favorite card and should be reflected there as well
Verify CRTDLs show up on the table on /models
> [NOREF] - Connect CRTDL data to /models table

- src/views/UserInfoWrapper/index.tsx
- Modify the key checked in the JWT from `groups` to `mint-groups` to reflect what actually gets returned from Okta
The backend change was made in this PR (https://github.com/CMSgov/mint-app/pull/300), and the corresponding frontend change was just missed until now!
- Log in with Okta
- Navigate to http://localhost:3005/user-diagnostics
- Ensure that the right job codes are parsed!
> [NOREF] Use 'mint-groups' instead of 'groups' when parsing job codes on Frontend

- .pre-commit-config.yaml
- Commits to `main` are allowed by pre-commit so that when `pre-commit` runs in CI it won't fail on `main`.
- GitHub itself (due to repository config) will not allow pushing to `main` anyways, so this is just for CI/CD (still can't commit directly to `main`)
Attempt to make a commit (with this pre-commit config) on `main`. It should let you commit, but not push!
> [EASI-2003] Allow 'main' in pre-commit config

- src/views/ModelPlan/ReadOnly/_components/ContactInfo/index.tsx
- src/views/ModelPlan/ReadOnly/index.tsx
- Add new prop to ContactInfo -- isViewingTeamPage to conditionally render the "More team members" link
1. seed
2. Navigate to any model plan read only page
3. Navigate to team sub-page and check to see that the link is now gone.
> [EASI-2484] Remove "More team members" link from the read-only Team sub-page

- src/views/ModelPlan/Table/index.tsx
NOREF
- Added missing isMAC useMemo dependency in model plan table
Not sure why linting checks didn't catch this missing useMemo dependency, but it caused the deployment ([EASI-2492] - Launch Darkly Flags to Hide IT Lead experience
) to fail.  Can probably cancel that deployment as this should fix the deployment error
> Added missing isMAC useMemo dependency

- src/views/TimeOutWrapper/index.tsx
- Use default `post_logout_redirect_uri` when logging users out via a session timeout
Not 100% sure why, but depending on _how_ a user logged out (session timeout vs. clicking "Sign Out") we'd send the user to a different URI. This was annoying because it wasn't consistent, and was problematic because the IDM team only has `/` as a valid redirect URI (rather than `/` and `/signin`)
Sadly, only `dev.mint.cms.gov` and `test.mint.cms.gov` are valid redirect URIs, not `localhost:3005/`, so testing this locally isn't possible yet, but ensuring that when you get a session timeout the `post_logout_redirect_uri` is what you expect it to be in the network console is sufficient! …
> [NOREF] Use default logout URI

- pkg/okta/authentication_middleware.go
- pkg/okta/authentication_middleware_test.go
- pkg/server/routes.go
- Okta middleware switches job codes depending on if the user is in a production environment or pre-production environment
TBD
> [EASI-2491] - Change Job Codes Depending on Environment

- .github/workflows/run_tests.yml
- cmd/mint/test.go
- docker-compose.cypress_ci.yml
- docker-compose.cypress_local.yml
- docs/local_testing.md
- pkg/appconfig/config.go
- pkg/appconfig/config_test.go
- pkg/server/routes.go
- scripts/check_deployed_image_findings
- scripts/release_static
- Changed references that used `test` as an environment to use `testing` instead
- Created new `testing` environment in `appconfig` package to facilitate identifying when we're running tests (what used to be `test`)
We needed to have some modifications to our environment configuration because EASi historically (and currently) only had `dev`, `impl`, and `prod` environments. Therefore, an environment was created in the appconfig called `test` which was used to identify when the application was being run for local test (i.e. `go test` or `cypress`)
However, MINT has an environment literally named `test`, so the "unit testing" environment was renamed `testing`, and all instances of `test` now refer to the _deployed_ test env, rather than the "unit testing" environment.
- Ensure that when …
> [NOREF] Create "testing" environment instead of using "test"

- .github/workflows/run_tests.yml
- Remove use of [satackey/docker-layer-caching](https://github.com/satackey/action-docker-layer-caching) GitHub action in `run_tests.yml` as it seemed to be causing issues with the amount of storage space on the GH runners.
Some examples of failed jobs:
1. @patrickseguraoddball's https://github.com/CMSgov/mint-app/actions/runs/3686509199
2. @rileyanderson's https://github.com/CMSgov/mint-app/actions/runs/3689636858/jobs/6245825319
https://github.com/satackey/action-docker-layer-caching/issues/305#issuecomment-1231144309 This is a possible reason that this only started happening recently.
Ensure that `run_tests` still passes - this is just a caching change, so as long as it still works, we should be good!
- It's best to pull the branch locally and test it, rather than just looking at the …
> [NOREF] Disable docker caching in GH Actions

- src/components/ITToolsWarning/index.tsx
NOREF
- The component ITToolsWarning component was not hidden by `hideITLeadExperience` flag
This PR added the conditional flag check on the component itself rather than the dozens of places it's implemented
- Verify the warning are not visible
> [NOREF] - Hide ITToolsWarning component if LD flag is true

- package.json
- src/views/TimeOutWrapper/index.tsx
- yarn.lock
- Fixed an issue with the TimeoutWrapper sending infinite messages to other tabs when multiple are open, causing the frontend/browser to crash.
- Start up the service locally with `scripts/dev up`
- Log in (Okta auth is all that will work)
- Open multiple home page tabs (usually 3-5 would replicate the issue previously)
- Switch between those tabs as rapidly as you can (`cmd+shift+arrow` on Mac can help do this quickly)
- Ensure there's no performance issues / crashes.
> [NOREF] Fix an issue with multiple tabs triggering an infinite loop of messages

- .github/workflows/deploy_pipeline.yml
- Enabled GitHub action to deploy to the production environment
- Temporarily set the dependency on deploying to `prod` to require a deploy to `test` rather than `impl`, due to current pen-testing.
- Overview the GitHub actions code to see if it aligns with other environment deploy code
- Ensure the environment in GitHub is properly configured (secrets)
> [EASI-2499] GitHub actions to deploy to prod

- .github/workflows/run_tests.yml
- Dockerfile.db_clean
- Dockerfile.db_migrations
- Upgrade flyway to V9 in Dockerfiles for DB Clean and DB Migrate
- Upgrade flyway to V9 by upgrading `joshuaavalon/flyway-action` to v3.0.0 (https://github.com/joshuaavalon/flyway-action/releases/tag/v3.0.0)
- Ensure that the CI/CD jobs pass, which use the flyway-action to run migrations!
- Start the service with `scripts/dev up`
- This inherently runs the `Dockerfile.db_migrations` file due to [this entry](https://github.com/CMSgov/mint-app/blob/8401c8c2a62a26a15e236051ebb05755b3911851/docker-compose.yml#L9-L18) in our docker-compose.yml file.
- Ensure DB migrations ran as expected
- Use this nasty one-liner to build and run the DB Clean image:
```bash
FLYWAY_CLEAN_DISABLED=false FLYWAY_USER=postgres FLYWAY_PASSWORD=mysecretpassword …
```
> [EASI-2435] Upgrade flyway to v9

- pkg/graph/generated/generated.go
- pkg/graph/schema.graphql
- pkg/server/routes.go
- pkg/services/auth.go
- A new directive with support for multiple roles is created
- The MAC role is assigned to appropriate GraphQL mutations
- agreeToNDA
- Call the agreeToNDA mutation with the following job codes and results:
- Job Code "MINT_USER_NONPROD" - Access
- Job Code "MINT MAC Users" - Access
- Job Code "MINT_ASSESSMENT" - No Access
> [Easi-2533] Multiple Role Directive and Assign MAC Role to Mutations 

- src/views/TimeOutWrapper/index.tsx
- Check if using Okta auth (if you have an `idToken` and an `accessToken`) before attempting to renew tokens
- Start MINT locally
- Set the timeout in `src/views/TimeOutWrapper/index.tsx` to something manageable for local development
```javascript
// const fiveMinutes = Duration.fromObject({ minutes: 5 }).as('milliseconds');
const fiveMinutes = Duration.fromObject({ seconds: 15 }).as('milliseconds');
```
- Log in with local dev
- Let the timeout modal pop up
- Close the modal to continue using MINT
- Ensure no errors pop up
- Always make comments, even if it's minor, or if you don't …
> [NOREF] Fix timeout modal locally

- .github/workflows/deploy_pipeline.yml
- Re-enable IMPL deploys, now that pen-testing is complete in the IMPL environment
- Make `dev` and `test` environments deploy concurrently after `run_tests`. 
- In the case of pushing a bug to `main`, this _does_ mean we will push it to both `dev` and `test`, but since `dev` is really meant to be an internal dev-only environment, and `test` is where most feature validation will happen, it feels like a good way to save some time on the deploy process.
- There's not a great way to test GitHub actions locally (except for something like [act](https://github.com/nektos/act)), so it's recommended to just review the changes made to this file and ensure they're doing what we expect!
- Also, if folks disagree or have questions about making dev/test deploy at the same time, I'm happy to change …
> [NOREF] Re-enable IMPL deployments. Make dev/test deploy concurrently

- cmd/dbseed/resolver_wrappers.go
- migrations/V2.5__Add_Users_table.sql
- migrations/V41__Add_Has_Logged_In_To_User_Account.sql
- pkg/appcontext/context.go
- pkg/authentication/enhanced_jwt.go
- pkg/authentication/user_account.go
- pkg/cedar/cedarldap/translated_client.go
- pkg/graph/resolvers/added_as_collaborator_email_test.go
- pkg/graph/resolvers/model_plan.go
- pkg/graph/resolvers/model_plan_test.go
- pkg/graph/resolvers/plan_collaborator.go
- pkg/graph/resolvers/plan_collaborator_test.go
- pkg/graph/resolvers/resolver_test.go
- pkg/graph/resolvers/resolver_test_utilities.go
- pkg/graph/schema.resolvers.go
- pkg/local/authentication_middleware.go
- pkg/local/cedar_ldap.go
- pkg/models/user_info.go
- pkg/okta/authentication_middleware.go
- pkg/okta/authentication_middleware_test.go
- pkg/storage/SQL/user_account/get_by_username.sql
- pkg/storage/SQL/user_account/insert_by_username.sql
- pkg/storage/SQL/user_account/update_by_username.sql
- pkg/storage/user_accountStore.go
- pkg/userhelpers/user_account_utils.go
- pkg/worker/worker_test.go
- pkg/worker/worker_test_utilities.go
- Add functionality to add a user account using CEDAR information when a collaborator is added
- Add hasLoggedIn bool to user account
- If user hasn't logged in, update the information with OKTA instead at the time of login.
- Decorate the context with the JWT, so we we can use that for reaching OKTA endpoints 
Note, this change should function for both local and CEDAR. It is worth while to check with both
To check Cedar locally, you need to comment out line 127-129 in routes and connect to the vpn
``` go
if s.environment.Local() || s.environment.Testing() {
cedarLDAPClient = local.NewCedarLdapClient(s.logger)
}
```
1. Create model plan.
2. Add a collaborator to the MODEL PLAN
a. Verify that a user account was added for this collaborator, and that hasLoggedIn == false
3. Log in as that …
> Easi 2550/add user account collaborator

- src/utils/user.test.ts
- src/utils/user.ts
- src/views/Home/index.tsx
- src/views/ModelAccessWrapper/index.tsx
- src/views/ModelPlan/CRTDL/CRTDLs/table.tsx
- src/views/ModelPlan/Discussions/index.tsx
- src/views/ModelPlan/Documents/table.tsx
- src/views/ModelPlan/ReadOnly/index.tsx
- src/views/ModelPlan/TaskList/ITSolutions/Home/operationalNeedsTable.tsx
- src/views/ModelPlan/TaskList/index.tsx
- src/views/User/index.tsx
- Require `flags` parameter for `isAssessment`, as it's needed within every context.
- Remove `flags` parameter for user utility functions that don't require flag data.
- Start the server with `scripts/dev up`
- Log in with your EUA account locally
- Downgrade yourself locally (https://app.launchdarkly.com/mint/local/features/downgradeAssessmentTeam/targeting)
- Seed the DB with `scripts/dev db:seed`
- Ensure that viewing a model plan you're not a collaborator for doesn't allow you to switch to the task list view
- Always make comments, even if it's minor, or if you don't understand …
> [NOREF] Require flags for isAssessment, remove from others

- src/queries/GetModelPlan.ts
- src/queries/types/GetModelPlan.ts
- src/views/ModelPlan/Documents/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/Documents/index.test.tsx
- src/views/ModelPlan/Documents/index.tsx
- src/views/ModelPlan/Status/index.tsx
- src/views/ModelPlan/TaskList/index.test.tsx
- src/views/ModelPlan/TaskList/index.tsx
- Condensed `GetModelPlanCollabotors` and `GetModelPlan` queries on task list
- Deprecated unneeded `useQuery` hook in favor of `useContext` within `ModelInfoWrapper`
- Run FE tests
- Check data is intact with collaborators in task list
> [NOREF] - Condensed task list queries, deprecated unneeded useQuery hook

- pkg/email/templates/daily_digest_body.template
- Modify link in daily digest email to link to `${modelPlanID}/task-list` instead of `${modelPlanID}` (which results in a 404)
- Make a model plan
- make some changes
- Check the audit email in Mailcatcher (should fire off every 5 minutes)
> [NOREF] Modify link in digest body to link to task list

- pkg/graph/resolvers/operational_solution_test.go
- pkg/storage/loaders/operational_solutions_loader.go
- Remove check for value in data loader logic
- If there isn't a result, it will return the `ZERO` value of the object ( an empty `[]*models.OperationalSolution{}`
- Unit Test to assert this behavior
You can test this two ways,
1. Load the front end, and go to the IT lead section
a. Assert that there are no errors when the page loads
2. Make a model plan, and query it for needs and solutions with include not needed = `false`
a. Assert that there are no errors
```GQL
query ModelPlan{  
modelPlan(id:"{{modelPlanID}}"){
id
modelName
isCollaborator
operationalNeeds { 
id
modelPlanID
name
key
nameOther
needed
solutions(includeNotNeeded:false) {
id
operationalNeedID        
name
key   
needed
nameOther
pocEmail
pocName     
createdBy
createdDts
}
}
}
}
``` 
- It's best to pull the branch …
> EASI-2461 Operational Solutions Data Loader allow empty

- README.md
- pkg/appcontext/context.go
- pkg/authentication/user_account.go
- pkg/graph/generated/generated.go
- pkg/graph/resolvers/base_struct_test.go
- pkg/graph/resolvers/operational_solution_test.go
- pkg/graph/resolvers/resolver_test_utilities.go
- pkg/graph/resolvers/user_account.go
- pkg/graph/resolvers/user_account_test.go
- pkg/graph/resolvers/user_id_relation_test.go
- pkg/graph/schema.resolvers.go
- pkg/models/audit_change.go
- pkg/models/base_struct_user_table.go
- pkg/models/plan_collaborator.go
- pkg/models/user_id_relation.go
- pkg/server/routes.go
- pkg/storage/SQL/user_account/get_by_id_LOADER.sql
- pkg/storage/access_controlStore.go
- pkg/storage/loaders/data_loaders.go
- pkg/storage/loaders/user_account_loader.go
- pkg/storage/user_accountStore.go
- pkg/userhelpers/user_account_middleware.go
- pkg/userhelpers/user_account_utils.go
- Data Loader to get User Account by ID
- Generic functionality to get user account info from a Middleware service
- GQL will try to call the method provided anytime that there is a method named the same as a property in the GQL
- So GQL with a createdByUserAccount, or modifiedByUserAccount will call those functions on base struct
- Likewise, there is a new embedded struct for a user_id_relation. If embedded in any model, GQL will call that method for returning the user account for that ID.
1. Make a few model plans
2. On each model plan, make a few different collaborators. 
3. Update the collaborators if you like, optionally with a different account (so you can have more values to test with)
4.  Use this GQL to invoke the dataloader (note these separate fields all call the same data …
> Easi 2652/user account data loader and generic GQL functionality

- pkg/storage/SQL/plan_basics/get_by_model_plan_id_LOADER.sql
- src/components/ReadyForReview/__snapshots__/index.test.tsx.snap
- src/components/ReadyForReview/index.test.tsx
- src/components/ReadyForReview/index.tsx
- src/i18n/en-US/draftModelPlan/draftModelPlan.ts
- src/queries/GetUserInfo.ts
- src/queries/types/GetUserInfo.ts
- src/views/ModelPlan/TaskList/PrepareForClearance/Checklist/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/PrepareForClearance/Checklist/index.test.tsx
- src/views/ModelPlan/TaskList/PrepareForClearance/Checklist/index.tsx
- Quick pairing with @StevenWadeOddball  to make sure basics' `ready_for_review_by` and `ready_for_review_dts` gets updated
- `GetUserInfo` query and type
- Add `GetUserInfo` queries to render username instead of EUA ID
- Change `itTools` to `itSolutions` in Prepare for Clearance checklist
1. Make a Task List section as ready for review.
2. Return to page and make sure the text is rendering username 
1. Go through the task list to enable the `Prepare for Clearance` section
2. Mark the sections ready for clearance
3. Verify that the timestamp shows username, not eua id
- Always make …
> [EASI-2630] EUA showing on timestamp instead of user name

- src/components/CedarContactSelect/index.tsx
- src/hooks/useCedarContactLookup.tsx
- src/hooks/useDebounce.tsx
NOREF
- Created `useDebounce` hook
- Updated `CedarContactSelect` and `useCedarLookup` to be more tailored to MINT's needs
There was the option to use `lodash`, however I found this solution to be simpler and more customizable.  Even if using `lodash` a custom hook would still be necessary.  
- Test difference debounce delays by changing line
https://github.com/CMSgov/mint-app/blob/b21d3ae5fa8ef5f7d27a13aaf09391b81830b7c7/src/components/CedarContactSelect/index.tsx#L160
- Inspect network calls to ensure the request is being properly debounced
- Always make comments, even if it's …
> [NOREF] - Debounce input for CEDAR API calls

- src/constants/jobCodes.ts
- src/views/AuthenticationWrapper/DevLogin.tsx
This is a fast follow to what @StevenWadeOddball [mentioned](https://github.com/CMSgov/mint-app/pull/433#pullrequestreview-1283617573) in #433, which was addressing a PROD side error on job codes. 
- Add a `NONPROD_JOB_CODES` constant
- Add all possible job codes in `JOB_CODES`
- Adjusted `DevLogin` to check the `NONPROD_JOB_CODES`
> [NOREF] Adding a NONPROD_JOB_CODES constant to jobCodes.ts

- .github/workflows/manual_deploy.yml
- Add read/write permissions to manual deploy script
- [Example of job failing](https://github.com/CMSgov/mint-app/actions/runs/4126898076/jobs/7129579404)
- This introduces the same permissions as the deploy_to_environment job, which is all that needs to be done to match.
> [NOREF] Add permissions to manual deploy to read credentials

- migrations/V68__Remove_Architect_Role_From_Team_Roles.sql
- Adds `modified_by` and `modified_dts` to the migration that updates plan collaborators
https://github.com/CMSgov/mint-app/pull/465
> [NOREF] Fix migration that removes architect to set modified_by and modified_dts

- src/i18n/en-US/general.ts
- src/i18n/en-US/modelPlanTaskList.ts
- src/views/App/index.tsx
- src/views/ModelPlan/TaskList/_components/TaskListLock/index.tsx
- src/views/TaskListBannerAlert/index.scss
- src/views/TaskListBannerAlert/index.test.tsx
- src/views/TaskListBannerAlert/index.tsx
- Wrapper component to render banner on relevant task list routes
- Should not render on clearance or IT solutions
- Added user name to task list lock on task list sections
- Unit testing
Verify task list locked and banner match figma mocks
> [EASI-2703] - Added banner and wrapper to display task list lock on routes

- migrations/V85__Add_Missing_Needs_And_Update_Existing_Needs.sql
- Create migration that inserts an operational need for every model plan that currently doesn't have one.
- Update those needs to set if they should be needed or not
1. Comment out migration v79 to v85
2. Bring up the container. 
3. Create some model plans, answer task list sections in a way that will trigger a new need being considered needed as indicated by this [spreadsheet](https://docs.google.com/spreadsheets/d/1HtXBREHtP5hEMFqcGvNDn_HuhyYMy9NX0tCvfWnRJd8/edit#gid=1374666257)
a. As an example, for General Characteristics, set what is the agreement type to participation agreement. That will make the need Sign Participation Agreements show up as needed.
4. run the commented out migrations
5. Verify that the needs inserted, and set as needed.
- It's best to pull the branch locally and …
> NOREF: Create Missing Operational Needs for Existing Model plans

- pkg/graph/generated/generated.go
- pkg/graph/schema.graphql
- This is a fairly simple change. It just gates all queries except for current_user with a @hasAnyRole directive. 
- This makes it so only users who have logged in and have the appropriate roles can query the data
1. Try to hit any query without having any jobCodes set in postman.
2. Confirm you get the unauthorized exception
> Add   @hasAnyRole(roles: [MINT_USER, MINT_MAC]) to all queries

- src/views/ModelPlan/TaskList/ITSolutions/Home/__snapshots__/operationalNeedsTable.test.tsx.snap
- src/views/ModelPlan/TaskList/ITSolutions/Home/operationalNeedsTable.tsx
- src/views/ModelPlan/TaskList/ITSolutions/util.tsx
- Modified how the initial state of Op Needs table is rendered to alleviate a race condition
- The initial state of the table was being set before async data was received to dictate what columns were hidden
Verify the 'Actions' column on op needs table isn't hidden because of a race condition
> [NOREF] - Hidden columns(OpNeeds Table) race condition

- src/i18n/en-US/landing.ts
- src/utils/date.ts
- src/views/Landing/index.scss
- src/views/Landing/index.tsx
Typos
Update “Product hightlights” to “Product highlights”
Update Jane Middleton timestamp from “3 hour ago” to “3 hours ago”
Styling
Increase the size of the email app icon? It looks a tad small currently
The alignment on the recruit participants row of the operational needs tracker looks a little wonky at some widths. It looks like it’s because it’s the only one not breaking to 2 lines all of the time (screenshot). Could we force a max width so it always wraps? Also open to your ideas if there's an easier way to fix that.
Can you update the color of the landing description and pre-decisional content to the primary lighter color? (#D9E8F6)
- Check that all code is adequately covered by tests …
> [NOREF] - Landing UI tweaks

- pkg/graph/schema.resolvers_test.go
- pkg/local/okta_api.go
- pkg/oktaapi/client_wrapper.go
- pkg/server/routes.go
- Uses the `context` logger instead of the one instantiated in `routes.go` to ensure that each request to the Okta API has its own logger with the trace ID already applied to it.
- scripts/dev up
- Make a new model plan
- Add a user, and perform a search by name
- Check the logs with `docker compose logs -f mint`
- You should see logs that mock calls to the Okta API, and they should have a TraceID attached to them
> [NOREF] Added trace ID to okta api calls

- pkg/local/authentication_middleware.go
- pkg/okta/authentication_middleware.go
- pkg/server/routes.go
- This allows tracking the traceID when we get these errors
> [EASI-2824] Use context based logger in websocket middleware

- .pre-commit-config.yaml
- .sqlfluff
- config/logstash/ingest_change_table.sql
- pkg/storage/SQL/access_control/check_if_collaborator.sql
- pkg/storage/SQL/access_control/check_if_collaborator_by_operational_need_id.sql
- pkg/storage/SQL/access_control/check_if_collaborator_by_solution_id.sql
- pkg/storage/SQL/access_control/check_if_collaborator_discussion_id.sql
- pkg/storage/SQL/analyzed_audit/get_by_model_plan_id_and_date.sql
- pkg/storage/SQL/analyzed_audit/get_collection_by_model_plan_ids_and_date.sql
- pkg/storage/SQL/audit_change/collection_by_id_and_table_and_field.sql
- pkg/storage/SQL/audit_change/collection_by_primary_key_or_foreign_keyand_date.sql
- pkg/storage/SQL/discussion_reply/update.sql
- pkg/storage/SQL/nda_agreement/update.sql
- pkg/storage/SQL/operational_need/insert_all_possible.sql
- pkg/storage/SQL/operational_need/insert_or_update.sql
- pkg/storage/SQL/operational_need/update_by_id.sql
- pkg/storage/SQL/operational_solution/insert.sql
- pkg/storage/SQL/operational_solution/update_by_id.sql
- pkg/storage/SQL/plan_document_solution_link/delete_by_ids.sql
- pkg/storage/SQL/plan_favorite/create.sql
- pkg/storage/SQL/plan_ops_eval_and_learning/update.sql
This change attempts to do 2 things
- Upgrade SQLFluff to v2 using [this upgrade guide](https://docs.sqlfluff.com/en/stable/releasenotes.html#upgrading-from-1-x-to-2-0)
- No longer lint the [migrations/](./migrations/) folder. I foresee the following benefits
- Allow us to more readily make changes to our SQLFluff config, as linting the migrations folder means we can't really lint any existing migrations (or else flyway will throw a fit about the SHA having changed)
- Speed up the linting of our SQL by reducing the lint process to only our other .sql files (right now it takes upwards of 5 minutes on CI to run our entire lint process)
If anyone can think of a way to lint NEW migrations, but not existing ones, I'm all ears, but this was the best thing I could come up with in the short term …
> [NOREF] Upgrade SQLFluff to v2

- .github/workflows/build_application_images.yml
- Dockerfile.db_migrations
- docker-compose.yml
- Modifies image tags used for mailcatcher to use 0.8.2, which is multi-arch (where the previous image was not)
- Modifies the Dockerfile for db migrations to support a build argument that allows modifying the tag used for the base Flyway image. This allows using the multi-arch image locally while also allowing the same dockerfile to build the alpine image to push to ECR.
The main goal for this PR was to reduce the frequency with which the DB Migrate container would fail to start locally. After some investigation, we're lead to believe that it's due to spinning up an amd64 image on arm computers (M1 Mac, for example). This isn't a guaranteed fix, but this is a good change to make even if it's not the fix for the hanging migrate cnotainers.
- Ensure there are no warnings …
> Use multi-arch images when building locally for migrate and mailcatcher, use alpine when building for ECR

- docker-compose.yml
- Pulling Opensearch from Dockerhub after experiencing rate limiting issues pulling from ECR.
- Pinning to 2.5.0 to match current available versions in AWS Opensearch Service
```
Supported versions of OpenSearch and Elasticsearch
OpenSearch Service currently supports the following OpenSearch versions:
2.5, 2.3, 1.3, 1.2, 1.1, 1.0
```
[Current Versions- AWS Docs](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/what-is.html#choosing-version)
> EASI-2876: pull from dockerhub and pin to 2.5.0

- pkg/graph/resolvers/search_change_table.go
- pkg/local/authentication_middleware.go
- pkg/okta/authentication_middleware.go
- pkg/okta/authentication_middleware_test.go
- Assessment User now gets granted normal user role
- Unit tests to assert this new logic.
- I looked through the front end code to see if there needs to be changes there, It looks like this covers all the needs.
- 
1. Log into the app / Run postman queries with only the ASSESSMENT Job code
2. Confirm that you can hit endpoints that require the mint user job code (like modelPlan)
3. Verify Unit test coverage matches as expected
4.  Verify that there aren't missed areas on the frontend that need code changes to work with this paradigm.
- Always make comments, even if it's minor, or if …
> Easi 2592/mint assessment permissions overhaul

- pkg/server/logger.go
-  (source and host) fields are created during ingestion by SPLUNK, and are defined in our logger.go configuration.
- this made it so you couldn't search on those fields without getting incorrect results
- These fields are renamed so we can query them individually in SPLUNK.
Run the App, or just see that CI tests passed.
> Rename logger fields so they dont conflict with SPLUNK

- migrations/V91__Resembles_Existing_Model_To_Link.sql
Deploying the migration V91 failed in impl because it tried to insert a record where for a text array entry for resembles which in general characteristics that didn't map to an `existing_model` or a `model_plan`. This is likely an artifact of data in IMPL from when we changed existing model ids. These unmatched links should be ignored.
- Add where clause to migration to make sure links are only added
1. Comment out migration v91
2. Bring up the app
3. Run the below SQL to add some data (with non-matching values for resembles_existing_model_which)
4. Manually run the migration in SQL and verify that it handles the non match condition
5. If you would like to verify that this was the root cause, do the above steps, but run the old migration without the where clause for step 4.
Seed data SQL …
> Existing Model Link Migration correction

- src/components/ITSolutionsWarning/__snapshots__/index.test.tsx.snap
- src/components/shared/Alert/__snapshots__/index.test.tsx.snap
- src/components/shared/Alert/index.tsx
- src/views/ModelPlan/Collaborators/AddCollaborator/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/Collaborators/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/Discussions/SingleDiscussion.tsx
- src/views/ModelPlan/Discussions/index.tsx
- src/views/ModelPlan/Documents/AddDocument/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/NewPlan/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/Basics/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/GeneralCharacteristics/KeyCharacteristics/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/GeneralCharacteristics/TargetsAndOptions/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/OpsEvalAndLearning/CCWAndQuality/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/OpsEvalAndLearning/IDDOCTesting/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/OpsEvalAndLearning/Learning/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/OpsEvalAndLearning/Performance/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/ParticipantsAndProviders/Coordination/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/Payment/AnticipateDependencies/__snapshots__/index.test.tsx.snap
- src/views/NDA/__snapshots__/index.test.tsx.snap
- Added text pre-wrap to discussion text for spacing preservation
- Added callback to alert for consecutive rendering of alerts to properly close and reopen (noticeable in the recent discussion readdonly PR)
- Added a div around alert children to properly use flex with multi- line children text and the close button
> [NOREF] - Discussion text and alert fixes

- pkg/storage/SQL/operational_solution/and_possible_get_by_operational_need_id_LOADER.sql
- Update the operational solutions dataloader to correctly select the created by field from the operational solution table.
- This fixes a bug where you would see multiple solutions for an operational need under certain conditions.
- To recreate the bug locally, all you have to do is make a model plan, answer a question to set a need as needed.
- Log in as a different user, and select a default operational solution as the chosen solution. --> This would give two views of the solution, one with the incorrect created by, and one with the correct
1. Make a model Plan
2. Answer a question to set an operational need as needed
3. Log in as a different user
4. Select a default solution for that operational need.
5. Confirm that you don't see a duplicate solution.
6. 
- It's best to pull the …
> Correct Duplicate Operational Solution

- src/components/Modal/index.scss
- src/components/Modal/index.tsx
- src/i18n/en-US/index.ts
- src/i18n/en-US/readOnly/filterView.ts
- src/i18n/en-US/readOnly/generalReadOnly.ts
- src/types/flags.ts
- src/utils/user.test.ts
- src/views/FlagsWrapper/index.tsx
- src/views/ModelPlan/ReadOnly/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/_components/FilterViewModal/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/_components/FilterViewModal/index.test.tsx
- src/views/ModelPlan/ReadOnly/_components/FilterViewModal/index.tsx
- src/views/ModelPlan/ReadOnly/_components/Sidenav/index.tsx
- src/views/ModelPlan/ReadOnly/index.tsx
- Add `FilterVIewModal` component
- Add filter "box" to `SideNav` nav and wrapped in a flag
- Add new `hideGroupView` flag
- Add Group View specific copy
- Adjusted `Modal` component to be more flexible
1. Navigate to a Read only page for any model plan
2. See sidenav does not have "Filter box" 
3. Go to LaunchDarkly and add yourself to the flag
4. Now, see new filter "box" in the side nav
6. Click button to pop up modal
7. Select a group in the dropdown and hit `View filtered content` button
8. Check to see query parameter has been updated to have the value of the group you've selected
9. Go through the modal again, but this time click `View all content` 
10. check to see query parameter is cleared
- It's best to pull the branch locally and test it, rather than just looking at the code …
> [EASI-2968] Group Filter Box/Modal Select

- pkg/local/authentication_middleware.go
- pkg/okta/authentication_middleware.go
- src/constants/jobCodes.ts
- src/utils/user.ts
It was determined that the job code `MINT MAC Users` should be a broader named job code `MINT Contractor`. To avoid any service interruption, the code is updated to allow all job code checking logic by using either the legacy job code, or the new job code. When the new job code is released, we will remove the references to the legacy job code.
- Introduce MINT Contractor job codes
- Update JobCodeMAC on the backend to return true for either `MINT Contractor` or for `MINT MAC users`
- Update isMac user on frontend to return true for either `MINT Contractor` or for `MINT MAC users`
1. Log in with the new job code. Confirm you can accept the NDA (which requires at least a MAC user job code)
2. Repeat the above with the legacy job code, and ensure that you can still accept the NDA.
- It's …
> NOREF add MINT Contractor role in anticipation of job role change

- pkg/graph/generated/generated.go
- pkg/graph/schema.graphql
- src/views/ModelPlan/ModelPlanOverview/index.tsx
- src/views/ModelPlan/ReadOnly/index.tsx
- Modify BE to allow plan favoriting by all users
- Modify FE to show hidden fields for MAC users
- Start app
- Seed DB
- Login as a MAC user (from 1Password)
- Ensure plan favoriting works
> [EASI-3022] Allow MAC users to favorite plans

- .github/workflows/run_tests.yml
- src/views/TimeOutWrapper/index.tsx
- Increase activity timeout to 90 minutes
The best way to test this change locally is to modify the timeout variables in `TimeOutWrapper` to something more manageable, like
```typescript
const activeDuration = Duration.fromObject({ minutes: 1 }).as('milliseconds');
const modalDuration = Duration.fromObject({ minutes: 12 }).as('milliseconds');
```
then, **_log in with your EUA rather than local auth_**, as local auth negates the timeout modal, and ensure that aftert 1 minute of inactivity you get a modal that warns you that you have 12 minutes remaining.
Additionally, if you want to see the events that trigger activity, add the following property to `useIdleTimer`
```typescript
onAction(event) {
console.log('user triggered', event?.type);
},
```
- It's best to pull the branch locally and …
> [EASI-3044] Increase activity timeout to 90 minutes

- src/i18n/en-US/draftModelPlan/itSolutions.ts
- src/views/ModelPlan/TaskList/ITSolutions/AddCustomSolution/index.tsx
- src/views/ModelPlan/TaskList/ITSolutions/AddSolution/index.tsx
- src/views/ModelPlan/TaskList/ITSolutions/_components/CheckboxCard/index.tsx
`UpdateOperationalSolution` payload had an incorrect conditional for passing `nameOther` .  It was expecting `selectedSolution` to be falsy, when that isn't the case here
- Fixed the conditonal to explicity check for `OTHER_NEW_PROCESS` to pass `nameOther` to the mutation payload
Had to fix areas where we were treating custom solutions with a key.  We now pass null keys when creating a brand new custom solution.  For the case where we have the `OTHER_NEW_PROCESS` solution as a default, we pass that key and it behaves like `treatAsOther`
Also added a translation key for render `OTHER_NEW_PROCESS` as 'Other new process' on the card once created.
- Check that all code is adequately covered by …
> [NOREF] - Fixed conditional when updating custom solution

- src/views/ModelPlan/ReadOnly/Payments/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/Payments/index.tsx
- Address rogue question popping up (https://oddball.slack.com/archives/C059QQA3HK5/p1689018937456579?thread_ts=1688750264.802819&cid=C059QQA3HK5)
- Change 2
1. This should only show if "Reductions to beneficiary cost-sharing" is selected under claims-based payment types (first question on page 2). 
> [EASI-3091] Bug fix -- Question should only show up if "Reductions to beneficiary cost-sharing" is selected

- .pre-commit-config.yaml
- Remove branch naming check in favor of using GitHub rules
- Try to create a branch in GitHub that doesn't match our expected naming patterns!
> [NOREF] Remove branch naming check

- src/views/App/index.tsx
- src/views/ModelPlan/ReadOnly/_components/FilterView/Banner/index.tsx
- src/views/ModelPlan/ReadOnly/_components/FilterView/Modal/index.tsx
- src/views/ModelPlan/ReadOnly/index.tsx
- Fixed app crash when passing an unmapped filter query param
- Reworked readonly routing to all for filter views to be passed without a page subkey
This is in preparation for the BE to begin supplying filter view links to readonly without needing to specify a subpage
Ex: `${host}/models/${modelID}/read-only`
Ex: `${host}/models/${modelID}/read-only?filter-view=ccw`
Previous the routing didn't allow for filter views without a specified subpage (`model-basics`, etc)
Test out navigation to `${host}/models/${modelID}/read-only` without a subpage , should redirect to `model-basics`
Append a filter-view query param to `${host}/models/${modelID}/read-only` and verify it renders - `${host}/models/${modelID}/read-only?filter-view=ccw`
Try to type in an incorrect filter-view param - should reroute …
> [NOREF] - Filter view view route restructure

- src/components/ShareExport/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/index.tsx
- src/views/ModelPlan/TaskList/_components/TaskListStatus/index.tsx
'Edit Model Plan' button was not hidden for users without access
The button doesn't work due to security constraints, but the button should and is now hidden
Login with Mac user or user who isnt a collaborator on a model plan
Navigate to readonly
Verify the 'Edit Model Plan' is hidden
> [NOREF] - Restricted edit button to users who have access

- src/components/ShareExport/__snapshots__/index.test.tsx.snap
- src/stylesheets/print.scss
- src/views/ModelPlan/ReadOnly/ModelBasics/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/ModelBasics/index.tsx
- src/views/ModelPlan/ReadOnly/__snapshots__/index.test.tsx.snap
- Removed styling from pdf link in readonly basics
Download a readonly pdf and verify blue link styling is gone
> [NOREF] - Removed styling from pdf link

- src/views/ModelPlan/TaskList/index.test.tsx
- src/views/ModelPlan/TaskList/index.tsx
The last updated time on IT Solutions in the task list was incorrect.  There was an incorrect non-null assertion, where null values were actually being passed.  This causes an incorrect datestring comparison.
[Slack thread](https://cmsgov.slack.com/archives/C04B10ZN6A2/p1690895792031639)
- Filtered for null values before comparing
- Added unit test
> [NOREF] - Fixed task list last updated

- src/index.tsx
- src/views/AuthenticationWrapper/index.tsx
MINT deployed and local env were experiencing issues with gql subscription authentication due to a missing okta storage token post login.  The app was using `react-router-dom` for post redirect, not allowing the app to ingest the auth token into its ws connections
This was carried over from EASI, so the same issue may exist there as well.
This resolves the issue, but we may want to dig further to see if it's possible to still use `react-router-dom` for a cleaner user experience
- Changed the `AuthenticationWrapper` redirect to use native browser redirect/hard refresh - post login
- Reverted the  native browser redirect/hard refresh - post login
- Added a lazy config to ws connection to only attempt to init on first subscription
- Wrapped `authToken` in `connectionParams` function
This …
> [NOREF] - Changed post login redirect from react-router to native browser redirect

- pkg/graph/resolvers/model_plan.go
- pkg/graph/schema.resolvers.go
- Use default sender (configured per-env through env vars) instead of trying to send emails from the user who made the GQL call.
- `scripts/dev db:seed`
- Share a model plan through the UI
- Ensure that mailcatcher shows it's coming from `no-reply-mint-localhost@cms.hhs.gov`
> [EASI-3098] Use default sender when sharing model plans

- pkg/email/model_plan_share.go
- pkg/email/templates/model_plan_share_body.html
- pkg/graph/resolvers/model_plan.go
- pkg/models/model_plan.go
- Use `modelPlan.Status` instead of `planBasics.Status` when sending out email for sharing a model plan
- added humanized strings for model plan statuses
- `scripts/dev db:seed`
- Modify some plans statuses
- Share those model plans in the UI
- View the emails in mailcatcher to ensure they appear as expected.
> [EASI-3098] Use Model Status in Share Email

- package.json
- yarn.lock
- Upgrade Cypress from 12 to 13
- No truly breaking changes per the [migration guide](https://docs.cypress.io/guides/references/migration-guide)
- Only change that changes functionality is that video upload is disabled by default. I am considering NOT re-enabling this to see what kind of time save (if any) it makes in our CI test runs
- Ensure cypress tests pass locally and in CI
> [NOREF] Upgrade Cypress from 12 to 13

- docker-compose.override.yml
- Added volume mount for ./cypress directory in CI to alleviate FLAGDATA_FILE issuesd
- Ensure CI E2E tests pass
> [NOREF] Add ./cypress volume mount for backend to address issues in CI

- .github/dependabot.yml
- See https://github.com/CMSgov/easi-app/pull/2185
- Use dependabot groups ([docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups)) to reduce the number of PRs that we need to dig through for each package manager.
- Groups minor/patch PRs in one group and major upgrades in another
- Ensure that the dependabot config matches what would be expected based on the linked documentation
> [NOREF] Use groups for dependabot upgrades

- Dockerfile
- Modify dockerfile to correctly copy to pkg and cmd directories, not to root of workspace
- Fixes issue from https://github.com/CMSgov/mint-app/pull/707
- Running `docker build -t local . --no-cache` locally should build the target that's built on the production build pipeline, which will validate this!
> [NOREF] Fix dockerfile copy command copying to wrong directory

- .envrc
- MINT.postman_collection.json
- docker-compose.backend.yml
- pkg/appconfig/config.go
- pkg/email/address_book.go
- pkg/email/send_feedback.go
- pkg/email/template_service_impl.go
- pkg/email/templates/send_feedback_body.html
- pkg/email/templates/send_feedback_subject.html
- pkg/graph/resolvers/send_feedback_email.go
- pkg/graph/schema.resolvers.go
- pkg/server/routes.go
- Create the email for Send Feedback email
- Backend Resolver for Send Feedback
-  Note optional strings and "" are treated equivalently. They are represented as nullable in the schema to reflect the intended requirements of the form.
- Postman Query to Send Feedback
1. Bring up the app
2. Use the postman query as is to send an email with all fields filled out
3.  Verify the email using [mailcatcher](http://127.0.0.1:1085/)
4. If desired, comment out  parameters in the query to see what the email looks like without optional parameters.
- Always make comments, even if it's minor, or if …
> Easi 3349/send feedback email be

- src/components/Footer/index.tsx
- src/views/ModelPlan/TaskList/ITSolutions/LinkDocuments/__snapshots__/index.test.tsx.snap
- Removed styling `<MainContent />` element on footer that caused it to expand vertically on large screens with empty space
> Fixed styling on footer than made it expand vertically on large screens

- pkg/graph/resolvers/send_feedback_email.go
- The email was displaying `Other` even if the input was an empty string. It also would not populate other if no optional text was populated.
- This will populate `Other`  even if no optional text is provided. It will also populate Other if it isn't selected but the optional usedForOther field is populated
1. Send feedback without selecting other
2. Ensure that it isn't visible in the email
3. Send feedback with other and without optional text
4. Ensure it is visible in the email
5. Send feedback with optional text filled out, but the other option deselected
6. Ensure you can see the other value populated in the email.
- Check that all code is adequately covered by tests - if it isn't feel …
> feat: only populate other in the email if not nil or empty string

- .envrc
- .github/workflows/build_frontend_assets.yml
- docker-compose.frontend.yml
- src/index.tsx
- Introduces environment variable to configure per-env GA Tracking IDs
- Adds a default value to track data when developing locally (uses a different property / tracking ID than any of the other envs)
- Start the server locally
- Use the app
- Navigate to GA and see if data is ingested under the `MINT (Localhost)` property
> [NOREF] GA tracking id env var

- src/components/ShareExport/__snapshots__/index.test.tsx.snap
- src/types/flags.ts
- src/utils/user.test.ts
- src/views/FlagsWrapper/index.tsx
- src/views/ModelPlan/ReadOnly/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/_components/FilterView/Banner/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/_components/FilterView/Banner/index.tsx
- src/views/ModelPlan/TaskList/_components/TaskListSideNav/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/TaskList/_components/TaskListSideNav/index.tsx
- Removed instances of `shareExportEnabled` LD flag
Verify Share/Export behaves the same
> [EASI-3238] - Removed share export ld flag

- src/components/shared/CollapsableLink/index.tsx
- src/views/ModelPlan/ReadOnly/_components/ModelSummary/index.tsx
- src/views/ModelPlan/ReadOnly/index.tsx
The `Read more` link in the model summary was not rendering on load.  This work moves the logic for controlling the state of expanded description to rerender when the summary is collapsed/shown
- Fixed the link in model summary to read more
Verify the read more link for long descriptions renders
To get a long description, populate the Goals textarea in model basics
> [EASI-3488] - Fixed missing read more link on model summary

- pkg/email/templates/plan_discussion_tagged_solution_body.html
- pkg/email/templates/plan_discussion_tagged_user_body.html
- pkg/storage/SQL/discussion_reply/get_by_discussion_id_LOADER.sql
- pkg/storage/SQL/discussion_reply/get_by_id.sql
- pkg/storage/SQL/plan_discussion/get_by_model_plan_id_LOADER.sql
- src/i18n/en-US/draftModelPlan/discussions.ts
- src/views/ModelPlan/Discussions/QuestionAndReply.tsx
- src/views/ModelPlan/Discussions/Replies/index.tsx
- src/views/ModelPlan/Discussions/index.tsx
- src/views/ModelPlan/ReadOnly/Discussions/index.tsx
- Ensured discussion/reply correct sorting through GQL
- Discussions should be sorted newest to oldest
- Replies should be sorted oldest to newest
- Fixes incorrect translation - `View more replies`
- Changed email to open discussion in readonly section for tagged users
- Auto expand replies when opened from email
> [EASI-3590] - Discussion order fix

- src/views/ModelPlan/Discussions/DiscussionModalWrapper.tsx
- src/views/ModelPlan/ReadOnly/Discussions/index.tsx
Natasha noticed in the readonly view that the mention dropdown was appearing in the wrong position.  After a bit of headache, figured some funky css was being propagated due to the missing grid container much higher in the readonly html/css hierarchy
- Fixed the tiptap/mention dropdown position on the readonly view to always render in the same position
Verify the mention dropdown always appears in the correct position in readonly
> [EASI-3753] - Added grid on readonly to mirror task list/stable position

- src/views/ModelPlan/ModelPlanOverview/index.tsx
- src/views/ModelPlan/Table/index.tsx
- src/views/ModelPlan/TaskList/Payment/AnticipateDependencies/index.tsx
- src/views/ModelPlan/TaskList/Payment/BeneficiaryCostSharing/index.tsx
- src/views/ModelPlan/TaskList/Payment/ClaimsBasedPayment/index.tsx
- src/views/ModelPlan/TaskList/Payment/Complexity/index.tsx
- src/views/ModelPlan/TaskList/Payment/FundingSource/index.tsx
- src/views/ModelPlan/TaskList/Payment/NonClaimsBasedPayment/index.tsx
- src/views/ModelPlan/TaskList/Payment/Recover/index.tsx
The home table was never rendering the loading component, as well as the favorites cards on /models
Additional the modelName variable on payments was being rendered as `undefined` while data was loading
- Fixed loading render on the home tables and favorites cards
- Fixed model name rendering `undefined` on Payments
Verify loading component correctly renders on home tables
Verify the favorites cards gets cached after first data fetch
Verify model name does not render `undefined` while data is loading
- Always make comments, even if it's minor, or if you don't understand why something …
> [NOREF] - Fixed loading render issues on home pages and payments

- .github/dependabot.yml
- This PR aims to disable major NPM upgrades being suggested from dependabot, as it was often suggesting PRs with 40+ package upgrades, which is unreasonable for a single PR.
https://github.com/CMSgov/mint-app/pull/857 is an example of one of those PRs!
- Just ensure that this is still a valid dependabot file!
> Disable NPM major package upgrades in dependabot

- cmd/test_email/discussion_reply_emails.go
- pkg/email/discussion_reply_created_originator.go
- pkg/email/templates/discussion_reply_created_originator_body.html
- pkg/email/templates/discussion_reply_created_originator_subject.html
- pkg/graph/resolvers/discussion_emails.go
- Update email subject to be based on model name
- I discussed this with UX. I noticed while deploying that using the username of the user who made the reply results in emails being grouped oddly in gmail. To make them group more logically, the subject will be based on the name of the model plan.
- Update templating efficiency
- in response to suggestion by @OddTomBrooks [here](https://github.com/CMSgov/mint-app/pull/854#discussion_r1428475833), I updated the template logic. We now explicitly pass the count of the number of replies, and only the first two actual replies.
1. Run the app
2. Make a discussion
3. Make a reply
a. confirm the account you used to make the discussion is sent an email
4. Keep making replies
a.  ensure that it always goes to the account that made the discussion
b. …
> NOREF/Discussion Reply email subject and template efficiency

- src/i18n/en-US/readOnly/generalReadOnly.ts
- Correct typo in CM FFS empty state translation
1. Bring up the application
2. Make a new model
3. Navigate to the read only view for dsfwm
4. Confirm the empty state doesn't have an extra s in `leads(s)` --> `lead(s)`
> NOREF: correct typo in emptyStateCMFFS translation

- src/components/ShareExport/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/Beneficiaries/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/GeneralCharacteristics/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/ModelBasics/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/OpsEvalAndLearning/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/ParticipantsAndProviders/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/Payments/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/_components/ReadOnlySection/index.tsx
- src/views/ModelPlan/TaskList/PrepareForClearance/ClearanceReview/__snapshots__/index.test.tsx.snap
There was a change that added `display: flex` to a parent element of a list item, which was inherited and overrode `display:list-item` causing the bullet to not render on the first level bullet point (child bullets renders)
[Figma](https://www.figma.com/file/6tkIhfNfcsKEAkqXo1qvXH/MINT---Read-Only-View?type=design&node-id=3405-204354&mode=design&t=bDso5buWC9hYTemq-0)
- Removed `display-flex` to ensure bullets get rendered
- Fill out some multilselect data, verify that the readonly renders the bullets correctly
- Always make comments, even if it's minor, or if you don't …
> [NOREF] - Fixed bullet not rendering, updated snaps

- src/views/ModelPlan/ReadOnly/_components/ReadOnlySection/index.test.tsx
- src/views/ModelPlan/ReadOnly/_components/ReadOnlySection/index.tsx
Previously readonly enum values were not maintaining the correct order from Figma when rendered.  The BE does not persist order of multiselect.  This work add a util function to order the readonly values as they are defined in the translation file, rather than the default BE order
This work also defines another util function for readonly.  When values have multiple additional info/other values, we need to properly map those to their respective values.  For example `fundingSource` on `Payments` has 4 enum values.  3 of those 4 values all trigger additional fields with text values.  In the readonly, we need to match up those values to their conditional parent values, while in the correct order.
- Added util to correctly order readonly enum values
- Added util function to match up …
> [NOREF] - Added util and test to correctly order readonly items

- migrations/V126__Add_COR_team_role.sql
- pkg/graph/generated/generated.go
- pkg/graph/schema.graphql
- pkg/models/plan_collaborator.go
- src/gql/gen/graphql.ts
- src/i18n/en-US/modelPlan/collaborators.ts
- src/types/graphql-global-types.ts
- Added new enum value for `TeamRole` - `COR` - `Contracting Officer's Representative (COR)` within schema
- Added migration for new value
- Updated translation text for `OACT` -> `Office of the Actuary (OACT)`
- Add a collaborator with one or more roles, consisting of the changes roles
- Verify the roles render correctly in the collaborator table and task list side bar
I think there may be a preexisting issue with the roles not rendering in the csv.  Looking into it, and it will be a followup PR
- Always make comments, even if it's minor, or if you don't understand why something was …
> [EASI-3745] - Collaborator/Team Role updates

- src/components/ShareExport/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/OpsEvalAndLearning/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/OpsEvalAndLearning/index.tsx
- Changed the label to use the correct read only label translation
1. Navigate to `Operations, evaluation, and learning` Read only page 
2. Verify that rogue payments are gone. 
|| |
|---|---|
|Before|![image](https://github.com/CMSgov/mint-app/assets/2349702/bd0fff4a-f617-4bc8-82e6-ca45f6a5bd01)|
|After|![image](https://github.com/CMSgov/mint-app/assets/2349702/aa7078c0-db08-4711-a569-4a11c0631262)|
> [EASI-3906] Remove rogue "Payments" fields in ops, eval, and learning

- .air.conf
- .airDebug.conf
- .airDebugWait.conf
We use AIR for hot reloading our BE dev server. This updates the config to rebuild the app not just for GO file changes, but also if the SQL file changes. This makes it so you don't have to rebuild the container manually when you update a SQL script
1. Bring the app up `scripts/dev up:backend:debug`
2. Modify a SQL file
3. Inspect the backend docker container to make sure that the server re-builds.
> NOREF: Watch SQL files in backend DEV Server

- MINT.postman_collection.json
- migrations/V149__User_Notification_Preferences_Flags_To_Array.sql
- pkg/graph/generated/generated.go
- pkg/graph/resolvers/user_notification_preferences.resolvers.go
- pkg/graph/resolvers/user_notification_preferences_test.go
- pkg/graph/schema/types/user_notification_preferences.graphql
- pkg/models/user_notification_preferences.go
- pkg/notifications/tagged_in_discussion_meta.go
- pkg/notifications/tagged_in_discussion_reply_meta.go
- pkg/notifications/user_notification.go
- pkg/notifications/user_notification_test.go
- pkg/serialization/array_types.go
- pkg/serialization/serialization.go
- src/gql/gen/graphql.ts
- Migrated user notification preferences to use an array instead of a single enum value
- introduced a serialization package to host helper methods to serialize this enum array (originally prototyped in `EASI-1982/generic_type_array_serialization`
- We could have used a pq string array, but it seems important to be able to use receiver methods on this preference type. We will be using this value throughout the application.
1. Use the updated postman collection to update user preferences.
2. Try to remove all preferences, and re-add preferences.
3. Verify the existing logic to not send an email if tagged in a discussion or a reply continues to function as expected.
Note: This code does not enforce that a preference not be duplicated in an entry, for example, IN_APP could be listed twice. …
> [Easi-4043] User notification preferences flag to array

- src/components/ShareExport/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/ModelBasics/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/_components/ReadOnlySection/index.tsx
- src/views/ModelPlan/ReadOnly/_components/ReadOnlySection/util.tsx
- Changed ReadonlySection to render `previousNames` in bullet, rather than plain string
- Updated snapshots
Verify that previous names now render in bullet for Basics and filter views
[Figma](https://www.figma.com/file/6tkIhfNfcsKEAkqXo1qvXH/MINT---Read-Only-View?type=design&node-id=4307-15843&mode=design&t=KpnkYWyv4SVorZBm-0)
> [NOREF] - Fixed previous names readonly render to now render in bullet

- src/views/ModelPlan/ReadOnly/_components/FilterView/BodyContent/index.tsx
- src/views/ModelPlan/TaskList/ITSolutions/Home/__snapshots__/operationalNeedsTable.test.tsx.snap
- src/views/ModelPlan/TaskList/ITSolutions/Home/operationalNeedsTable.tsx
Per slack discussion, slight tweaks to op solutions filter view table
- Revised sort on filter view ops table
- Added bottom border to last row
I left a comment and link in the code about this specific case of sorting
Verify sort and border bottom works as intended
> [NOREF] - Revised sort on filter view ops table, added bottom border to last row

- pkg/graph/resolvers/user_notification_preferences.go
- pkg/sqlqueries/SQL/user_notification_preferences/update.sql
- pkg/storage/user_notification_preferencesStore.go
- Update the check to see if a notification belongs to a user in the app code to make an error clearer. Take the check out of the SQL and make it an app code responsibility.
This will be easiest to test in a deployed environment. A smoke test might be sufficient for now here! If you do want to test this locally,
1. Comment out all notification migrations,
2.  Do some queries or log into the app to make a user account reference
3. Run the migrations to add preference for existing user accounts
4. Verify that updating the notification preference for that user doesn't fail.
- Always make …
> NOREF: Notification Preferences Fix

- src/i18n/en-US/modelPlan/basics.ts
- src/i18n/en-US/modelPlan/beneficiaries.ts
- src/i18n/en-US/modelPlan/generalCharacteristics.ts
- src/i18n/en-US/modelPlan/opsEvalAndLearning.ts
- src/i18n/en-US/modelPlan/participantsAndProviders.ts
- src/i18n/en-US/modelPlan/payments.ts
- src/types/translation.ts
Currently questions that read `Please specify` or `How so` have no directly connection to the parent question.  In preparation for Change History, extending the translation type to allow for this optional field that references the parent gql field.
- Added optional type - `otherParentField`  on `TranslationFieldProperties` 
- Populated task list translation sections with `otherParentField` where applicable
Some questions gave enough information, such as `Please specify what the other geography type is.`
In this case, there is enough context and no parent relation would be needed.
Nothing should really need to be tested as this is prep work for CH
- Check that all code is adequately covered by …
> [EASI-4134] Add parent relation for other type questions

- .github/workflows/change_history_dev_deploy.yml
- .github/workflows/deploy_pipeline.yml
- .github/workflows/deploy_to_environment.yml
- Temporarily disable main deploy to dev
- Introduce temporary pipeline to deploy change history branch to dev
- add variable ENABLE_DEV_DB_CLEAN to enable/disable DB clean in dev
> EASI-4179: temporarily disable main dev deploy

- src/i18n/en-US/auth.ts
- src/i18n/en-US/modelPlan/discussions.ts
- src/i18n/en-US/modelPlanTaskList.ts
I believe that the latest upgrade to i18next changed the key for plurals from `_plural` to `_other`
- Changed instances of `_plural` to `_other`
Verify plurals work on discussions, documents, etc. - anywhere where we key the translation with a count
> [NOREF] Fixed pluralization 

- src/views/ModelPlan/TaskList/GeneralCharacteristics/TargetsAndOptions/index.tsx
- Moved the additional note outside of the boolean conditional
1. Navigate to page 4 of Geography questions
2. `Add an additional note` is visible/accessible regardless of answer to `Is the model targeted at specific geographies?`
> [EASI-4167] Moved Additional Notes outside of the Conditional Render for the Geography Question

- src/hooks/useHandleMutation.ts
- src/views/ModelPlan/TaskList/Basics/index.tsx
- src/views/ModelPlan/TaskList/GeneralCharacteristics/index.tsx
- Fixed locked section with history block
- Moved order of redirect, unblock history
Verify cypress tests pass
Verify you get redirected to locked section page if attempting to navigate to a page that is locked
> [EASI-4291] Fixed locked section with history block

- pkg/models/translation_field.go
- pkg/translatedaudit/translate_foreign_key.go
- pkg/translatedaudit/translate_foreign_key_test.go
- pkg/translatedaudit/translated_audit.go
- pkg/translatedaudit/translated_audit_test.go
- pkg/translatedaudit/translated_audit_test_suite.go
- Generic entry point to translate a foreign key field
-  Implementation for the user_account table reference
- Unit test for user_account table
- Skip translating user_account_preferences table (this will be expanded, but for now just skip the table).
1. Make a plan collaborator
2. Generate audits
3. Verify that user names are the translated value instead of the UUID string FK value.
> [Easi 4278] Change history foreign key fields for User account

- migrations/V155__Translated_Audit.sql
- pkg/graph/schema/types/translated_audit.graphql
- pkg/models/translated_audit.go
- pkg/models/translated_audit_field.go
- pkg/models/translated_audit_meta_base.go
- pkg/models/translated_audit_meta_generic.go
- pkg/sqlqueries/SQL/translated_audit/collection_get_by_model_plan_ids.sql
- pkg/sqlqueries/SQL/translated_audit/create.sql
- pkg/storage/translated_auditStore.go
- pkg/translatedaudit/translated_audit.go
- pkg/translatedaudit/translated_audit_meta_data.go
- src/gql/gen/graphql.ts
- Added a generic audit meta data type 
-  All meta data to be null in the DB
- Add a meta data type to the table
- Fill out the meta data for a discussion reply
NOTE: This meta data work will continue for additional types. PR is being created now to unblock front end work. 
1. Make a discussion
2. Make a reply
3. Translate the audits
4. Verify the data is as expected.
> [Easi 4345] Generic translated audit meta data, discussion reply meta data

- src/components/shared/SectionWrapper/index.tsx
- src/views/ModelPlan/ReadOnly/Beneficiaries/index.tsx
- src/views/ModelPlan/ReadOnly/GeneralCharacteristics/index.tsx
- src/views/ModelPlan/ReadOnly/ModelBasics/index.tsx
- src/views/ModelPlan/ReadOnly/OpsEvalAndLearning/index.tsx
- src/views/ModelPlan/ReadOnly/ParticipantsAndProviders/index.tsx
- src/views/ModelPlan/ReadOnly/Payments/index.tsx
- src/views/ModelPlan/ReadOnly/__snapshots__/index.test.tsx.snap
- src/views/ModelPlan/ReadOnly/_components/Sidenav/index.tsx
- src/views/ModelPlan/ReadOnly/index.scss
- src/views/ModelPlan/ReadOnly/index.tsx
- Adjusted css to make sure sticky filter bar does not hide things behind it
- Created new `scrollToTheFilterBanner` function and passed it down to `SideNav` component
- Add `height-viewpoint` to each of the read only `PageLoading` components to address scroll jitter
> [EASI-4302, EASI-4300] Sticky Filter Bar and Scroll to Top on Read Only Pages

- graphql-schema-linter.config.js
- mappings/export/exportTranslation.ts
- mappings/export/util.ts
- mappings/translation/document_solution_link.json
- mappings/translation/existing_model_link.json
- mappings/translation/plan_document.json
- pkg/graph/model/models_gen.go
- pkg/graph/resolvers/translation.resolvers.go
- pkg/graph/schema/types/existing_model_link_translation.graphql
- pkg/graph/schema/types/plan_document_solution_link_translation.graphql
- pkg/graph/schema/types/translation.graphql
- src/gql/gen/graphql.ts
- src/i18n/en-US/modelPlan/documentSolutionLink.ts
- src/i18n/en-US/modelPlan/documents.ts
- src/i18n/en-US/modelPlan/existingModelLink.ts
- src/types/translation.ts
- src/views/ModelPlan/ReadOnly/_components/ReadOnlySection/util.tsx
The fields in the new translations are just placeholders!  Feel free to add/edit/remove at will!
- Added optional exportOptions translation type for restricted field
- Added two new translation tables for linking tables
- plan_document_solution_link
- existing_model_link
- Export
Verify export and types look correct
> [EASI-4361] Export options, linking table translation

- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/Modal/index.tsx
- src/views/HelpAndKnowledge/SolutionsHelp/SolutionDetails/_components/Contact/index.tsx
- src/views/ModelPlan/ReadOnly/_components/Sidenav/index.tsx
The SideNav component used in readonly and help modal was targeting an element that didnt exist in help modal `scroll-element` and was attemping to call `window.getComputedStyle` on that element, triggering an error.  This fix returns early on element absence.  Additionally I added a scoll element to the modal to snap to the top when navigation changes  
- Early return on scroll function if element is not found
- Fixed incorrect PoC link when viewing from Op solutions
- Added 'scroll-element' id to help modal
Verify navigation works for help solutions, as well as the PoC link
- Always …
> [EASI-4368] Fix missing element scroll, incorrect PoC link

- Dockerfile
- go.mod
- scripts/testsuite
- Upgrade Go version from 1.21 to 1.22.3
- Upgrade go.mod
- Upgrade Dockerfile
- `scripts/dev up` should run/install the new version of Go in Docker, and E2E tests in CI should capture most changes.
- Follow install instructions at https://go.dev/dl/ to download Go 1.22.3
- Ensure `go version` returns the correct go version
> [NOREF] Upgrade go from 1.21 to 1.22.3

- pkg/graph/schema/types/translated_audit.graphql
- pkg/models/operational_solution_subtask.go
- pkg/models/translated_audit_meta_base.go
- pkg/models/translated_audit_meta_operational_solution.go
- pkg/translatedaudit/translated_audit.go
- pkg/translatedaudit/translated_audit_meta_data.go
- pkg/translatedaudit/translated_audit_meta_data_test.go
- pkg/translatedaudit/translated_audit_suite_utils_test.go
- pkg/translatedaudit/translated_audit_test.go
- src/gql/gen/graphql.ts
- Solution subtask can get name from changes fields on delete
- Operational Solution now stores must start, must finish, and status in meta data
- Unit tests added for all current meta data functions
1.Make the new types
2. Make sure they provide the needed info
> [Easi 4407]solution not needed meta

- mappings/translation_test_utilities.go
- pkg/graph/resolvers/translation.resolvers.go
- pkg/models/translation_field.go
- pkg/models/translation_field_test.go
- Add export options as the first priority option to return for a translation with Options
1. Make a change that uses export options ( I suggest plan document restricted status)
2.  Translate the change.
3. Assert that the data was translated with export options and not the regular options.
> [Easi 4360]/change history translation export options

- cypress/e2e/collaborator.spec.js
- cypress/e2e/notification.spec.js
- src/views/App/index.tsx
- src/views/ModelPlan/ReadOnly/index.tsx
- Added redirect for all `read-only` routes to `read-view`
- Added redirect instead of string parse to default to `model-basics`
Verify all attempts to access `read-only` redirect to `read-view`
Verify read view always defaults to `model-basics` if no subroute present
- Include a slash, don't include a trailing slash, both should work
Verify links from emails work
> [EASI-4416, EASI-4445] - Read-only -> Read-view changes

- src/hooks/useHandleMutation.ts
- src/views/ModelPlan/TaskList/GeneralCharacteristics/index.tsx
- Early return on `useHandleMutation` if there are no dirty changes.  This prevents CH from marking as task list section as `In progress` if no changes have been made when entering the form
Verify mutation doesn't get called on task list sections (Basics and GenChar are the only pages that have complex mutations and may come back to in another ticket)
> [NOREF] Mutation handler improvement

- pkg/graph/schema/types/translated_audit.graphql
- pkg/models/translated_audit_meta_operational_solution.go
- pkg/translatedaudit/translated_audit.go
- pkg/translatedaudit/translated_audit_meta_data.go
- pkg/translatedaudit/translated_audit_meta_data_test.go
- pkg/translatedaudit/translated_audit_utils.go
- src/gql/gen/graphql.ts
- Translate Audit Meta Data
- Operational Solution Status
- Document Type
- Document Visibility
- Utility function to translate a single field by providing.
- Updates to Plan Document meta Data paradigm
- don't fail if can't fetch the name even for delete or truncate  
1. Seed the data
2. Verify the translated data meta data is now translated.
> [Easi 4420]/audit meta data translation

- .github/workflows/change_history_dev_deploy.yml
- pkg/translatedaudit/translated_audit.go
- pkg/translatedaudit/translated_audit_test.go
- src/views/HomeNew/__snapshots__/index.test.tsx.snap
It was noted that certain conditions can create a translation error when a field tries to write an empty string to the old, new or translated fields. This is not allowed as the fields are `ZERO_STRINGS` (requiring non empty strings or nil).
To address situations where an answer changes from nil to "", we now convert "" to nil. If the answer is effectively unchanged, the field is not saved as a translated field.
This happened effectively when a new CR was made with an empty note field.
- Create a model plan
- Create a plan CR, enter text in the note field, but then delete all the text
- translate the audit changes.
- verify that there is an entry for the new CR, and also verify that the note field does not render on the front end.
- It's best to pull the branch locally and test it, rather …
> [EASi-4511] Convert empty strings to nil for translations

- pkg/sqlqueries/SQL/translated_audit_queue/update.sql
- pkg/sqlutils/errors.go
- pkg/sqlutils/exec_procedure.go
- pkg/storage/translated_audit_queueStore.go
- pkg/translatedaudit/translated_audit_job_utitilities.go
- pkg/worker/translate_audit_batch_job.go
- pkg/worker/translate_audit_job.go
- pkg/worker/translate_audit_job_test.go
The jobs for change history currently will fail if there is a duplicate entry attempting to translate an audit. This might happen in lower environments based on the timing of the `postgres` database being cleaned, and a mismatch with the faktory reddis instance. This isn't actually an issue though, so we should ideally not fail the job. 
This PR accomplishes that by typing that error, and not failing if so. This also begins to expand error handling for postgres data, so that `errors.As` can be used to determine specific error types. You will note that sqlutils get and select now process all errors. This can be expanded to handle new error types as desired in the future.
Also, the translated audit job is now a sugared logger with the worker JID, internal translated_audit_queue_id, and the …
> [EASi-4520]/Change history job logging

- MINT.postman_collection.json
- migrations/V188__Add_MTO_Category_Reorder_Trigger.sql
- pkg/graph/resolvers/mto_category.go
- pkg/graph/resolvers/mto_category.resolvers.go
- pkg/graph/resolvers/mto_category_test.go
- pkg/graph/schema/types/mto_category.graphql
- pkg/sqlqueries/SQL/mto/category/update.sql
- src/gql/generated/graphql.ts
This is a follow up to https://github.com/CMS-Enterprise/mint-app/pull/1511 after discovering a new requirement to be able to change a parent id of a child category.
A parent can't become a child.
This was accomplished by modifying the trigger to handle when a parent was changed to update the children of the old parent like a delete, and the parent of the new children like an insert. If an order is not specified for a new parent, the app code will provide the max of the current positions, effectively putting it at the end of the categories.
NOTE!!! If you haven't reviewed and approved https://github.com/CMS-Enterprise/mint-app/pull/1511, please review that PR first. This builds on top of that PR, and will be simpler to review in that context.
1.  Run all unit tests
2.  Use Postment
3. …
> [MINT-3212]/category reorder to parent

- MINT.postman_collection.json
- pkg/graph/resolvers/mto_category.go
- pkg/graph/resolvers/mto_milestone.go
- pkg/graph/resolvers/mto_milestone.resolvers.go
- pkg/graph/schema/types/mto_category.graphql
- pkg/graph/schema/types/mto_milestone.graphql
- pkg/models/mto_category.go
- pkg/sqlqueries/SQL/mto/category/get_by_id_LOADER.sql
- pkg/sqlqueries/SQL/mto/milestone/get_by_id_loader.sql
- pkg/sqlqueries/mto_category.go
- pkg/sqlqueries/mto_milestone.go
- pkg/storage/loaders/mto_category.go
- pkg/storage/loaders/mto_milestone.go
- pkg/storage/mto_category.go
- pkg/storage/mto_milestone.go
- src/gql/generated/graphql.ts
1. This implemented a resolver to return a new parent level MTOCategories type on an MTO milestone
a. After syncing, we decided to rely on a parent level call and a dataloader to focus on simple maintainable code, instead of creating a more complicated dataloader that would return both records and deserialize.
2.  Syncing with the FE team, it was determined we should also be able to get a milestone by ID, so we don't have to call this category resolver when we are looking at all milestones for the model
Use the postman queries to
1.  Create an MTO milestone
2. Get the MTO milestone by ID
3.  Verify the Categories information for the milestone.
a. note a nil category will return uncategorized uncategorized
- It's best to pull the branch locally and test it, rather than just looking at the …
> [MINT-3229]milestone category resolvers and milestone by ID

- migrations/V186__Add_MTO_Solution.sql
- pkg/graph/resolvers/mto_milestone.go
- pkg/graph/resolvers/mto_solution.go
1. POC email and POC name are now not editable if you make a custom solution
2. Milestone and solutions sourced from common options now update correctly, and don't attempt to set name and type
1.  Create a solution from a common solution
2. attempt to edit the poc info.
3. Confirm the action fails.
4. Edit other information. Confirm it passes
5. Confirm you can update a milestone made from the common milestone library.
- Don't be afraid to leave comments or ask …
> [NOREF]Constrain  mto solution poc fields

- src/features/ModelPlan/ModelToOperations/_components/Modal/CategoryForm/__snapshots__/index.test.tsx.snap
- src/features/ModelPlan/ModelToOperations/_components/Modal/CategoryForm/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/Modal/MilestoneForm/__snapshots__/index.test.tsx.snap
- src/features/ModelPlan/ModelToOperations/_components/Modal/MilestoneForm/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/Modal/SolutionForm/__snapshots__/index.test.tsx.snap
- src/features/ModelPlan/ModelToOperations/_components/Modal/SolutionForm/index.tsx
- src/i18n/en-US/modelPlan/modelToOperations.ts
Addressing https://cmsgov.slack.com/archives/C01B9TEC65A/p1733169342753359?thread_ts=1733163413.249109&cid=C01B9TEC65A
* use built-in react USWDS required marker in form labels
1.  Navigate to the custom solution modals
2. Put a invalid email address and check to see error message pops up
3. Enter a valid email and check to see that the error message goes away
- Don't be afraid to leave comments or ask questions, especially if you don't understand why something was …
> [NOREF] Email Validation Error Message && Use Built-in React USWDS Required Marker in Form Labels

- pkg/graph/resolvers/mto_milestone_test.go
- Adds in some tests for some existing logic in MTO Milestone resolvers and mutations
> [!IMPORTANT]
> This PR is purposefully _not_ exhaustive - I just wanted to get _some_ tests written for this resolver file so we had somewhere to write other tests, and to validate some of the more complex logic (like Common Milestones creating categories upon their instantiation)
1.  Review the tests in `pkg/graph/resolvers/mto_milestone_test.go` and make sure they all make sense and are readable
2. Make sure CI/CD tests pass!
- e.g. "Approving because the …
> [NOREF] Initial MTO Milestone resolver tests

- MINT.postman_collection.json
- pkg/graph/resolvers/mto_category.go
- pkg/graph/resolvers/mto_category.resolvers.go
- pkg/graph/resolvers/mto_category_test.go
- pkg/graph/schema/types/mto_category.graphql
- pkg/sqlutils/transactions.go
- src/gql/generated/graphql.ts
- Adds a new mutation that creates a standard set of categories and subcategories when called.
- Adds `Resolver` suite tests to cover new behavior
- Adds new Postman query
> [!NOTE]
> This PR adds a `sqlutils.WithTransactionNoReturn` method, which is equivalent to `sqlutils.WithTransaction`, except that it doesn't return any values -- useful for if you need to call a bunch of storage methods as part of a transaction but don't care about a specific return value (just if an error occurred)
> [!CAUTION]
> I took the approach of sequentially calling a storage method as part of a transaction rather than trying to create a complex SQL/Storage method that would bulk insert these (since allowing conflicts and ordering seemed like a difficult solve)
> There's currently a `TODO` in the codebase …
> [MINT-3238] Standard Categories

- MINT.postman_collection.json
- migrations/V187__Add_MTO_Milestone_Solution_Link.sql
- pkg/graph/resolvers/mto_milestone.go
- pkg/graph/resolvers/mto_milestone.resolvers.go
- pkg/graph/resolvers/mto_milestone_test.go
- pkg/graph/schema/types/mto_milestone.graphql
- pkg/sqlqueries/SQL/mto/milestone/delete.sql
- pkg/sqlqueries/mto_milestone.go
- pkg/sqlutils/exec_procedure.go
- pkg/storage/mto_milestone.go
- src/gql/generated/graphql.ts
- Adds API Support (GraphQL mutation) for deleting an MTO milestone
- Adds Postman Query
- Adds resolver test (honestly pretty minimal at this point, maybe could bolster this up)
> [!NOTE]
> This PR also introduces a `sqlutils.ExecProcedure` method, useful for calling delete statements which do not need to return any values
1. Use `scripts/dev db:seed` to populate an MTO with some milestones
2. Optionally create some milestones from the common milestone library and link some solutions
3. Use the postman query to delete those milestones
a. Ensure that the milestones are deleted properly
b. Ensure that any milestone solution links are also deleted (but _not_ the solutions themselves
- When …
> [MINT-3227] API Support for deleting an MTO Milestone

- cmd/dbseed/main.go
- cmd/dbseed/mto.go
- src/app/index.tsx
- src/features/ModelPlan/ModelToOperations/_components/Table/columns.tsx
- src/features/ModelPlan/ModelToOperations/_components/Table/index.test.tsx
- src/features/ModelPlan/ModelToOperations/_components/Table/index.tsx
Previously MTO matrix was hidden if there were no milestones added.  The util in this PR will check if any categories or subcategories have been created as criteria for rendering the MTO matrix - even in the absence of any milestones.  This util will also not count `Uncategorized` as categories/subcategories.
Additionally added a custom apollo cache key and removed toggle icon if no children present
> [!CAUTION]
> We have not yet hooked up a refetch on the form mutations, so you will need to refresh or force rerender in the app to see changes take effect.
1.  Create a model plan and go to matrix
2. Verify empty state
3. Added a category and refresh
4. Verify matrix renders
5. Repeat but this time add a milestone
6. Verify matrix renders
- It's best to pull the branch locally and test it, …
> [NOREF] Show MTO matrix if started

- migrations/V181__Add_MTO_Category.sql
- pkg/graph/resolvers/mto_category.go
Standard category name casing didn't match the category names configured for a common milestone. This standardizes the casing so duplicate categories aren't created
Also, I added a collation to the name column to enforce case insensitivity. See this [pgres documentation](https://www.postgresql.org/docs/current/collation.html#COLLATION-NONDETERMINISTIC)
1.  Create standard categories
2. Create a common milestone that uses the standard category
3. ensure that a duplicate category is not created.
Test the case insensitive table constraint
1. Make a category
2. Make another category with exactly the same name, but different casing. Ensure that this errors
- When approving a PR, provide a reason …
> [NOREF] correct casing to sentence case for standard categories

- .envrc
- .pre-commit-config.yaml
This PR introduces linting to the migration folder! IT uses regex to exclude any migration previous to migration 180.
1.  Run `pre-commit run --all sqlfluff-fix`
2. Ensure that no migrations are changed (for example V80 has indentation that could change)
3. Add and stage a new migration with a number greater than 180, ensure that  `pre-commit run --all sqlfluff-fix` runs against it
Hint, you can look at the files it matches by scrolling up after running the command
- …
> [NOREF] sqlfluff targets migrations after v180
